### ISSUE TITLE
[fix] scan .dat File: cannot read needle header at offset

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#2945]
**Describe the bug**

fix return panic

**System Setup**
```
2.99
```

**Expected behavior**

fix  re-create the index .idx file

**Additional context**

volume.lits
```
          volume id:256  size:257705512  collection:"documents"  file_count:188  delete_count:168  deleted_byte_count:6034807  read_only:true  replica_placement:10  version:3  modified_at_second:1642471870
```

panic logs
```
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset 256960240
I0420 14:10:36    82 volume_read.go:131] new entry needle size:98 rest:112
I0420 14:10:36    82 fix.go:51] key 3060820471888067997 offset 256960240 size 98 disk_size 128 compressed false
I0420 14:10:36    82 fix.go:54] saved 98 with error <nil>
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset 256960368
I0420 14:10:36    82 volume_read.go:131] new entry needle size:0 rest:16
I0420 14:10:36    82 fix.go:51] key 3060820471888067993 offset 256960368 size 0 disk_size 32 compressed false
I0420 14:10:36    82 fix.go:56] skipping deleted file ...
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset 256960400
I0420 14:10:36    82 volume_read.go:131] new entry needle size:0 rest:16
I0420 14:10:36    82 fix.go:51] key 3060820471888067994 offset 256960400 size 0 disk_size 32 compressed false
I0420 14:10:36    82 fix.go:56] skipping deleted file ...
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset 256960432
I0420 14:10:36    82 volume_read.go:131] new entry needle size:0 rest:16
I0420 14:10:36    82 fix.go:51] key 3060820471888067995 offset 256960432 size 0 disk_size 32 compressed false
I0420 14:10:36    82 fix.go:56] skipping deleted file ...
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset 256960464
I0420 14:10:36    82 volume_read.go:131] new entry needle size:0 rest:16
I0420 14:10:36    82 fix.go:51] key 3060820471888067996 offset 256960464 size 0 disk_size 32 compressed false
I0420 14:10:36    82 fix.go:56] skipping deleted file ...
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset 256960496
I0420 14:10:36    82 volume_read.go:131] new entry needle size:0 rest:16
I0420 14:10:36    82 fix.go:51] key 3060820471888067997 offset 256960496 size 0 disk_size 32 compressed false
I0420 14:10:36    82 fix.go:56] skipping deleted file ...
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset 256960528
I0420 14:10:36    82 volume_read.go:131] new entry needle size:228 rest:248
I0420 14:10:36    82 fix.go:51] key 3060820471888067984 offset 256960528 size 228 disk_size 264 compressed false
I0420 14:10:36    82 fix.go:54] saved 228 with error <nil>
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset 256960792
I0420 14:10:36    82 volume_read.go:131] new entry needle size:-1754292226 rest:-1754292200
I0420 14:10:36    82 fix.go:51] key 18340839113111895790 offset 256960792 size -1754292226 disk_size -1754292184 compressed false
I0420 14:10:36    82 fix.go:56] skipping deleted file ...
I0420 14:10:36    82 volume_read.go:124] ==> new entry offset -1497331392
F0420 14:10:36    82 fix.go:125] scan .dat File: cannot read needle header at offset -1497331392: readat /data/documents_256.dat: negative offset
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
	/Users/tochka/GolandProjects/seaweedfs/weed/glog/glog.go:767 +0x8a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x457b640, 0x3, 0xc0005ba000, {0x36f7b94?, 0xc000921d18?}, 0x1?, 0x0)
	/Users/tochka/GolandProjects/seaweedfs/weed/glog/glog.go:718 +0x3ab
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x7fff30538499?, 0x2?, {0x29c1b66, 0x12}, {0xc000921d18, 0x1, 0x1})
	/Users/tochka/GolandProjects/seaweedfs/weed/glog/glog.go:656 +0x110
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/Users/tochka/GolandProjects/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.doFixOneVolume({0x7fff30538499, 0x6}, {0xc00013fac0?, 0x40?}, {0xc00013fac0, 0x12}, 0x100)
	/Users/tochka/GolandProjects/seaweedfs/weed/command/fix.go:125 +0x1d7
github.com/chrislusf/seaweedfs/weed/command.runFix(0x455a898?, {0xc00004c0d0?, 0x1, 0x3?})
	/Users/tochka/GolandProjects/seaweedfs/weed/command/fix.go:106 +0x48d
main.main()
	/Users/tochka/GolandProjects/seaweedfs/weed/weed.go:81 +0x383
```

**Comment by chrislusf** [comment]
very likely this .dat file content is already corrupted around offset 256960792.

**Comment by kmlebedev** [comment]
> very likely this .dat file content is already corrupted around offset 256960792.

file size 261632248
```
/data # ls -l *256*
-rw-rw-r--    1 root     99       261632248 Apr 12 02:02 signator-documents_256.dat
```

Judging by the file size and offset, there are 4,671,456 bytes left where there may be records.
As far as I understand, the needle header turned out to be incorrect and you can try to skip this header and continue reading the file until you find the end of the data with the next needle header.

**Comment by kmlebedev** [comment]
it looks like broken files at the time of interrupted replication

**Comment by kmlebedev** [comment]
```
I0901 07:42:32.682844 volume_read.go:180 ==> new entry offset 1683048
I0901 07:42:32.682856 volume_read.go:187 new entry needle size:-1415995074 rest:-1415995048
I0901 07:42:32.682866 fix.go:51 key 1569328022556466321 offset 1683048 size -1415995074 disk_size -1415995032 compressed false
I0901 07:42:32.682877 fix.go:56 skipping deleted file ...
I0901 07:42:32.682891 volume_read.go:180 ==> new entry offset -1414311984
F0901 07:42:32.682963 fix.go:125 scan .dat File: cannot read needle header at offset -1414311984: readat /data/allo-json_95.dat: negative offset
goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
	/Users/tochka/GolandProjects/seaweedfs/weed/glog/glog.go:766 +0x89
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3eedc20, 0x3, 0xc000380070, {0x324eee0?, 0xc0005cdd18?}, 0x1?, 0x0)
	/Users/tochka/GolandProjects/seaweedfs/weed/glog/glog.go:717 +0x3aa
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0x7ffd6db7f158?, 0x2?, {0x2636300, 0x12}, {0xc0005cdd18, 0x1, 0x1})
	/Users/tochka/GolandProjects/seaweedfs/weed/glog/glog.go:655 +0x10f
github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
	/Users/tochka/GolandProjects/seaweedfs/weed/glog/glog.go:1148
github.com/seaweedfs/seaweedfs/weed/command.doFixOneVolume({0x7ffd6db7f158, 0x6}, {0xc0005f7030?, 0x40?}, {0xc0005f7030, 0x9}, 0x5f)
	/Users/tochka/GolandProjects/seaweedfs/weed/command/fix.go:125 +0x1d7
github.com/seaweedfs/seaweedfs/weed/command.runFix(0x3ecf578?, {0xc0000bc090?, 0x1, 0x1?})
	/Users/tochka/GolandProjects/seaweedfs/weed/command/fix.go:106 +0x48d
main.main()
	/Users/tochka/GolandProjects/seaweedfs/weed/weed.go:81 +0x38c
/data # ls -l /data/allo-json_95.dat
-rw-rw-r--    1 root     99         1728088 Apr  8 12:24 /data/allo-json_95.dat
```

**Comment by kmlebedev** [comment]
@chrislusf  Can I add a skip error parameter? So that fix can save the resulting idx file from what has already been read from the dat file.
```
F1025 16:34:56.324267 fix.go:129 scan .dat File: cannot read needle header at offset -407646224: readat /data/registry_1090.dat: negative offset
goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
	/go/src/github.com/seaweedfs/seaweedfs/weed/glog/glog.go:768 +0x89
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3fb7fc0, 0x3, 0xc0005d6000, {0x32f5255?, 0xc0007bfce8?}, 0x1?, 0x0)
	/go/src/github.com/seaweedfs/seaweedfs/weed/glog/glog.go:719 +0x3aa
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0x7ffd614d303c?, 0x2?, {0x26a62be, 0x12}, {0xc0007bfce8, 0x1, 0x1})
	/go/src/github.com/seaweedfs/seaweedfs/weed/glog/glog.go:657 +0x10f
github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
	/go/src/github.com/seaweedfs/seaweedfs/weed/glog/glog.go:1154
github.com/seaweedfs/seaweedfs/weed/command.doFixOneVolume({0x7ffd614d303c, 0x5}, {0xc0000572f0?, 0x40?}, {0xc0000572f0, 0xf}, 0x442)
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/fix.go:129 +0x1d7
github.com/seaweedfs/seaweedfs/weed/command.runFix(0x3f99438?, {0xc0000500d0?, 0x1, 0x3?})
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/fix.go:110 +0x4f7
main.main()
	/go/src/github.com/seaweedfs/seaweedfs/weed/weed.go:81 +0x38c
```

**Comment by chrislusf** [comment]
Sounds good.
