### ISSUE TITLE
Support Locking via FUSE Mount

### ISSUE THREAD

**Issue by danlsgiga** [seaweedfs/seaweedfs#3384]
**Describe the bug**
When running the `linuxserver/plex:latest` [Docker image](https://hub.docker.com/r/linuxserver/plex) with its `/config` folder mapped to a collection mounted via FUSE (weed mount), the Plex internal SQLite3 DB gets corrupted constantly

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
Ubuntu 22.04 arm64
- output of `weed version`
version 30GB 3.18 475185fb linux arm64
- if using filer, show the content of `filer.toml`
```
[leveldb3]
enabled = true
dir = "/filer"
```
**Expected behavior**
This used to work well in the past but now it renders Plex unusable right after it starts. According to the Plex Docker documentation `Note: the underlying filesystem needs to support file locking. This is known to not be default enabled on remote filesystems like NFS, SMB, and many many others. The 9PFS filesystem used by FreeNAS Corral is known to work but the vast majority will result in database corruption. Use a network share at your own risk.`

Expected behaviour is that Plex can use a seaweedfs fuse mount to store its `/config` folder where it stores all its configs and internal SQLite3 DB.

**Additional context**
I have a full cluster running on top of Nomad using the `seaweedfs-csi-driver` and all applications are working just fine, except for Plex. A way to reproduce this is just by mounting a seaweedfs collection via `weed mount` and when running the docker container passing the `-v /local/path/of/the/mounted/volume:/config`. Plex will output DB crashes on its stderr logging output right after trying to startup.

**Comment by chrislusf** [comment]
can you show the full command to run the docker image?

**Comment by danlsgiga** [comment]
yeah, here it goes:

```shell
docker run -d \
  --name=plex \
  --net=host \
  -e PUID=1000 \
  -e PGID=1000 \
  -e VERSION=docker \
  -v /path/to/weed/mount/target:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/plex:latest
```

**Comment by chrislusf** [comment]
after running the command, then what?

**Comment by chrislusf** [comment]
If started on foreground on an empty folder, there is a command line error.

```
docker run \
  -p 32400:32400 \
  --net=host \
  -e PUID=1000 \
  -e PGID=1000 \
  -e VERSION=docker \
  -v /Users/chrislu/tmp/mm/target:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/plex:latest
WARNING: Published ports are discarded when using host network mode
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/40-chown-files
cont-init: info: /etc/cont-init.d/40-chown-files exited 0
cont-init: info: running /etc/cont-init.d/45-plex-claim
cont-init: info: /etc/cont-init.d/45-plex-claim exited 0
cont-init: info: running /etc/cont-init.d/50-gid-video
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/60-plex-update
Docker is used for versioning skip update check
cont-init: info: /etc/cont-init.d/60-plex-update exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-scripts
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-scripts exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun plex (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
Starting Plex Media Server.
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --platformVersion arg Platform version string
  --vendor arg          Vendor string
  --device arg          Device string
  --model arg           Device model string
  --sentryUrl arg       Sentry URL to upload to
  --sentryKey arg       Sentry Key for the project
  --version arg         Version of the product
  --allowRetries arg    Whether we will allow retries
Traceback (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a806c5905/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py", line 168, in <module>
    run()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a806c5905/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py", line 148, in run
    core = Framework.core.FrameworkCore(bundle_path, FRAMEWORK_DIR, config)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a806c5905/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 148, in __init__
    self.set_value('LastVersion', self.version)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a806c5905/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 551, in set_value
    self.storage.save(self._values_file_path, json_str)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a806c5905/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 86, in save
    shutil.move(tempfile, filename)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/shutil.py", line 325, in move
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/shutil.py", line 153, in copy2
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/shutil.py", line 96, in copyfile
IOError: [Errno 2] No such file or directory: '/config/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.system/._StoredValues'
```

**Comment by danlsgiga** [comment]
I just realized, for the Plex Server to be fully provisioned you need a plex pass account, which I believe you may not have. That's a bummer! 😞 

The error above is kinda expected on the first execution.

**Comment by chrislusf** [comment]
The lock is handled by the native file system. It should not be related. 

Does the problem show up after a restart (if so, make sure the server is completely stopped) or does it happen on a fresh install?

**Comment by danlsgiga** [comment]
it happens on a fresh install

**Comment by chrislusf** [comment]
fixed with https://github.com/seaweedfs/seaweedfs/commit/8a880a139d81b3c0ee14d0f22a2f569abb1a48b6
