### ISSUE TITLE
weedfs-3.22 S3  reports a directory as a file

### ISSUE THREAD

**Issue by tyronecai** [seaweedfs/seaweedfs#3457]
**Describe the bug**

we run weedfs to set up an S3 service,  used by Aapche Flink,  replace the former Minio.
when upgrade to weedfs-3.22, flink jobmanager start up fail, and report  s3://flink/recovery/flink/blob is a file !!!
But actually It is a directory.
![image](https://user-images.githubusercontent.com/3582423/185061458-661565ff-9b70-4df9-a762-06798b574bf8.png)

Roll back to weedfs-3.19, everything is OK

`Caused by: org.apache.hadoop.fs.FileAlreadyExistsException: Path is a file: s3://flink/recovery/flink/blob
        at org.apache.hadoop.fs.s3a.S3AFileSystem.innerMkdirs(S3AFileSystem.java:2042) ~[?:?]
        at org.apache.hadoop.fs.s3a.S3AFileSystem.mkdirs(S3AFileSystem.java:2007) ~[?:?]
        at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2275) ~[hadoop-common-3.3.4.jar:?]
        at org.apache.flink.fs.s3hadoop.common.HadoopFileSystem.mkdirs(HadoopFileSystem.java:183) ~[?:?]
        at org.apache.flink.core.fs.PluginFileSystemFactory$ClassLoaderFixingFileSystem.mkdirs(PluginFileSystemFactory.java:162) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.blob.FileSystemBlobStore.<init>(FileSystemBlobStore.java:64) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.blob.BlobUtils.createFileSystemBlobStore(BlobUtils.java:98) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.blob.BlobUtils.createBlobStoreFromConfig(BlobUtils.java:76) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createHighAvailabilityServices(HighAvailabilityServicesUtils.java:115) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.createHaServices(ClusterEntrypoint.java:338) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.initializeServices(ClusterEntrypoint.java:296) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runCluster(ClusterEntrypoint.java:224) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.lambda$startCluster$1(ClusterEntrypoint.java:178) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at javax.security.auth.Subject.doAs(Unknown Source) ~[?:?]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878) ~[hadoop-common-3.3.4.jar:?]
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.startCluster(ClusterEntrypoint.java:175) ~[flink-dist_2.11-1.12.4.jar:1.12.4]
        ... 2 more`

**System Setup**

Linux CentOS 7 

weedfs version 30GB 3.22 fa4d0093e17f710c3da00545022646cb96a6fd98 linux amd64

weed -v 1 server -volume.port 38080 -dir=/data/seaweedfs/data -s3 -s3.config /data/seaweedfs/config.json

**Comment by chrislusf** [comment]
Do you have some simpler way to reproduce this?

**Comment by tyronecai** [comment]
OK, 
I captured the HTTP stream of S3 service and found the following problems. I hope it will help you




`
tcpdump -S -s0 -nn -i any port 8333 -w8333.pcap
`

Weedfs. version 30GB 3.22 fa4d0093e17f710c3da00545022646cb96a6fd98 linux amd64
![image](https://user-images.githubusercontent.com/3582423/185269421-ae7dc007-ded2-4c1b-988b-cd381f6025dc.png)
`
HEAD /flink-rizhiyi/recovery/flink-rizhiyi/blob HTTP/1.1
Host: 192.168.1.21:8333
amz-sdk-invocation-id: a8306377-8eee-364c-db0a-4afa903fb748
amz-sdk-request: ttl=20220818T004351Z;attempt=1;max=21
amz-sdk-retry: 0/0/500
Authorization: AWS4-HMAC-SHA256 Credential=XXXX
Content-Type: application/octet-stream
User-Agent: Hadoop 3.1.4, aws-sdk-java/1.11.788 Linux/4.18.0-373.el8.x86_64 OpenJDK_64-Bit_Server_VM/25.322-b06 java/1.8.0_322 scala/2.11.12 vendor/BellSoft
x-amz-content-sha256: XXXX
X-Amz-Date: 20220818T004031Z
Connection: Keep-Alive

HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Thu, 18 Aug 2022 00:40:31 GMT
Server: SeaweedFS Filer 30GB 3.22
`



Weedfs version 30GB 3.19 03c6f978f42a55810441c7a5a6c77da567bc99b7 linux amd64
![image](https://user-images.githubusercontent.com/3582423/185269561-9395666c-8097-487c-9809-45844a286c5e.png)
`
HEAD /flink-rizhiyi/recovery/flink-rizhiyi/blob HTTP/1.1
Host: 192.168.1.21:8333
amz-sdk-invocation-id: 9326a5b5-95aa-4011-8495-89111e133986
amz-sdk-request: ttl=20220818T004450Z;attempt=1;max=21
amz-sdk-retry: 0/0/500
Authorization: AWS4-HMAC-SHA256 Credential=XXXX
Content-Type: application/octet-stream
User-Agent: Hadoop 3.1.4, aws-sdk-java/1.11.788 Linux/4.18.0-373.el8.x86_64 OpenJDK_64-Bit_Server_VM/25.322-b06 java/1.8.0_322 scala/2.11.12 vendor/BellSoft
x-amz-content-sha256: XXXX
X-Amz-Date: 20220818T004130Z
Connection: Keep-Alive

HTTP/1.1 404 Not Found
Accept-Ranges: bytes
Content-Length: 309
Content-Type: application/xml
Server: SeaweedFS S3
X-Amz-Request-Id: 1660783290571354717
Date: Thu, 18 Aug 2022 00:41:30 GMT
`



minio version RELEASE.2022-06-07T00-33-41Z
![image](https://user-images.githubusercontent.com/3582423/185269258-8e486920-1a04-4484-a126-855fc46e3611.png)
`
HEAD /flink-rizhiyi/recovery/flink-rizhiyi/blob HTTP/1.1
Host: 192.168.40.107:9000
amz-sdk-invocation-id: 97ef94fe-ae0c-6f0a-e707-fb5619addd2a
amz-sdk-request: ttl=20220818T005952Z;attempt=1;max=21
amz-sdk-retry: 0/0/500
Authorization: AWS4-HMAC-SHA256 Credential=XXXX
Content-Type: application/octet-stream
User-Agent: Hadoop 3.1.4, aws-sdk-java/1.11.788 Linux/4.18.0-373.el8.x86_64 OpenJDK_64-Bit_Server_VM/25.322-b06 java/1.8.0_322 scala/2.11.12 vendor/BellSoft
x-amz-content-sha256: XXXX
X-Amz-Date: 20220818T005632Z
Connection: Keep-Alive

HTTP/1.1 404 Not Found
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 170C4A6C6E055CC4
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Thu, 18 Aug 2022 00:56:32 GMT
`

**Comment by tyronecai** [comment]
> Do you have some simpler way to reproduce this?

https://github.com/seaweedfs/seaweedfs/commit/7457c746f0cc06ed19e97fa24207a252fcf76235

weedfs-3.20 is OK too,
So, is this commit caused the problem ?

**Comment by chrislusf** [comment]
Thanks for all the details, which makes the tricky problem very clear! Added fix 42c6e5251363f0437f22eace84589856ff06f669

**Comment by kmlebedev** [comment]
@chrislusf Need 200 ok just for IsDirectoryKeyObject

**Comment by kmlebedev** [comment]
Usually the directory key is created automatically when creating a nested object, such directory keys do not seem to exist for S3. But if a key / directory was explicitly created, then such keys must exist from the point of view of s3

**Comment by chrislusf** [comment]
@kmlebedev Added special handling for explicitly created folders.
