### ISSUE TITLE
Volume server crashed during vacuum and doesn't want to start

### ISSUE THREAD

**Issue by LuckyFrost** [seaweedfs/seaweedfs#3463]
**Describe the bug**
Volume server crashed during vacuum and doesn't want to start
Start error:
```
Aug 18 20:18:11 seaweedfs-volume[187523]: I0818 15:18:11.812002 volume_loading.go:89 readSuperBlock volume 2774 version 3
Aug 18 20:18:11 seaweedfs-volume[187523]: F0818 15:18:11.812016 volume_loading.go:110 check volume idx file /srv/vweed/xxxx_2774.idx: idx file /srv/vweed/m
ongodb-backup-restic_2774.idx does not exists
Aug 18 20:18:11 seaweedfs-volume[187523]: goroutine 984 [running]:
Aug 18 20:18:11 seaweedfs-volume[187523]: github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/glog/glog.go:766 +0x89
Aug 18 20:18:11 seaweedfs-volume[187523]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3a7e940, 0x3, 0xc0003740e0, {0x2e82c9a?, 0x11?}, 0x2?, 0x0)
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/glog/glog.go:717 +0x3aa
Aug 18 20:18:11 seaweedfs-volume[187523]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0xc00fbfbcb0?, 0x29?, {0x2360615, 0x1c}, {0xc000533c10, 0x2, 0x2})
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/glog/glog.go:655 +0x10f
Aug 18 20:18:11 seaweedfs-volume[187523]: github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/glog/glog.go:1148
Aug 18 20:18:11 seaweedfs-volume[187523]: github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).load(0xc00e0f6c60, 0x1, 0x1, 0x0, 0xa9823d?)
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/storage/volume_loading.go:110 +0x8ec
Aug 18 20:18:11 seaweedfs-volume[187523]: github.com/seaweedfs/seaweedfs/weed/storage.NewVolume({0x7ffe5cd1be8b, 0x8}, {0x7ffe5cd1beca, 0xa}, {0xc00bf47de0, 0x15}, 0xad6, 0x0, 0x0, 0x0, ...)
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/storage/volume.go:60 +0x1da
Aug 18 20:18:11 seaweedfs-volume[187523]: github.com/seaweedfs/seaweedfs/weed/storage.(*DiskLocation).loadExistingVolume(0xc000916300, {0x2935318, 0xc00bf4d180}, 0x0?, 0x1)
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/storage/disk_location.go:161 +0x372
Aug 18 20:18:11 seaweedfs-volume[187523]: github.com/seaweedfs/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes.func2()
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/storage/disk_location.go:201 +0x9a
Aug 18 20:18:11 seaweedfs-volume[187523]: created by github.com/seaweedfs/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes
Aug 18 20:18:11 seaweedfs-volume[187523]: #011/github/workspace/weed/storage/disk_location.go:198 +0xbc
Aug 18 20:18:11 seaweedfs-volume[187523]: I0818 15:18:11.811796 volume_loading.go:136 loading index /srv/vweed/xxxx_2728.idx to memory
Aug 18 20:18:11 seaweedfs-volume[187523]: I0818 15:18:11.811801 disk_location.go:170 data file /mnt/sdc/xxxx_2697.dat, replication=020 v=3 size=2339005272 ttl=
Aug 18 20:18:11 seaweedfs-volume[187523]: I0818 15:18:11.812001 volume_loading.go:136 loading index /srv/vweed/xxxx_2757.idx to memory
Aug 18 20:18:11 seaweedfs-volume[187523]: I0818 15:18:11.812024 volume_loading.go:89 readSuperBlock volume 2778 version 3
Aug 18 20:18:11 systemd[1]: weed-volume.service: Main process exited, code=exited, status=255/n/a
Aug 18 20:18:11 systemd[1]: weed-volume.service: Failed with result 'exit-code'.
```

Error before the fall
```
Aug 18 14:20:53 seaweedfs-master[2832031]: I0818 09:20:53.454216 topology_vacuum.go:73 0 Start vacuuming 2774 on local_volumeserver_addr:8080
Aug 18 14:20:53 seaweedfs-master[2832031]: I0818 09:20:53.454216 topology_vacuum.go:73 1 Start vacuuming 2774 on z.z.z.z:8080
Aug 18 14:20:53 seaweedfs-master[2832031]: I0818 09:20:53.455604 topology_vacuum.go:101 Complete vacuuming 2774 on local_volumeserver_addr:8080
.....
Aug 18 14:24:21 seaweedfs-master[2832031]: I0818 09:24:21.906621 topology_vacuum.go:92 2 vacuum 2774 on n.n.n.n:8080 processed 9758691328 bytes, loadAvg 16.25%
Aug 18 14:24:22 seaweedfs-master[2832031]: volume 3604 processed 8860467200 bytes
Aug 18 14:24:23 seaweedfs-master[2832031]: I0818 09:24:23.004740 topology_vacuum.go:92 2 vacuum 2774 on n.n.n.n:8080 processed 9894786696 bytes, loadAvg 16.25%
Aug 18 14:24:23 seaweedfs-master[2832031]: volume 3604 processed 8996782080 bytes
Aug 18 14:24:24 seaweedfs-master[2832031]: volume 3604 processed 9133096960 bytes
Aug 18 14:24:24 seaweedfs-master[2832031]: I0818 09:24:24.605051 topology_vacuum.go:92 2 vacuum 2774 on n.n.n.n:8080 processed 10032633848 bytes, loadAvg 15.94%
Aug 18 14:24:25 seaweedfs-master[2832031]: I0818 09:24:25.511991 topology_vacuum.go:101 Complete vacuuming 2774 on n.n.n.n:8080
Aug 18 14:24:25 seaweedfs-master[2832031]: I0818 09:24:25.512008 topology_vacuum.go:126 Start Committing vacuum 2774 on local_volumeserver_addr:8080
Aug 18 14:24:25 seaweedfs-volume[2833260]: I0818 09:24:25.512114 volume_vacuum.go:106 Committing volume 2774 vacuuming...
Aug 18 14:24:25 seaweedfs-volume[2833260]: I0818 09:24:25.512540 volume_vacuum.go:128 makeupDiff in CommitCompact volume 2774 failed makeupDiff open /srv/vweed/xxxx_2774.idx failed: open /srv/vweed/xxxx_2774.idx: no such file or directory
Aug 18 14:24:25 seaweedfs-volume[2833260]: I0818 09:24:25.535581 volume_loading.go:89 readSuperBlock volume 2774 version 3
Aug 18 14:24:25 seaweedfs-volume[2833260]: F0818 09:24:25.535593 volume_loading.go:110 check volume idx file /srv/vweed/xxxx_2774.idx: idx file /srv/vweed/xxxx_2774.idx does not exists
Aug 18 14:24:25 seaweedfs-volume[2833260]: goroutine 1564731 [running]:
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/glog/glog.go:766 +0x89
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3a7e940, 0x3, 0xc0001121c0, {0x2e82c9a?, 0xc027489718?}, 0x2?, 0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/glog/glog.go:717 +0x3aa
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0xc018bafd70?, 0x29?, {0x2360615, 0x1c}, {0xc027489718, 0x2, 0x2})
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/glog/glog.go:655 +0x10f
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/glog/glog.go:1148
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).load(0xc00c102a20, 0x1, 0x0, 0x0, 0x2f?)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/storage/volume_loading.go:110 +0x8ec
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).CommitCompact(0xc00c102a20)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/storage/volume_vacuum.go:163 +0x819
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/storage.(*Store).CommitCompactVolume(0x30?, 0x40d97f?)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/storage/store_vacuum.go:33 +0x4c
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/server.(*VolumeServer).VacuumVolumeCommit(0xc00082b200, {0xc033c46d20?, 0x535ec6?}, 0xc033c46d20)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/server/volume_grpc_vacuum.go:72 +0x6c
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/pb/volume_server_pb._VolumeServer_VacuumVolumeCommit_Handler({0x23043e0?, 0xc00082b200}, {0x29343c8, 0xc033c46cf0}, 0xc03c764700, 0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/pb/volume_server_pb/volume_server_grpc.pb.go:933 +0x170
Aug 18 14:24:25 seaweedfs-volume[2833260]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017bc20, {0x2941c80, 0xc066bc9860}, 0xc04f57c120, 0xc02e028cc0, 0x3a67670, 0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
Aug 18 14:24:25 seaweedfs-volume[2833260]: google.golang.org/grpc.(*Server).handleStream(0xc00017bc20, {0x2941c80, 0xc066bc9860}, 0xc04f57c120, 0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
Aug 18 14:24:25 seaweedfs-volume[2833260]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
Aug 18 14:24:25 seaweedfs-volume[2833260]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a
[root@mnt]# less /var/log/messages | grep "Aug 18 14:24:" | grep seaweedfs-volume
Aug 18 14:24:06 seaweedfs-volume[2833260]: I0818 09:24:06.605115 volume_vacuum.go:106 Committing volume 2054 vacuuming...
Aug 18 14:24:06 seaweedfs-volume[2833260]: W0818 09:24:06.725674 volume_info.go:48 unmarshal error: unexpected EOF
Aug 18 14:24:06 seaweedfs-volume[2833260]: W0818 09:24:06.725691 volume_tier.go:31 load volume 2054.vif file: unmarshal error: unexpected EOF
Aug 18 14:24:06 seaweedfs-volume[2833260]: I0818 09:24:06.725718 volume_loading.go:89 readSuperBlock volume 2054 version 3
Aug 18 14:24:06 seaweedfs-volume[2833260]: I0818 09:24:06.725743 volume_loading.go:136 loading index /srv/vweed/xxxx_2054.idx to memory
Aug 18 14:24:25 seaweedfs-volume[2833260]: I0818 09:24:25.512114 volume_vacuum.go:106 Committing volume 2774 vacuuming...
Aug 18 14:24:25 seaweedfs-volume[2833260]: I0818 09:24:25.512540 volume_vacuum.go:128 makeupDiff in CommitCompact volume 2774 failed makeupDiff open /srv/vweed/xxxx_2774.idx failed: open /srv/vweed/xxxx_2774.idx: no such file or directory
Aug 18 14:24:25 seaweedfs-volume[2833260]: I0818 09:24:25.535581 volume_loading.go:89 readSuperBlock volume 2774 version 3
Aug 18 14:24:25 seaweedfs-volume[2833260]: F0818 09:24:25.535593 volume_loading.go:110 check volume idx file /srv/vweed/xxxx_2774.idx: idx file /srv/vweed/xxxx_2774.idx does not exists
Aug 18 14:24:25 seaweedfs-volume[2833260]: goroutine 1564731 [running]:
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/glog/glog.go:766 +0x89
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3a7e940, 0x3, 0xc0001121c0, {0x2e82c9a?, 0xc027489718?}, 0x2?, 0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/glog/glog.go:717 +0x3aa
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0xc018bafd70?, 0x29?, {0x2360615, 0x1c}, {0xc027489718, 0x2, 0x2})
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/glog/glog.go:655 +0x10f
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/glog/glog.go:1148
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).load(0xc00c102a20, 0x1, 0x0, 0x0, 0x2f?)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/storage/volume_loading.go:110 +0x8ec
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).CommitCompact(0xc00c102a20)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/storage/volume_vacuum.go:163 +0x819
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/storage.(*Store).CommitCompactVolume(0x30?, 0x40d97f?)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/storage/store_vacuum.go:33 +0x4c
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/server.(*VolumeServer).VacuumVolumeCommit(0xc00082b200, {0xc033c46d20?, 0x535ec6?}, 0xc033c46d20)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/server/volume_grpc_vacuum.go:72 +0x6c
Aug 18 14:24:25 seaweedfs-volume[2833260]: github.com/seaweedfs/seaweedfs/weed/pb/volume_server_pb._VolumeServer_VacuumVolumeCommit_Handler({0x23043e0?, 0xc00082b200}, {0x29343c8, 0xc033c46cf0}, 0xc03c764700, 0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/github/workspace/weed/pb/volume_server_pb/volume_server_grpc.pb.go:933 +0x170
Aug 18 14:24:25 seaweedfs-volume[2833260]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017bc20, {0x2941c80, 0xc066bc9860}, 0xc04f57c120, 0xc02e028cc0, 0x3a67670, 0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
Aug 18 14:24:25 seaweedfs-volume[2833260]: google.golang.org/grpc.(*Server).handleStream(0xc00017bc20, {0x2941c80, 0xc066bc9860}, 0xc04f57c120, 0x0)
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
Aug 18 14:24:25 seaweedfs-volume[2833260]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
Aug 18 14:24:25 seaweedfs-volume[2833260]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Aug 18 14:24:25 seaweedfs-volume[2833260]: #011/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a
```

**System Setup**
OS version
`Oracle Linux Server 8.6`
output of weed version
`version 8000GB 3.22 fa4d0093e17f710c3da00545022646cb96a6fd98 linux amd64
`

**Comment by chrislusf** [comment]
From the logs and https://github.com/seaweedfs/seaweedfs/issues/3459 , I feel `-dir.idx` here is not working well with multiple `-dir` directories. I will look into this direction.
