### ISSUE TITLE
Multi-process IO to an mmap'ed file has a race condition that will corrupt the stack or cause an inconsistent read

### ISSUE THREAD

**Issue by nickb937** [seaweedfs/seaweedfs#3535]
**Describe the bug**

Using this command will cause the `weed mount` process to hang (high `limit` value makes it easier to lock the process):

`./src/dt/linux.d/dt of=/mnt/test passes=256 limit=256m bs=4k procs=4 enable=mmap`

The stack traces are omnimous because the stack addresses often match with the write patterns:

```
Thread 35 (Thread 0x7fd8a17fa6c0 (LWP 98278) "weed"):
--Type <RET> for more, q to quit, c to continue without paging--
#0  runtime/internal/syscall.Syscall6 () at /usr/lib/go/src/runtime/internal/syscall/asm_linux_amd64.s:36
#1  0x0000000000404553 in syscall.RawSyscall6 (num=18446744073709551104, a1=16, a2=4212078, a3=16, a4=824754553264, a5=0, a6=0, r1=<optimized out>, r2=<optimized out>, errno=<optimized out>) at /usr/lib/go/src/runtime/internal/syscall/syscall_linux.go:38
#2  0x000000000048b2a8 in syscall.Syscall (trap=0, a1=16, a2=824754553264, a3=131280, r1=<optimized out>, r2=<optimized out>, err=<optimized out>) at /usr/lib/go/src/syscall/syscall_linux.go:81
#3  0x0000000000488d45 in syscall.read (fd=<optimized out>, p=..., n=<optimized out>, err=...) at /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:696
#4  0x0000000001cc731b in syscall.Read (fd=-512, p=..., n=<optimized out>, err=...) at /usr/lib/go/src/syscall/syscall_unix.go:183
#5  github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest.func1 () at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:322
#6  github.com/hanwen/go-fuse/v2/fuse.handleEINTR (err=..., fn=<optimized out>) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:297
#7  github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest (ms=0xc000713760, exitIdle=<optimized out>, req=0xc0061e6000, code=0) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:320
#8  0x0000000001cc8112 in github.com/hanwen/go-fuse/v2/fuse.(*Server).loop (ms=0xc000713760, exitIdle=true) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:465
#9  0x0000000001cc782b in github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest.func3 () at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:354
#10 0x0000000000470aa1 in runtime.goexit () at /usr/lib/go/src/runtime/asm_amd64.s:1594
#11 0x0000000000000001 in ?? ()
#12 0x0000000002e00000 in runtime[pclntab] ()
#13 0x0000000003000000 in runtime[pclntab] ()
#14 0x170f94a58bdb8831 in ?? ()
#15 0x000000c01de30000 in ?? ()
#16 0x39c39c3939c39c39 in ?? ()
#17 0x39c39c3939c39c39 in ?? ()
#18 0x39c39c3939c39c39 in ?? ()
#19 0x39c39c3939c39c39 in ?? ()
#20 0x39c39c3939c39c39 in ?? ()
...
```

```
Thread 14 (Thread 0x7fd9017fa6c0 (LWP 98159) "weed"):
#0  runtime/internal/syscall.Syscall6 () at /usr/lib/go/src/runtime/internal/syscall/asm_linux_amd64.s:36
#1  0x0000000000404553 in syscall.RawSyscall6 (num=18446744073709551104, a1=16, a2=4212078, a3=16, a4=824978702768, a5=0, a6=0, r1=<optimized out>, r2=<optimized out>, errno=<optimized out>) at /usr/lib/go/src/runtime/internal/syscall/syscall_linux.go:38
#2  0x000000000048b2a8 in syscall.Syscall (trap=0, a1=16, a2=824978702768, a3=131280, r1=<optimized out>, r2=<optimized out>, err=<optimized out>) at /usr/lib/go/src/syscall/syscall_linux.go:81
#3  0x0000000000488d45 in syscall.read (fd=<optimized out>, p=..., n=<optimized out>, err=...) at /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:696
#4  0x0000000001cc731b in syscall.Read (fd=-512, p=..., n=<optimized out>, err=...) at /usr/lib/go/src/syscall/syscall_unix.go:183
#5  github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest.func1 () at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:322
#6  github.com/hanwen/go-fuse/v2/fuse.handleEINTR (err=..., fn=<optimized out>) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:297
#7  github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest (ms=0xc000713760, exitIdle=<optimized out>, req=0xc0061e7200, code=0) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:320
#8  0x0000000001cc8112 in github.com/hanwen/go-fuse/v2/fuse.(*Server).loop (ms=0xc000713760, exitIdle=true) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:465
#9  0x0000000001cc782b in github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest.func3 () at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:354
#10 0x0000000000470aa1 in runtime.goexit () at /usr/lib/go/src/runtime/asm_amd64.s:1594
#11 0x0000000000000001 in ?? ()
#12 0x0000000002e00000 in runtime[pclntab] ()
#13 0x0000000003000000 in runtime[pclntab] ()
#14 0x170f94a58bdb8831 in ?? ()
#15 0x000000c0081ae000 in ?? ()
#16 0x0000000000000001 in ?? ()
#182 0x0000000000000001 in ?? ()
#183 0x000000c000c00000 in ?? ()
#184 0x000000000043eaf6 in runtime.gopark (unlockf=<optimized out>, lock=<optimized out>, reason=<optimized out>, traceEv=<optimized out>, traceskip=824978702768) at /usr/lib/go/src/runtime/proc.go:363
#185 0x000000000044fb2f in runtime.semacquire1 (addr=<optimized out>, lifo=false, profile=4639833, skipframes=78868612422390) at /usr/lib/go/src/runtime/sema.go:158
#186 0x0000000000000000 in ?? ()

```

```
Thread 21 (Thread 0x7fd8e17fa6c0 (LWP 98182) "weed"):
#0  runtime/internal/syscall.Syscall6 () at /usr/lib/go/src/runtime/internal/syscall/asm_linux_amd64.s:36
#1  0x0000000000404553 in syscall.RawSyscall6 (num=18446744073709551104, a1=16, a2=4212078, a3=16, a4=825007776176, a5=0, a6=0, r1=<optimized out>, r2=<optimized out>, errno=<optimized out>) at /usr/lib/go/src/runtime/internal/syscall/syscall_linux.go:38
#2  0x000000000048b2a8 in syscall.Syscall (trap=0, a1=16, a2=825007776176, a3=131280, r1=<optimized out>, r2=<optimized out>, err=<optimized out>) at /usr/lib/go/src/syscall/syscall_linux.go:81
#3  0x0000000000488d45 in syscall.read (fd=<optimized out>, p=..., n=<optimized out>, err=...) at /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:696
#4  0x0000000001cc731b in syscall.Read (fd=-512, p=..., n=<optimized out>, err=...) at /usr/lib/go/src/syscall/syscall_unix.go:183
#5  github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest.func1 () at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:322
#6  github.com/hanwen/go-fuse/v2/fuse.handleEINTR (err=..., fn=<optimized out>) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:297
#7  github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest (ms=0xc000713760, exitIdle=<optimized out>, req=0xc0061e6480, code=0) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:320
#8  0x0000000001cc8112 in github.com/hanwen/go-fuse/v2/fuse.(*Server).loop (ms=0xc000713760, exitIdle=true) at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:465
#9  0x0000000001cc782b in github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest.func3 () at /home/nickb/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:354
#10 0x0000000000470aa1 in runtime.goexit () at /usr/lib/go/src/runtime/asm_amd64.s:1594
#11 0x0000000000000001 in ?? ()
#12 0x0000000002e00000 in runtime[pclntab] ()
#13 0x0000000003000000 in runtime[pclntab] ()
#14 0x170f94a58bdb8831 in ?? ()
#15 0x000000c0081a8000 in ?? ()
#16 0x00001001000000f1 in ?? ()
#17 0x00001001000000f1 in ?? ()
...
#119 0x00001001000000f1 in ?? ()
#120 0x00001001000000f1 in ?? ()
#121 0x00001001000000f1 in ?? ()
#122 0x00001001000000f1 in ?? ()
#123 0x0000000000845b4a in google.golang.org/grpc/metadata.FromOutgoingContextRaw (ctx=..., ~r0=<optimized out>, ~r1=..., ~r2=<optimized out>) at /home/nickb/go/pkg/mod/google.golang.org/grpc@v1.48.0/metadata/metadata.go:207
#124 0x0000000000926ef9 in google.golang.org/grpc.newClientStream (ctx=<error reading variable: access outside bounds of object referenced via synthetic pointer>, desc=0x40456e <runtime/internal/syscall.Syscall6+14>, cc=0x10, method=..., opts=..., ~b0=..., ~b0=..., err=...) at /home/nickb/go/pkg/mod/google.golang.org/grpc@v1.48.0/stream.go:170
#125 0x0000000000000050 in ?? ()
#126 0x00000000021763e0 in type.* ()
#127 0x0000000000000000 in ?? ()
```

Using this command (you may need to run it several times), will expose an inconsistent read:
`./src/dt/linux.d/dt of=/mnt/test passes=256 limit=131072 bs=4k procs=32 enable=mmap`

```
dt (j:1 t:2): Read Statistics:
dt (j:1 t:2):       Job Information Reported: Job 1, Thread 2
dt (j:1 t:2):        Current Thread Reported: 2/4
dt (j:1 t:2):      Data pattern read/written: 0xaaaaaaaa
dt (j:1 t:2):        Total records processed: 32 @ 4096 bytes/record (4.000 Kbytes)
dt (j:1 t:2):        Total bytes transferred: 131072 (128.000 Kbytes, 0.125 Mbytes)
dt (j:1 t:2):         Average transfer rates: 124949476 bytes/sec, 122020.972 Kbytes/sec, 119.161 Mbytes/sec
dt (j:1 t:2):        Number I/O's per second: 30505.243
dt (j:1 t:2):         Number seconds per I/O: 0.0000 (0.03ms)
dt (j:1 t:2):         Total passes completed: 188/256
dt (j:1 t:2):          Total errors detected: 0/1
dt (j:1 t:2):             Total elapsed time: 00m00.00s
dt (j:1 t:2):              Total system time: 00m00.01s
dt (j:1 t:2):                Total user time: 00m00.00s
dt (j:1 t:2):                  Starting time: Sun Aug 28 19:07:50 2022
dt (j:1 t:2):                    Ending time: Sun Aug 28 19:07:51 2022
dt (j:1 t:1): The incorrect data starts at memory address 0x00007f6441118000 (for Robin's debug! :)
dt (j:1 t:1): The incorrect data starts at file offset 000000000000000000 (marked by asterisk '*')
dt (j:1 t:1): Dumping Data File offsets (base = 0, mismatch offset = 0, limit = 512 bytes):
dt (j:1 t:1):                   / Block
dt (j:1 t:1):       File Offset / Index 
dt (j:1 t:1): 000000000000000000/     0 |*aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000016/    16 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000032/    32 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000048/    48 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000064/    64 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000080/    80 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000096/    96 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000112/   112 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000128/   128 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000144/   144 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000160/   160 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000176/   176 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000192/   192 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000208/   208 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000224/   224 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000240/   240 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000256/   256 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000272/   272 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000288/   288 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000304/   304 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000320/   320 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000336/   336 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000352/   352 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000368/   368 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000384/   384 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000400/   400 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000416/   416 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000432/   432 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000448/   448 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000464/   464 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000480/   480 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 000000000000000496/   496 | aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa "                "
dt (j:1 t:1): 
dt (j:1 t:1): 
dt (j:1 t:1): Writing corrupted data to file dt-nickb-cc5cd343-5ce5-3ad2-0d36-67d00ca78529.data-j1t1p98322-CORRUPT0-j1t1, from buffer 0x7f6441118000, 4096 bytes...
dt (j:1 t:1): Rereading and verifying record data using Direct I/O...
dt (j:1 t:1): Record #1 - Reading 4096 bytes (8 blocks) into buffer 0x7f643c002000, Relative LBA's 0 - 7 (offset 0)
Segmentation fault (core dumped)
```

I think this problem relates to why Sonarr crashes on startup in https://github.com/seaweedfs/seaweedfs/issues/2609, since it seems to be related to two child processes accessing the same file using mmap.

**System Setup**

weed version `https://github.com/seaweedfs/seaweedfs/commit/089446f5b16ada234a7d3890dfc756311cc8d1d5`
OS archlinux running linux 5.9.3

Using `dt` as a file-system write pattern tester

```
git clone https://github.com/RobinTMiller/dt
~/go/bin/weed server -dir /tmp/weed-data
~/go/bin/weed -v=4 filer
sudo ~/go/bin/weed mount -dir=/mnt
./src/dt/linux.d/dt of=/mnt/test passes=32 limit=131072 bs=4k procs=32 enable=mmap
```

**Expected behavior**

`dt` should complete successfully without error

**Comment by chrislusf** [comment]
Thanks! This is a very good test!

**Comment by Woellchen** [comment]
@nickb937 Could you check again with 2240333b9a4b9ac5769fbb5878c84162a32ec4c5 when you find a moment? I believe it should be fixed.

**Comment by nickb937** [comment]
Checked. LGTM
