### ISSUE TITLE
Periodic SIGSEGV with mount with caching enabled

### ISSUE THREAD

**Issue by nickb937** [seaweedfs/seaweedfs#3940]
**Describe the bug**

I am getting this periodic `mount` SIGSEGV, which happens anywhere between 1 and 7 days after the mount-point has started:

```
I1102 03:09:04.518153 needle_map_leveldb.go:105 generateLevelDbFile /local/cache_dir/plex-config/ff882414/c0_2_0.ldb, watermark 0, num of entries:0
I1102 03:09:04.543613 needle_map_leveldb.go:57 Loading /local/cache_dir/plex-config/ff882414/c0_2_0.ldb... , watermark: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x471f61]

goroutine 124008 [running]:
github.com/karlseguin/ccache/v2.(*Cache).bucket(0xc000038050, {0x0?, 0xc003a570e0?})
	/go/pkg/mod/github.com/karlseguin/ccache/v2@v2.0.8/cache.go:212 +0x38
github.com/karlseguin/ccache/v2.(*Cache).Get(0xc000038050, {0x0, 0x12})
	/go/pkg/mod/github.com/karlseguin/ccache/v2@v2.0.8/cache.go:92 +0x2c
github.com/seaweedfs/seaweedfs/weed/util/chunk_cache.(*ChunkCacheInMemory).readChunkAt(0x1000?, {0xc00f93b400, 0x400, 0xc00e480000?}, {0x0?, 0xc00f93b000?}, 0x0)
	/go/src/github.com/seaweedfs/seaweedfs/weed/util/chunk_cache/chunk_cache_in_memory.go:48 +0x3a
github.com/seaweedfs/seaweedfs/weed/util/chunk_cache.(*TieredChunkCache).ReadChunkAt(0xc0000380a0, {0xc00f93b400, 0x400, 0xc00}, {0x0, 0x12}, 0x0)
	/go/src/github.com/seaweedfs/seaweedfs/weed/util/chunk_cache/chunk_cache.go:56 +0x155
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).readChunkSliceAt(0xc000e7bc70, {0xc00f93b400, 0x400, 0xc00}, 0xc000e53ef0, {0xc000e4a6c0?, 0x2?, 0xc5b1a0?}, 0x0?)
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/reader_at.go:183 +0x95
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).doReadAt(0xc000e7bc70, {0xc00f93b000, 0x1000, 0x1000}, 0x4daa000)
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/reader_at.go:145 +0x3f3
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).ReadAt(0xc00e853ad8?, {0xc00f93b000?, 0x3ad7d20?, 0xc00e853bf0?}, 0x1cf3254?)
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/reader_at.go:115 +0x11e
github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).readFromChunks(0xc002b66000, {0xc00f93b000, 0x1000, 0x1000}, 0x4daa000)
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/filehandle_read.go:75 +0x756
github.com/seaweedfs/seaweedfs/weed/mount.readDataByFileHandle({0xc00f93b000, 0x1000, 0x1000}, 0xc002b66000, 0x4daa000)
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/weedfs_file_read.go:62 +0xf8
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).Read(0x47b8ae?, 0xc000a7bb00?, 0xc000a7bc98, {0xc00f93b000, 0x1000, 0x1000})
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/weedfs_file_read.go:47 +0x108
github.com/hanwen/go-fuse/v2/fuse.doRead(0xc000950160, 0xc000a7bb00)
	/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/opcode.go:374 +0x83
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000950160, 0xc000a7bb00)
	/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:514 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000950160, 0xa0?)
	/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:487 +0x108
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
	/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:354 +0x53e
E1102 03:09:05.032147 mounter.go:75 weed mount exit, pid: 24, path: /local/csi/staging/plex-config/rw-file-system-single-node-writer, error: exit status 2
```

**System Setup**
- weed version is 3.32
- arch-linux 6.0

Weed mount called like this (from the CSI driver):
```
- weed -logtostderr=true mount -dirAutoCreate=true -umask=000 -dir=/local/csi/staging/plex-config/rw-file-system-single-node-writer -collection=plex-config -filer=localhost:8888 -filer.path=/buckets/plex-config -cacheCapacityMB=8 -localSocket=/tmp/seaweedfs-mount-1840377979.sock -replication=000 -cacheDir=/local/cache_dir/plex-config -concurrentWriters=32
```
```
/usr/local/bin/weed filer -master=192.168.1.253:9333,192.168.1.254:9333,192.168.1.252:9333 -ip 192.168.1.10 -port 8888
/usr/local/bin/weed volume -dir=/seaweedfs -mserver=192.168.1.253:9333,192.168.1.254:9333,192.168.1.252:9333 -port=8091 -port.grpc=18091 -ip=192.168.1.10 -max=30000 -index=leveldb -dataCenter=shed -rack=tv
```

filer configured to store metadata in a Galera cluster (mysql).

**Additional context**
I suspect this is a race condition involving regular read-write IO to the same file in the client application.

**Comment by SigmaStar** [comment]
I met the same error! the error looks like:
![image](https://user-images.githubusercontent.com/22829962/202055975-71cc70f2-3029-44ab-83af-806d3d896034.png)

**Comment by paochiang** [comment]
hi @nickb937 
If the cache is disabled, will there be a periodic SIGSEGV problem?

**Comment by nickb937** [comment]
With the cache disabled, I still get a periodic SIGSEGV, just a different SIGSEGV:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x11 pc=0x50e3f9]

goroutine 395463 [running]:
strings.LastIndexByte(...)
	/usr/local/go/src/strings/strings.go:227
strings.LastIndex({0x0?, 0xc00cd99ea0?}, {0x294636a?, 0xc001c8f7e8?})
	/usr/local/go/src/strings/strings.go:82 +0x2d9
github.com/seaweedfs/seaweedfs/weed/filer.VolumeId(...)
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/stream.go:388
github.com/seaweedfs/seaweedfs/weed/filer.LookupFn.func1({0x0, 0x12})
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/reader_at.go:35 +0x85
github.com/seaweedfs/seaweedfs/weed/filer.fetchChunkRange({0xc00cb12c00, 0x400, 0x400}, 0x7fbd4ccd0938?, {0x0, 0x12}, {0x0, 0x0, 0x0}, 0x0, ...)
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/filechunk_manifest.go:120 +0x75
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).readChunkSliceAt(0xc0018ac730, {0xc00cb12c00, 0x400, 0x400}, 0xc00188fc20, {0xc001a8a498?, 0x7fbd4c4abb00?, 0x0?}, 0x46ed8e?)
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/reader_at.go:187 +0x105
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).doReadAt(0xc0018ac730, {0xc00cb12000, 0x1000, 0x1000}, 0x577000)
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/reader_at.go:145 +0x3f3
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).ReadAt(0xc00fb7bad8?, {0xc00cb12000?, 0x1000?, 0xc00fb7bbf0?}, 0x1cf3254?)
	/go/src/github.com/seaweedfs/seaweedfs/weed/filer/reader_at.go:115 +0x11e
github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).readFromChunks(0xc009782900, {0xc00cb12000, 0x1000, 0x1000}, 0x577000)
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/filehandle_read.go:75 +0x756
github.com/seaweedfs/seaweedfs/weed/mount.readDataByFileHandle({0xc00cb12000, 0x1000, 0x1000}, 0xc009782900, 0x577000)
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/weedfs_file_read.go:62 +0xf8
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).Read(0x47b8ae?, 0xc00dfd6900?, 0xc00dfd6a98, {0xc00cb12000, 0x1000, 0x1000})
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/weedfs_file_read.go:47 +0x108
github.com/hanwen/go-fuse/v2/fuse.doRead(0xc00071cf20, 0xc00dfd6900)
	/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/opcode.go:374 +0x83
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc00071cf20, 0xc00dfd6900)
	/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:514 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc00071cf20, 0xc0?)
	/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:487 +0x108
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
	/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:354 +0x53e
```

**Comment by SigmaStar** [comment]
Are you reading or writing with multiple threads or processes?

**Comment by nickb937** [comment]
Single host, multi process & multi threaded IO to the same filesystem

**Comment by paochiang** [comment]
> With the cache disabled, I still get a periodic SIGSEGV, just a different SIGSEGV:

Can you provide the steps to reproduce?
