### ISSUE TITLE
filer server bug： RUnlock of unlocked RWMutex

### ISSUE THREAD

**Issue by huamr** [seaweedfs/seaweedfs#3962]
version : 2.67

filer server  Exit  exception
 

![seaweed-bug](https://user-images.githubusercontent.com/28745710/200754557-8943e3bb-3eb8-4d22-84e1-306e1ccbdc32.png)

**Comment by chrislusf** [comment]
Not sure why. The code is as simple as this and do not know how to fix this. Could be a golang runtime error?
```
func (vc *vidMap) GetLocations(vid uint32) (locations []Location, found bool) {
	vc.RLock()
	defer vc.RUnlock() // failed here

	locations, found = vc.vid2Locations[vid]
	return
}
```

**Comment by huamr** [comment]
[filer.out.1000.txt](https://github.com/seaweedfs/seaweedfs/files/10268914/filer.out.1000.txt)

**Comment by huamr** [comment]
goroutine 12047585 [running]:
runtime.throw({0x2417b83, 0x7f9f6048a3b8})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc00133d230 sp=0xc00133d200 pc=0x443a71
sync.throw({0x2417b83, 0x7f9f6048d4d8})
	/usr/local/go/src/runtime/panic.go:1184 +0x1e fp=0xc00133d250 sp=0xc00133d230 pc=0x47209e
sync.(*RWMutex).rUnlockSlow(0xc000fa9460, 0x0)
	/usr/local/go/src/sync/rwmutex.go:93 +0x39 fp=0xc00133d278 sp=0xc00133d250 pc=0x4828f9
sync.(*RWMutex).RUnlock(0x0)
	/usr/local/go/src/sync/rwmutex.go:83 +0x2a fp=0xc00133d298 sp=0xc00133d278 pc=0x48288a
github.com/chrislusf/seaweedfs/weed/wdclient.(*vidMap).GetLocations·dwrap·1()
	/usr/local/seaweedfs-2.67/weed/wdclient/vid_map.go:110 +0x26 fp=0xc00133d2b0 sp=0xc00133d298 pc=0xb375c6
github.com/chrislusf/seaweedfs/weed/wdclient.(*vidMap).GetLocations(0xc00657d518, 0x4)
	/usr/local/seaweedfs-2.67/weed/wdclient/vid_map.go:113 +0xd7 fp=0xc00133d310 sp=0xc00133d2b0 pc=0xb37537
github.com/chrislusf/seaweedfs/weed/wdclient.(*vidMap).LookupVolumeServerUrl(0xc000fa9460, {0xc00657d518, 0x4})
	/usr/local/seaweedfs-2.67/weed/wdclient/vid_map.go:62 +0x74 fp=0xc00133d418 sp=0xc00133d310 pc=0xb36b34
github.com/chrislusf/seaweedfs/weed/wdclient.(*vidMap).LookupFileId(0x0, {0xc00657d518, 0x13})

**Comment by huamr** [comment]
又出现锁释放的问题了，，可以考虑使用无锁的方式优化吗，，写时复制等

**Comment by huamr** [comment]
@chrislusf
