### ISSUE TITLE
Reading a file from Spark (pyspark) using S3 API

### ISSUE THREAD

**Issue by bsbodden** [seaweedfs/seaweedfs#4043]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

**Describe the bug**
In pyspark I can interact with the Seaweed S3 instance via boto but not via the connectors as shown in https://github.com/seaweedfs/seaweedfs/wiki/HDFS-via-S3-connector

**System Setup**
- Mac OS Monterey - Docker using docker-compose from `docker/seaweedfs-compose.yml`

**Expected behavior**
Expect the file to be read, instead it fails with a bucket does not exist.

**Test with aws cli**

I've created a bucket, put a file in it and can see the file and download it with a presign URL:

```
➜ aws --endpoint-url http://localhost:8333 s3 mb s3://opensky
make_bucket: opensky
➜ aws --endpoint-url http://localhost:8333 s3 ls             
2022-12-08 10:48:55 opensky
➜ aws --endpoint-url http://localhost:8333 s3 cp states_2020-05-25-00.avro s3://opensky
upload: states_2020-05-25-00.avro to s3://opensky/states_2020-05-25-00.avro
➜ aws --endpoint-url http://127.0.0.1:8333 s3 ls opensky
2022-12-08 10:55:41   42857835 states_2020-05-25-00.avro
➜ aws --endpoint-url http://localhost:8333 s3 presign s3://opensky/states_2020-05-25-00.avro
http://localhost:8333/opensky/states_2020-05-25-00.avro?X-Amz-Algorithm=...
```
**PySpark code output**

Launched using:
```
spark-submit --jars lib/spark-redis_2.12-3.1.0-SNAPSHOT-jar-with-dependencies.jar --packages org.apache.spark:spark-avro_2.12:3.3.1,org.apache.hadoop:hadoop-aws:3.3.2 seaweed_test.py
```

Part that works with boto - correctly list the bucket:

```bash
22/12/08 12:36:34 INFO __main__: Running Application...
22/12/08 12:36:34 INFO __main__: Hadoop version = 3.3.2
22/12/08 12:36:34 INFO __main__: Buckets="[{CreationDate=2022-12-08T10:48:55.000-0700, Name=opensky}]" Owner="{DisplayName=, ID=}" ResponseMetadata="{HTTPHeaders={date=Thu, 08 Dec 2022 19:36:34 GMT, content-length=292, server=SeaweedFS S3, content-type=application/xml, x-amz-request-id=1670528194440655595, accept-ranges=bytes}, RequestId=1670528194440655595, HTTPStatusCode=200, HostId=, RetryAttempts=0}"
```

Part that does not work with `spark.read.format.load`:

```
22/12/08 12:36:35 INFO DirectoryPolicyImpl: Directory markers will be kept
22/12/08 12:36:36 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://127.0.0.1:8333/opensky/states_2020-05-25-00.avro.
org.apache.hadoop.fs.s3a.UnknownStoreException: `s3a://127.0.0.1:8333/opensky/states_2020-05-25-00.avro': getFileStatus on s3a://127.0.0.1:8333/opensky/states_2020-05-25-00.avro: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1670528196132359420; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null:NoSuchBucket: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1670528196132359420; S3 Extended Request ID: null; Proxy: null)
        at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:263)
        at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:175)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3858)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:3688)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$isDirectory$35(S3AFileSystem.java:4724)
        at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
        at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2356)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.isDirectory(S3AFileSystem.java:4722)
        at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:185)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1670528196132359420; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
```

**PySpark code: **

```
import argparse
import os
from pyspark.sql import SparkSession
from pyspark import SparkContext, SparkConf, SQLContext
from pyspark.sql.functions import *
import boto3

conf = (
    SparkConf()
    .setAppName("Spark SeaWeedFS Test")
    .set("spark.hadoop.fs.s3a.endpoint", "127.0.0.1:8333")
    .set("spark.hadoop.fs.s3a.access.key", "****************")
    .set("spark.hadoop.fs.s3a.secret.key", "********************************")
    .set("spark.hadoop.fs.s3a.path.style.access", True)
    .set("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
    .set("com.amazonaws.services.s3a.enableV4", True)
    .set("spark.hadoop.fs.s3a.connection.ssl.enabled", False)
    .set("spark.hadoop.fs.s3a.multiobjectdelete.enable", False)
    .set("spark.hadoop.fs.s3a.directory.marker.retention", "keep")
    .set("spark.hadoop.fs.s3a.change.detection.version.required", False)
    .set("spark.hadoop.fs.s3a.change.detection.mode", "warn")
)
SparkSession.builder.config(conf=conf)
spark = (
    SparkSession.builder.appName("S3 SeaweedFS Test")
    .config("spark.master", "local[*]")
    .getOrCreate()
)
sc = spark.sparkContext
log4jLogger = sc._jvm.org.apache.log4j
LOGGER = log4jLogger.LogManager.getLogger(__name__)


def main():
    LOGGER.info("Running Application...")
    LOGGER.info(
        f"Hadoop version = {sc._jvm.org.apache.hadoop.util.VersionInfo.getVersion()}"
    )
    # this works!
    kwrgs = {
        "endpoint_url": "http://localhost:8333",
        "aws_access_key_id": "****************",
        "aws_secret_access_key": "********************************",
    }
    cli = boto3.client("s3", **kwrgs)
    LOGGER.info(cli.list_buckets())

    # this doesn't work!
    LOGGER.info("Loading AVRO file...")
    df = spark.read.format("avro").load(
        "s3a://127.0.0.1:8333/opensky/states_2020-05-25-00.avro"
    )
    LOGGER.info("Finished Loading AVRO file...")
    LOGGER.info(df.dtypes)
    LOGGER.info(df.show(2))


if __name__ == "__main__":
    main()
```

Any ideas on the spark/hadoop config, would greatly appreciated.

**Comment by bsbodden** [comment]
Thanks @chrislusf I've tried every combination of spark/hadoop version so far to no avail. I'm going to just pull the files from WEBDAV for now but I will come back to it after I demo the whole thing and fix it.
