### ISSUE TITLE
mount died

### ISSUE THREAD

**Issue by zemul** [seaweedfs/seaweedfs#4056]
**Describe the bug**
Mount LevelDB metacache put data error
![image](https://user-images.githubusercontent.com/43405321/207208119-d62924c0-0c62-40e3-a11d-49bfccef7c06.png)

**System Setup**
- List the command line to start "weed mount"
  weed -logdir=/web/log/seaweed-mount mount -dirAutoCreate=true -umask=000 -dir=/var/lib/kubelet/pods/530f8770-2f51-4583-b44f-111b40ad2b40/volumes/kubernetes.io~csi/gal-pv-static-dev/mount -collection=static-dev -filer=10.17.100.28:8888,10.17.100.29:8888,10.17.100.30:8888 -filer.path=/buckets/static-dev -cacheCapacityMB=0 -replication=001 -concurrentWriters=32 -cacheDir=/export/seaweed-cache-tmp
   
- output of `weed version`
  version 30GB 3.34  linux amd64

**Additional context**

![image](https://user-images.githubusercontent.com/43405321/207208239-5340648c-cacf-4fbe-8907-a62f4e326192.png)

**Comment by zemul** [comment]
Possibly related to the goleveldb.

**Comment by zemul** [comment]
@chrislusf @kmlebedev

**Comment by chrislusf** [comment]
Is this reproducible? Does `/export/seaweed-cache-tmp` have permissions open?

**Comment by zemul** [comment]
> Is this reproducible? Does `/export/seaweed-cache-tmp` have permissions open?
reproducible, permissions open.

**Comment by zemul** [comment]
it appears occasionally.

**Comment by chrislusf** [comment]
Is this `/export/seaweed-cache-tmp` something special?

**Comment by zemul** [comment]
/export is a hard drive
[root@dev-node1 export]# df /dev/sdb
文件系统            1K-块      已用       可用 已用% 挂载点
/dev/sdb       2341899008 192541676 2149357332    9% /export

**Comment by zemul** [comment]
Find more Errors.

```
F0907 11:23:25  6451 filer_pb_tail.go:68] process directory:"/buckets/gradle-cache/cache/caches/transforms-2/files-2.1" event_notification:{old_entry:{name:"c2bf4314e640bfd987dbc78c63763f3f.bin" chunks:{file_id:"3383,44aaaf92be53acaf" size:13 mtime:1660634426182789218 e_tag:"6XRjGIwacvpkTx8k3c4cdg==" fid:{volume_id:3383 file_key:1152036754 cookie:3193154735} is_compressed:true} attributes:{file_size:13 mtime:1660634426 file_mode:420 crtime:1660634426 mime:"text/plain; charset=utf-8"}} delete_chunks:true signatures:873327020 signatures:1655448150} ts_ns:1662521005016949332: delete /buckets/gradle-cache/cache/caches/transforms-2/files-2.1/c2bf4314e640bfd987dbc78c63763f3f.bin : open /tmp/7d36abed/meta/000007.log: no such file or directory
goroutine 145 [running]:


weed.dev-node1.root.log.FATAL.20221212-170834.32660

F1212 17:08:34.041003 filer_pb_tail.go:78 process directory:"/buckets/static-dev/website/pc/cn/ff/assets/fonts" event_notification:{old_entry:{name:"Roboto-Bold.90786472.ttf" chunks:{file_id:"3550,5f69982aba9f80d8" size:33648 modified_ts_ns:1670571447781577070 e_tag:"P3il7aCAoEoLbEcu3kGKlQ==" fid:{volume_id:3550 file_key:1600755754 cookie:3131015384}} attributes:{file_size:33648 mtime:1670571447 file_mode:432 crtime:1658459771 mime:"application/x-font-ttf" md5:"?x\xa5\xed\xa0\x80\xa0J\x0blG.\xdeA\x8a\x95"}} new_entry:{name:"Roboto-Bold.90786472.ttf" chunks:{size:33648 modified_ts_ns:1670836113952321821 e_tag:"P3il7aCAoEoLbEcu3kGKlQ==" fid:{volume_id:3550 file_key:1612254535 cookie:2993640420}} attributes:{file_size:33648 mtime:1670836113 file_mode:432 crtime:1658459771 mime:"application/x-font-ttf" md5:"?x\xa5\xed\xa0\x80\xa0J\x0blG.\xdeA\x8a\x95"}} delete_chunks:true new_parent_path:"/buckets/static-dev/website/pc/cn/ff/assets/fonts" signatures:1655448150} ts_ns:1670836114026484845: persisting /buckets/static-dev/website/pc/cn/ff/assets/fonts/Roboto-Bold.90786472.ttf : open /export/seaweed-cache-tmp/c6f27662/meta/000002.log: no such file or directory


weed.dev-node2.root.log.FATAL.20221125-151517.15348

F1125 15:15:17 15348 filer_pb_tail.go:68] process directory:"/buckets/static-dev/h5/ih/points_sales/images" event_notification:{new_entry:{name:"available-button.c1538875.png" chunks:{size:56856 mtime:1669360517111500063 e_tag:"ybbtz2HVU4vCDNeDCdELeg==" fid:{volume_id:3550 file_key:1550319014 cookie:104149067}} attributes:{file_size:56856 mtime:1669360517 file_mode:432 crtime:1669360517 mime:"image/png" md5:"ɶ\xed\xcfa\xd5S\x8b\xc2\x0c׃\t\xd1\x0bz"}} delete_chunks:true new_parent_path:"/buckets/static-dev/h5/ih/points_sales/images" signatures:1655448150} ts_ns:1669360517125340054: persisting /buckets/static-dev/h5/ih/points_sales/images/available-button.c1538875.png : open /tmp/333e5e62/meta/000004.log: no such file or directory
goroutine 163 [running]:
```

**Comment by zemul** [comment]
F0907 11:23:25  6451 filer_pb_tail.go:68] process directory:"/buckets/gradle-cache/cache/caches/transforms-2/files-2.1" event_notification:{old_entry:{name:"c2bf4314e640bfd987dbc78c63763f3f.bin" chunks:{file_id:"3383,44aaaf92be53acaf" size:13 mtime:1660634426182789218 e_tag:"6XRjGIwacvpkTx8k3c4cdg==" fid:{volume_id:3383 file_key:1152036754 cookie:3193154735} is_compressed:true} attributes:{file_size:13 mtime:1660634426 file_mode:420 crtime:1660634426 mime:"text/plain; charset=utf-8"}} delete_chunks:true signatures:873327020 signatures:1655448150} ts_ns:1662521005016949332: delete /buckets/gradle-cache/cache/caches/transforms-2/files-2.1/c2bf4314e640bfd987dbc78c63763f3f.bin : open /tmp/7d36abed/meta/000007.log: no such file or directory
goroutine 145 [running]:


weed.dev-node1.root.log.FATAL.20221212-170834.32660

F1212 17:08:34.041003 filer_pb_tail.go:78 process directory:"/buckets/static-dev/website/pc/cn/ff/assets/fonts" event_notification:{old_entry:{name:"Roboto-Bold.90786472.ttf" chunks:{file_id:"3550,5f69982aba9f80d8" size:33648 modified_ts_ns:1670571447781577070 e_tag:"P3il7aCAoEoLbEcu3kGKlQ==" fid:{volume_id:3550 file_key:1600755754 cookie:3131015384}} attributes:{file_size:33648 mtime:1670571447 file_mode:432 crtime:1658459771 mime:"application/x-font-ttf" md5:"?x\xa5\xed\xa0\x80\xa0J\x0blG.\xdeA\x8a\x95"}} new_entry:{name:"Roboto-Bold.90786472.ttf" chunks:{size:33648 modified_ts_ns:1670836113952321821 e_tag:"P3il7aCAoEoLbEcu3kGKlQ==" fid:{volume_id:3550 file_key:1612254535 cookie:2993640420}} attributes:{file_size:33648 mtime:1670836113 file_mode:432 crtime:1658459771 mime:"application/x-font-ttf" md5:"?x\xa5\xed\xa0\x80\xa0J\x0blG.\xdeA\x8a\x95"}} delete_chunks:true new_parent_path:"/buckets/static-dev/website/pc/cn/ff/assets/fonts" signatures:1655448150} ts_ns:1670836114026484845: persisting /buckets/static-dev/website/pc/cn/ff/assets/fonts/Roboto-Bold.90786472.ttf : open /export/seaweed-cache-tmp/c6f27662/meta/000002.log: no such file or directory


weed.dev-node2.root.log.FATAL.20221125-151517.15348

F1125 15:15:17 15348 filer_pb_tail.go:68] process directory:"/buckets/static-dev/h5/ih/points_sales/images" event_notification:{new_entry:{name:"available-button.c1538875.png" chunks:{size:56856 mtime:1669360517111500063 e_tag:"ybbtz2HVU4vCDNeDCdELeg==" fid:{volume_id:3550 file_key:1550319014 cookie:104149067}} attributes:{file_size:56856 mtime:1669360517 file_mode:432 crtime:1669360517 mime:"image/png" md5:"ɶ\xed\xcfa\xd5S\x8b\xc2\x0c׃\t\xd1\x0bz"}} delete_chunks:true new_parent_path:"/buckets/static-dev/h5/ih/points_sales/images" signatures:1655448150} ts_ns:1669360517125340054: persisting /buckets/static-dev/h5/ih/points_sales/images/available-button.c1538875.png : open /tmp/333e5e62/meta/000004.log: no such file or directory
goroutine 163 [running]:

**Comment by chrislusf** [comment]
Try it on different hardware.

**Comment by chrislusf** [comment]
which underlying file system is it?

**Comment by zemul** [comment]
> which underlying file system is it?

ext4

**Comment by guol-fnst** [comment]
Please create a docker file to reproduce this issue.

**Comment by zemul** [comment]
> Please create a docker file to reproduce this issue.

Sorry, this issue is accidental, I can't reproduce it with dockfile.
