### ISSUE TITLE
seaweedfs container crashing

### ISSUE THREAD

**Issue by Sudhir-Harikant** [seaweedfs/seaweedfs#4317]
**Describe the bug**
Seaweedsfs K8s POD logs show the below error and repeatedly crashing. The POD was up and working fine and recently was in a terminated state, while K8s was unable to bring up a new POD as it was repeatedly crashing.

I0316 13:11:46.487625 master.go:268 current: 192.168.10.10:9333 peers:
I0316 13:11:46.555070 file_util.go:23 Folder /data/store1 Permission: -rwxr-xr-x
I0316 13:11:46.555263 master.go:268 current: 192.168.10.10:9333 peers:192.168.10.10:9333
I0316 13:11:46.555264 file_util.go:23 Folder /data/store1 Permission: -rwxr-xr-x
I0316 13:11:46.555429 master_server.go:127 Volume Size Limit is 30000 MB
I0316 13:11:46.555808 master.go:149 Start Seaweed Master 30GB 3.43 673214574 at 192.168.10.10:9333
I0316 13:11:46.558281 raft_server.go:119 Starting RaftServer with 192.168.10.10:9333
I0316 13:11:46.558790 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:11:46.687449 raft_server.go:168 current cluster leader:
I0316 13:11:48.350425 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:11:48.556484 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:49.557531 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:50.141583 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:11:50.558666 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:51.560387 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:51.933040 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:11:52.561638 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:53.562483 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:53.723858 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:11:54.563136 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:55.515519 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:11:55.563945 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:56.565410 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:57.306594 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:11:57.566608 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:58.568196 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:11:59.097521 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:11:59.569348 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:12:00.570857 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:12:00.888891 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:12:01.572144 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:12:02.573810 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:12:02.679850 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:12:03.574399 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:12:04.471459 volume_grpc_client_to_master.go:43 checkWithMaster 192.168.10.10:9333: get master 192.168.10.10:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.10.10:19333: connect: connection refused"
I0316 13:12:04.576196 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:12:04.689286 master_server.go:215 [192.168.10.10:9333]  - is the leader.
W0316 13:12:04.689713 tls.go:39 pemfile.NewProvider({   5h0m0s}) grpc.master failed: pemfile: at least one credential file needs to be specified
I0316 13:12:04.815564 master.go:200 Start Seaweed Master 30GB 3.43 673214574 grpc server at 192.168.10.10:19333
I0316 13:12:05.577973 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:12:06.315984 masterclient.go:155 No existing leader found!
I0316 13:12:06.316035 raft_server.go:190 Initializing new cluster
I0316 13:12:06.316104 master_server.go:174 leader change event:  => 192.168.10.10:9333
I0316 13:12:06.316118 master_server.go:177 [192.168.10.10:9333] 192.168.10.10:9333 becomes leader.
I0316 13:12:06.579545 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
I0316 13:12:07.581096 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
W0316 13:12:08.563280 filer_server.go:142 skipping default store dir in /data/store1/filerldb2
I0316 13:12:08.563666 leveldb2_store.go:42 filer store leveldb2 dir: /data/filerldb2
I0316 13:12:08.563684 file_util.go:23 Folder /data/filerldb2 Permission: -rwxr-xr-x
I0316 13:12:08.564056 master_grpc_server.go:349 + client .filer@192.168.10.10:8888
E0316 13:12:08.576145 leveldb2_store.go:62 filer store open dir /data/filerldb2/00: resource temporarily unavailable
I0316 13:12:08.582343 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
F0316 13:12:08.662698 configuration.go:25 failed to initialize store for leveldb2: resource temporarily unavailable
goroutine 135 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
        /go/src/github.com/seaweedfs/seaweedfs/weed/glog/glog.go:768 +0x89
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3bde300, 0x3, 0xc0002300e0, {0x2f3f5f8?, 0xc0004fb9b8?}, 0x2?, 0x0)
        /go/src/github.com/seaweedfs/seaweedfs/weed/glog/glog.go:719 +0x3aa
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0x23c3bb1?, 0x8?, {0x24192bd, 0x26}, {0xc0004fb9b8, 0x2, 0x2})
        /go/src/github.com/seaweedfs/seaweedfs/weed/glog/glog.go:657 +0x10f
github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
        /go/src/github.com/seaweedfs/seaweedfs/weed/glog/glog.go:1154
github.com/seaweedfs/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc00047a500, 0x3bd87d0)
        /go/src/github.com/seaweedfs/seaweedfs/weed/filer/configuration.go:25 +0x2fb
github.com/seaweedfs/seaweedfs/weed/server.NewFilerServer(0xc0001be140, 0xc0001be140, 0xc0001b29c0)
        /go/src/github.com/seaweedfs/seaweedfs/weed/server/filer_server.go:152 +0x97f
github.com/seaweedfs/seaweedfs/weed/command.(*FilerOptions).startFiler(0x3bde7e0)
        /go/src/github.com/seaweedfs/seaweedfs/weed/command/filer.go:228 +0x351
github.com/seaweedfs/seaweedfs/weed/command.runServer.func1()
        /go/src/github.com/seaweedfs/seaweedfs/weed/command/server.go:258 +0x2a
created by github.com/seaweedfs/seaweedfs/weed/command.runServer
        /go/src/github.com/seaweedfs/seaweedfs/weed/command/server.go:256 +0xd94

**System Setup**
- Seaweedfs POD is running in AIO
- Command : ["-logdir", "/data/logs", "server", "-dir", "/data/store1", "-volume.max=200", "-s3", "-s3.config", "/data/config/config.json"]

**Comment by washcycle** [comment]
Can you provide a few more details like verion of k8s, version of seaweedfs, how it was deployed?

What pod are you launching, master, volume, filer, s3?

Might help to share your deployment yaml or helm config.

This is the only interesting thing I see:

```
E0316 13:12:08.576145 leveldb2_store.go:62 filer store open dir /data/filerldb2/00: resource temporarily unavailable
I0316 13:12:08.582343 s3.go:177 wait to connect to filer 192.168.10.10:8888 grpc address 192.168.10.10:18888
F0316 13:12:08.662698 configuration.go:25 failed to initialize store for leveldb2: resource temporarily unavailable
goroutine 135 [running]:
```

Could be an issue with whatever you are using to host the `/data/` files.
