### ISSUE TITLE
needle_read.go: entry not found1

### ISSUE THREAD

**Issue by roflmao** [seaweedfs/seaweedfs#4338]
**Describe the bug**
Trying to read a file uploaded many seaweedversions ago.

```
Mar 27 10:54:43 photos-103 weed[35056]: E0327 10:54:43.231902 needle_read.go:45 /mnt/data01/data/photo-small-prod-002_281.dat read 0 dataSize 9368 offset 42386175760 fileSize 36832451144: EOF
Mar 27 10:54:43 photos-103 weed[35056]: E0327 10:54:43.830938 needle_read.go:58 entry not found1: offset 8026437392 found id 38653364373234383138303964333937 size 1665017002, expected size 9332
```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
/usr/local/bin/weed -logtostderr -v=1 master -mdir=/mnt/data01/meta -ip=10.1.21.26 -defaultReplication=000 -volumeSizeLimitMB 30000 -garbageThreshold 0.01 -peers=10.1.21.26:9333,10.1.21.27:9333,10.1.21.28:9333
/usr/local/bin/weed -logtostderr -v=1 volume -pprof -concurrentUploadLimitMB 99999 -concurrentDownloadLimitMB 99999 -compactionMBps=50 -port=8080 -mserver=10.1.21.26:9333,10.1.21.27:9333,10.1.21.28:9333 -dir=/mnt/data01/data -index leveldb -max 0 -ip 10.1.21.26 -rack photos-103 -dataCenter v13
```
- OS version: Ubuntu 20.04
- output of `weed version`  version 30GB 3.44  linux amd64
- if using filer, show the content of `filer.toml`: N/A

**Expected behavior**
File to be read. This file were uploaded some years ago on a older seaweed version. From logs i can see at least 1.80, 2.92 and 3.27. Seems like a bug that has evolved over different versions that has broken the index and/or dat file?

If i remove the idx/ldb/vif and restart the weed server it doesnt detect the volume and the logs says: 
```
Mar 27 10:46:16 photos-103 weed[28454]: I0327 10:46:16.266529 volume_server_handlers_read.go:65 lookup error: <nil> /281,293cace902376b88
Mar 27 10:46:17 photos-103 weed[28454]: I0327 10:46:17.075796 volume_server_handlers_read.go:65 lookup error: <nil> /281,293cace902376b88

**Comment by chrislusf** [comment]
not sure. try to use `weed fix` to re-generate the .idx file.

**Comment by roflmao** [comment]
```weed fix```does not give any output and the idx is not recreated:
```
$ weed fix -volumeId 281
$ echo $?
0
$ ls -lah photo-small-prod-002_281.*
-rw-r--r-- 1 root root 35G Feb 27 00:22 photo-small-prod-002_281.dat
```
The logs does not contain anything either (level 1)

**Comment by chrislusf** [comment]
see `weed fix -h`. 

need to specify collection name.

**Comment by roflmao** [comment]
```weed fix -h``` says its optional, and still doesnt make any change:
```
$ weed fix -volumeId=281 -collection=photo-small-prod-002
$
$ echo $?
0

**Comment by chrislusf** [comment]
need to specify the folder.

```
Example: weed fix [-volumeId=234] [-collection=bigData] /tmp
Default Usage:
  -collection string
    	an optional volume collection name, if specified only it will be processed
  -ignoreError
    	an optional, if true will be processed despite errors
  -options string
    	a file of command line options, each line in optionName=optionValue format
  -volumeId int
    	an optional volume id, if not 0 (default) only it will be processed
Description:
  Fix runs the SeaweedFS fix command on dat files or whole folders to re-create the index .idx file.
```

**Comment by roflmao** [comment]
Right, my bad
```
$ weed fix -volumeId=281 -collection=photo-small-prod-002 .
I0327 21:56:54.126197 volume_loading.go:91 readSuperBlock volume 281 version 3
F0327 21:56:54.147758 fix.go:134 scan .dat File: cannot read needle header at offset -2555888: readat photo-small-prod-002_281.dat: negative offset
goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:768 +0x8a
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3c28040, 0x3, 0xc00017a380, {0x2fc87b8?, 0x1?}, 0xc000c9fcf8?, 0x0)
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:719 +0x3ab
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printDepth(0x23ed060?, 0x12?, 0xc000c9fcf8?, {0xc000c9fcc8, 0x1, 0x1})
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:648 +0xee
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).print(...)
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:639
github.com/seaweedfs/seaweedfs/weed/glog.Fatal(...)
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:1134
github.com/seaweedfs/seaweedfs/weed/command.doFixOneVolume({0x7ffe370c65a0, 0x1}, {0xc000669020?, 0x40?}, {0xc000669020, 0x14}, 0x119)
        /builds/deb/seaweed-build/seaweedfs/weed/command/fix.go:134 +0x26e
github.com/seaweedfs/seaweedfs/weed/command.runFix(0x3c0a178?, {0xc0001aa040?, 0x1, 0x3?})
        /builds/deb/seaweed-build/seaweedfs/weed/command/fix.go:111 +0x4f7
main.main()
        /builds/deb/seaweed-build/seaweedfs/weed/weed.go:82 +0x3a3

**Comment by chrislusf** [comment]
what is the output of `weed -v=4 fix ...`?

**Comment by roflmao** [comment]
```
$ weed -v=4 fix -volumeId=281 -collection=photo-small-prod-002 .
I0328 07:24:40.306228 volume_info.go:20 maybeLoadVolumeInfo checks photo-small-prod-002_281.vif
I0328 07:24:40.323136 volume_info.go:36 maybeLoadVolumeInfo reads photo-small-prod-002_281.vif
I0328 07:24:40.323185 volume_info.go:45 maybeLoadVolumeInfo Unmarshal volume info photo-small-prod-002_281.vif
I0328 07:24:40.323824 volume_loading.go:91 readSuperBlock volume 281 version 3
I0328 07:24:40.323874 fix.go:52 key 98208722213162 offset 8 size -2555936 disk_size -2555896 compressed false
I0328 07:24:40.323888 fix.go:57 skipping deleted file ...
I0328 07:24:40.323921 volume_read.go:259 ==> new entry offset -2555888
F0328 07:24:40.325606 fix.go:134 scan .dat File: cannot read needle header at offset -2555888: readat photo-small-prod-002_281.dat: negative offset
goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:768 +0x8a
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3c28040, 0x3, 0xc000cf6000, {0x2fc87b8?, 0x1?}, 0xc000ebfcf8?, 0x0)
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:719 +0x3ab
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printDepth(0x23ed060?, 0x12?, 0xc000ebfcf8?, {0xc000ebfcc8, 0x1, 0x1})
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:648 +0xee
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).print(...)
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:639
github.com/seaweedfs/seaweedfs/weed/glog.Fatal(...)
        /builds/deb/seaweed-build/seaweedfs/weed/glog/glog.go:1134
github.com/seaweedfs/seaweedfs/weed/command.doFixOneVolume({0x7ffe090ab5a0, 0x1}, {0xc000de8780?, 0x40?}, {0xc000de8780, 0x14}, 0x119)
        /builds/deb/seaweed-build/seaweedfs/weed/command/fix.go:134 +0x26e
github.com/seaweedfs/seaweedfs/weed/command.runFix(0x3c0a178?, {0xc00004e230?, 0x1, 0x3?})
        /builds/deb/seaweed-build/seaweedfs/weed/command/fix.go:111 +0x4f7
main.main()
        /builds/deb/seaweed-build/seaweedfs/weed/weed.go:82 +0x3a3

**Comment by VictorSFF** [comment]
This case is possibly caused by a garbage collection issue, which has been repaired in 3.3x. Before this version, both the .dat and .idx may be corrupted after GC. So it is possible that the .idx cannot be regenerated from .dat file.

**Comment by roflmao** [comment]
@VictorSFF Wow, thats not assuring, do you have any more data? Are the dat files really corrupted and not able to be fixed?

**Comment by VictorSFF** [comment]
I‘m not sure about your condition. In my test environment, most volumes can be fixed by "weed fix", however, some volumes cannot be fixed.

**Comment by roflmao** [comment]
@chrislusf Do you have any data on this and/or suggestions on how to resolve the broken volume/index?

**Comment by kmlebedev** [comment]
It's very bold to use 000 replication without rsync backing up dat files at least once a week. Because there are a million options to corrupt the dat' file. Trite may come OOM or power off. In general, you should be ready for this.

**Comment by roflmao** [comment]
@kmlebedev The GC generates a new file and then moves it into place when finished doesnt it?

**Comment by tadwiew** [comment]
I am also having a number of "damaged" volumes . All created with really old versions of weed, Was also looking at ways to fix them/recover usable Needles, It seems that there is no ready utility to do it.... As it seems that idx files are OK so I am thinking about retrieving Needles via pointers in idx and  writing good ones  a new file ... Not a Go programmer  ...
In that context I am wondering why seaweedfs has not included in Needle special fields used in original FB Haystack design - ie. Header/Footer Magic Numbers. According to FB article about Haystack they are "for recovery". No more details - but I guess one can "scan" volume file sequentially and find where each Needle Starts/Ends ...
