### ISSUE TITLE
mount deadlock

### ISSUE THREAD

**Issue by neo-v** [seaweedfs/seaweedfs#4346]
**Describe the bug**
Mount may hung by deadlock.
Here is the reason:

![image](https://user-images.githubusercontent.com/10511493/228212087-537e4243-f464-42dc-af6c-bc9c3e3e04b1.png)

stacks:
```
goroutine 1248229 [semacquire, 12 minutes]:
sync.runtime_SemacquireMutex(0xc0000ff418?, 0x60?, 0xc0004261d0?)
        /usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000a7cc98)
        /usr/local/go/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc000a7cc98)
        /usr/local/go/src/sync/mutex.go:81 +0x65
github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).AddChunks(0xc000a7cc80, {0xc00797bb90, 0x1, 0x1})
        /home/weed_source/seaweedfs/weed/mount/filehandle.go:95 +0x6b
github.com/seaweedfs/seaweedfs/weed/mount.(*ChunkedDirtyPages).saveChunkedFileIntervalToStorage(0xc0022d82a0, {0x495d780, 0xc00687c8a0}, 0x40000, 0x20000, 0xc00687c8a0?, 0x34a4bc0)
        /home/weed_source/seaweedfs/weed/mount/dirty_pages_chunked.go:79 +0x3b7
github.com/seaweedfs/seaweedfs/weed/mount/page_writer.(*MemChunk).SaveContent(0xc001521270, 0xc003eb9310)
        /home/weed_source/seaweedfs/weed/mount/page_writer/page_chunk_mem.go:105 +0x246
github.com/seaweedfs/seaweedfs/weed/mount/page_writer.(*UploadPipeline).moveToSealed.func1()
        /home/weed_source/seaweedfs/weed/mount/page_writer/upload_pipeline.go:184 +0xaa
github.com/seaweedfs/seaweedfs/weed/util.(*LimitedConcurrentExecutor).Execute.func1()
        /home/weed_source/seaweedfs/weed/util/limited_executor.go:38 +0x9f
created by github.com/seaweedfs/seaweedfs/weed/util.(*LimitedConcurrentExecutor).Execute
        /home/weed_source/seaweedfs/weed/util/limited_executor.go:33 +0x11b


goroutine 1237707 [semacquire, 12 minutes]:
sync.runtime_SemacquireMutex(0x7f35279bce58?, 0x99?, 0x4a4e77?)
        /usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0085b6eb8)
        /usr/local/go/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc0085b6eb8)
        /usr/local/go/src/sync/mutex.go:81 +0x65
github.com/seaweedfs/seaweedfs/weed/mount/page_writer.(*UploadPipeline).Shutdown(0xc0085b6e70)
        /home/weed_source/seaweedfs/weed/mount/page_writer/upload_pipeline.go:214 +0x7e
github.com/seaweedfs/seaweedfs/weed/mount.ChunkedDirtyPages.Destroy(...)
        /home/weed_source/seaweedfs/weed/mount/dirty_pages_chunked.go:86
github.com/seaweedfs/seaweedfs/weed/mount.(*PageWriter).Destroy(...)
        /home/weed_source/seaweedfs/weed/mount/page_writer.go:78
github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).ReleaseHandle(0xc000a7cc80)
        /home/weed_source/seaweedfs/weed/mount/filehandle.go:109 +0xbd
github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandleToInode).ReleaseByInode(0xc0003833b0, 0xc00a805cd7?)
        /home/weed_source/seaweedfs/weed/mount/filehandle_map.go:68 +0x1e5
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).Forget(0xc000426140, 0x10?, 0xb160?)
        /home/weed_source/seaweedfs/weed/mount/weedfs_forget.go:68 +0xa5
github.com/hanwen/go-fuse/v2/fuse.doBatchForget(0xc000880580, 0xc00210ed80)
        /home/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/opcode.go:332 +0x497
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000880580, 0xc00210ed80)
        /home/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:514 +0x556
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000880580, 0xc9?)
        /home/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:487 +0x1e5
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
```

**System Setup**
mount normal.
version:3.43

**Expected behavior**
mount run normally.

**Screenshots**

**Additional context**

**Comment by neo-v** [comment]
Can we take off fh.entryLock.Lock() in ReleaseHandle？
