### ISSUE TITLE
Caused by: org.apache.hadoop.yarn.exceptions.YarnException: Download and unpack failed

### ISSUE THREAD

**Issue by renweijun** [seaweedfs/seaweedfs#4403]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
When I run a test case and report the following error, it must be present

**System Setup**
- master :nohup /data/app/seaweedfs/weed -v=4 master -ip=1.x.x.x -mdir=/data/seaweedfs_master_data -port=9333 -metrics.address=10.x.x.x:9292 -defaultReplication=001 >master.log &
- volume :nohup /data/app/seaweedfs/weed -v=2 volume -disk= -max=60 -dir=/data/seaweedfs-data/9223 -mserver=1.x.x.x:9333 -dataCenter=jh -compactionMBps=200 -port=9223 -port.public=9223 -rack=E-11  >volume.log &
- filer s3.:nohup /data/app/seaweedfs/weed -v=4 filer -s3 -s3.config=/data/app/seaweedfs/cfg/s3config.json -s3.port=8333 -port=8888 -master=1.x.x.x:9333 >filer.log &
- OS version
> Ubuntu 18.04.3 LTS
- output of `weed version`
>version 8000GB 3.43 3227e4175e2bf8df2ac8aeeff8cf73a819abc5a7 linux amd64
>java version "1.8.0_202"
> hadoop version :hadoop-3.3.4
> seaweedfs-hadoop3-client-3.33.jar in share/hadoop/common/lib
- if using filer, show the content of `filer.toml`
- `
>[leveldb3]
>enabled = true 
>dir = "./filerldb3"  `

Other filer store   redis_ cluster3 tikv are the same 

**Expected behavior**
Initially OK, repeat several times for more than 6 hours, and an error will be reported
>echo "mkdir input" |/data/app/seaweedfs/weed shell   
>./bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-examples-3.3.4.jar wordcount input output
>echo "rm -rf output" |/data/app/seaweedfs/weed shell 
    
Return Error

Job job_1681018607274_0016 failed with state FAILED due to: Application application_1681018607274_0016 failed 2 times (global limit =5; local limit is =2) due to AM Container for appattempt_1681018607274_0016_000002 exited with  exitCode: -1000
Failing this attempt.Diagnostics: [2023-04-11 10:18:20.308]
java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInfoation.doAs(UserGroupInformation.java:1894)
	at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:412)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.doDownloadCall(ContainerLocalizer.java:247)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:240)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.yarn.exceptions.YarnException: Download and unpack failed
	at org.apache.hadoop.yarn.util.FSDownload.downloadAndUnpack(FSDownload.java:311)
	at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:288)
	at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:68)
	at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:415)
	at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:412)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	... 10 more
Caused by: java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkBounds(Buffer.java:567)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:187)
	at seaweedfs.client.SeaweedRead.readChunkView(SeaweedRead.java:109)
	at seaweedfs.client.SeaweedRead.read(SeaweedRead.java:75)
	at seaweedfs.client.SeaweedInputStream.read(SeaweedInputStream.java:125)
	at seaweedfs.client.SeaweedInputStream.read(SeaweedInputStream.java:106)
	at seaweed.hdfs.SeaweedHadoopInputStream.read(SeaweedHadoopInputStream.java:37)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:102)
	at org.apache.commons.io.input.TeeInputStream.read(TeeInputStream.java:129)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.PushbackInputStream.read(PushbackInputStream.java:186)
	at java.util.zip.ZipInputStream.readFully(ZipInputStream.java:403)
	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:278)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:83)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:62)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:118)
	at org.apache.hadoop.util.RunJar.unJarAndSave(RunJar.java:171)
	at org.apache.hadoop.yarn.util.FSDownload.unpack(FSDownload.java:359)
	at org.apache.hadoop.yarn.util.FSDownload.downloadAndUnpack(FSDownload.java:308)
	... 17 more

[hadoop-client-test.err.txt](https://github.com/seaweedfs/seaweedfs/files/11240906/hadoop-client-test.err.txt)

**Comment by chrislusf** [comment]
Could you please turn on the debugging on https://github.com/seaweedfs/seaweedfs/blob/master/other/java/client/src/main/java/seaweedfs/client/SeaweedRead.java#L107 ?

**Comment by renweijun** [comment]
visibleIntervalList:[VisibleInterval{start=0, stop=280990, modifiedTime=1681807803941000, fileId='8,8c00a93552b', isFullChunk=false, cipherKey=[], isCompressed=false}]
2023-04-18 16:50:05,017 DEBUG seaweedfs.client.SeaweedRead: doFetchOneFullChunkData url:http://1.2.2.2:9250/8,8c00a93552b chunkData.length:0
2023-04-18 16:50:05,017 DEBUG seaweedfs.client.SeaweedRead: doFetchFullChunkData fid:8,8c00a93552b chunkData.length:0
2023-04-18 16:50:05,017 DEBUG seaweedfs.client.SeaweedRead: readChunkView fid:8,8c00a93552b chunkData.length:0 chunkView.offset:0 chunkView[0;280990) startOffset:0

**Comment by renweijun** [comment]
http://1.2.2.2:9250/8,8c00a93552b  volume  log :
volume_server_handlers_read.go:148 read /8,8c00a93552b isNormalVolume true error: already deleted
volume_server_handlers_read.go:148 read /8,8c00a93552b isNormalVolume true error: already deleted

**Comment by renweijun** [comment]
@chrislusf  NeedleValue Size -281002?
volume_read.go:28 Key:8c0,Offset:153378,readSize: -281002
volume_read.go:28 Key:8c0,Offset:153378,readSize: -281002

**Comment by chrislusf** [comment]
Deleted needle.

**Comment by blackflash997997** [comment]
use hadoop config and run TestDFSIO on yarn:

hadoop jar hadoop-mapreduce-client-jobclient-3.4.2-tests.jar  TestDFSIO -Dmapreduce.job.queuename=root.default -Dmapreduce.framework.name=yarn -write -nrFiles 10 -fileSize 100MB -bufferSize 8388608  -resFile /tmp/Test0128.log

i got this exception too,


but i run TestDFSIO in local without -Dmapreduce.framework.name=yarn , all is normal

> Deleted needle.

**Comment by chrislusf** [comment]
@blackflash997997 Is this running on fuse mounted directory or using the seaweedfs hadoop jar?
