### ISSUE TITLE
The master node has been unsuccessful in electing the master node.

### ISSUE THREAD

**Issue by shichanglin5** [seaweedfs/seaweedfs#4435]
**Describe the bug**

The log file is displayed as follows
```log
{"log":"I0429 01:45:18.641377 raft_server.go:57 Save raft state {MaxVolumeId:127829}\n","stream":"stderr","time":"2023-04-28T17:45:18.641493926Z"
}
{"log":"I0429 01:45:18.642180 cluster_commands.go:32 max volume id 127829 ==\u003e 127830\n","stream":"stderr","time":"2023-04-28T17:45:18.642249801Z"}
{"log":"I0429 01:45:18.643640 raft_server.go:57 Save raft state {MaxVolumeId:127830}\n","stream":"stderr","time":"2023-04-28T17:45:18.643740126Z"}
{"log":"panic: runtime error: slice bounds out of range [18446744073709551615:200]\n","stream":"stderr","time":"2023-04-28T17:45:18.650753596Z"}
{"log":"\n","stream":"stderr","time":"2023-04-28T17:45:18.650768464Z"}
{"log":"goroutine 85389197 [running]:\n","stream":"stderr","time":"2023-04-28T17:45:18.650771013Z"}
{"log":"github.com/seaweedfs/raft.(*Log).compact(0xc000945ea0, 0x1f27d, 0x3)\n","stream":"stderr","time":"2023-04-28T17:45:18.651531757Z"}
{"log":"\u0009/root/go/pkg/mod/github.com/seaweedfs/raft@v1.1.0/log.go:592 +0x4b4\n","stream":"stderr","time":"2023-04-28T17:45:18.651542699Z"}
{"log":"github.com/seaweedfs/raft.(*server).TakeSnapshot(0xc0001870e0)\n","stream":"stderr","time":"2023-04-28T17:45:18.651547296Z"}
{"log":"\u0009/root/go/pkg/mod/github.com/seaweedfs/raft@v1.1.0/server.go:1281 +0x5b6\n","stream":"stderr","time":"2023-04-28T17:45:18.651551533Z"}
{"log":"github.com/seaweedfs/raft.(*server).maybeTakeSnapshot.func1()\n","stream":"stderr","time":"2023-04-28T17:45:18.651560125Z"}
{"log":"\u0009/root/go/pkg/mod/github.com/seaweedfs/raft@v1.1.0/server.go:1221 +0x66\n","stream":"stderr","time":"2023-04-28T17:45:18.651563344Z"}
{"log":"created by github.com/seaweedfs/raft.(*server).maybeTakeSnapshot\n","stream":"stderr","time":"2023-04-28T17:45:18.651565963Z"}
{"log":"\u0009/root/go/pkg/mod/github.com/seaweedfs/raft@v1.1.0/server.go:1219 +0x96\n","stream":"stderr","time":"2023-04-28T17:45:18.651568326Z"}
{"log":"\n","stream":"stdout","time":"2023-04-28T17:45:19.21349202Z"}
{"log":"172.26.199.25\n","stream":"stdout","time":"2023-04-28T17:45:19.213537596Z"}
```

version: 3.43

**Comment by shichanglin5** [comment]
log context
```log
{"log":"I0429 01:45:18.512480 volume_growth.go:244 Created Volume 127829 on topo:hd1:rack1:172.26.199.25:34355\n","stream":"stderr","time":"2023-04-28T17:45:18.512530391Z"}
{"log":"I0429 01:45:18.512633 volume_layout.go:223 volume 127829 does not have enough copies\n","stream":"stderr","time":"2023-04-28T17:45:18.512688785Z"}
{"log":"I0429 01:45:18.512649 volume_layout.go:228 volume 127829 remove from writable\n","stream":"stderr","time":"2023-04-28T17:45:18.51269624Z"}
{"log":"I0429 01:45:18.512825 masterclient.go:292 updateVidMap(hd1) .master: 172.26.199.25:34355 volume add: 1, del: 0, add ec: 0 del ec: 0\n","stream":"stderr","time":"2023-04-28T17:45:18.512866995Z"}
{"log":"I0429 01:45:18.636324 volume_layout.go:393 Volume 127829 becomes writable\n","stream":"stderr","time":"2023-04-28T17:45:18.636469509Z"}
{"log":"I0429 01:45:18.636357 volume_growth.go:244 Created Volume 127829 on topo:hd2:rack1:172.28.11.11:34449\n","stream":"stderr","time":"2023-04-28T17:45:18.636503194Z"}
{"log":"I0429 01:45:18.636396 volume_growth.go:257 Registered Volume 127829 on topo:hd1:rack1:172.26.199.25:34355\n","stream":"stderr","time":"2023-04-28T17:45:18.636507131Z"}
{"log":"I0429 01:45:18.636408 volume_growth.go:257 Registered Volume 127829 on topo:hd2:rack1:172.28.11.11:34449\n","stream":"stderr","time":"2023-04-28T17:45:18.636510668Z"}
{"log":"I0429 01:45:18.639054 masterclient.go:292 updateVidMap(hd2) .master: 172.28.11.11:34449 volume add: 1, del: 0, add ec: 0 del ec: 0\n","stream":"stderr","time":"2023-04-28T17:45:18.639187125Z"}
{"log":"I0429 01:45:18.641377 raft_server.go:57 Save raft state {MaxVolumeId:127829}\n","stream":"stderr","time":"2023-04-28T17:45:18.641493926Z"}
23-04-28T17:45:18.636507131Z"}
{"log":"I0429 01:45:18.636408 volume_growth.go:257 Registered Volume 127829 on topo:hd2:rack1:172.28.11.11:34449\n","stream":"stderr","time":"202
3-04-28T17:45:18.636510668Z"}
{"log":"I0429 01:45:18.639054 masterclient.go:292 updateVidMap(hd2) .master: 172.28.11.11:34449 volume add: 1, del: 0, add ec: 0 del ec: 0\n","st
ream":"stderr","time":"2023-04-28T17:45:18.639187125Z"}
{"log":"I0429 01:45:18.641377 raft_server.go:57 Save raft state {MaxVolumeId:127829}\n","stream":"stderr","time":"2023-04-28T17:45:18.641493926Z"
}
{"log":"I0429 01:45:18.642180 cluster_commands.go:32 max volume id 127829 ==\u003e 127830\n","stream":"stderr","time":"2023-04-28T17:45:18.642249801Z"}
{"log":"I0429 01:45:18.643640 raft_server.go:57 Save raft state {MaxVolumeId:127830}
```

**Comment by shichanglin5** [comment]
The reason for this problem is caused by concurrent execution of' maybeTakeSnapshot' (two green labels in two loops start a goroutine call' maybeTakeSnapshot' respectively)
<img width="616" alt="image" src="https://user-images.githubusercontent.com/48707349/235306054-13281e46-8d71-4fa7-9f93-0cf2bf80ae00.png">

Since 'maybeTakeSnapshot' starts a goroutine to execute 'TakeSnapshot', but 'TakeSnapshot' is not locked, the following code uses the 's. log.startIndex' thread to be unsafe.
```go
	// We keep some log entries after the snapshot.
	// We do not want to send the whole snapshot to the slightly slow machines
	if lastIndex > NumberOfLogEntriesAfterSnapshot && lastIndex-s.log.startIndex > NumberOfLogEntriesAfterSnapshot {
		compactIndex := lastIndex - NumberOfLogEntriesAfterSnapshot
		entry := s.log.getEntry(compactIndex)
		if entry != nil && entry.pb != nil {
			compactTerm := entry.Term()
			s.log.compact(compactIndex, compactTerm)
		}
	}
```
As a result, the `compactIndex` value passed in when executing the 'compact' method may be smaller than the latest `s.log.startIndex` value (because the s.log.startIndex has been updated to a larger value by another goroutine), so directly using the' index-l.startIndex 'expression in the commpact to calculate the slice index may be a negative number, triggering panic
