### ISSUE TITLE
filer store by elasticV7  support https?

### ISSUE THREAD

**Issue by 13666056333** [seaweedfs/seaweedfs#4468]
W0515 17:54:48.582453 filer_server.go:142 skipping default store dir in ./filerldb2
I0515 17:54:48.584144 elastic_store.go:73 filer store elastic endpoints: [https://elasticsearch.safedog.cn:39200].
E0515 17:54:48.625164 elastic_store_kv.go:47 find key(filer.store.id),no available connection: no Elasticsearch node available.
F0515 17:54:48.641787 filer.go:124 set filer.store.id=-1227019728 : kv put: Put "https://elasticsearch.safedog.cn:39200/.seaweedfs_kv_entries/_doc/filer.store.id": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match elasticsearch.safedog.cn
goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
        /root/seaweedfs/weed/glog/glog.go:768 +0x89
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x5123b80, 0x3, 0xc000638380, {0x3fbdf05?, 0xc000ec3628?}, 0x3?, 0x0)
        /root/seaweedfs/weed/glog/glog.go:719 +0x3aa
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0xc0b6dd2a30?, 0x37bc310?, {0x30e88a0, 0xe}, {0xc000ec3628, 0x3, 0x3})
        /root/seaweedfs/weed/glog/glog.go:657 +0x10f
github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
        /root/seaweedfs/weed/glog/glog.go:1154
github.com/seaweedfs/seaweedfs/weed/filer.(*Filer).setOrLoadFilerStoreSignature(0xc00062b180, {0x37d6908, 0xc000994240})
        /root/seaweedfs/weed/filer/filer.go:124 +0x3bd
github.com/seaweedfs/seaweedfs/weed/filer.(*Filer).SetStore(0xc00062b180?, {0x37d6908?, 0xc000994240?})
        /root/seaweedfs/weed/filer/filer.go:114 +0x225
github.com/seaweedfs/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc00062b180, 0x5119d40)
        /root/seaweedfs/weed/filer/configuration.go:27 +0x318
github.com/seaweedfs/seaweedfs/weed/server.NewFilerServer(0xc000fbccc0, 0xc000fbccc0, 0xc000fd1ad0)
        /root/seaweedfs/weed/server/filer_server.go:152 +0x97f
github.com/seaweedfs/seaweedfs/weed/command.(*FilerOptions).startFiler(0x5123f60)
        /root/seaweedfs/weed/command/filer.go:227 +0x351
github.com/seaweedfs/seaweedfs/weed/command.runFiler(0x50ff638?, {0xc000134020?, 0x3?, 0x3?})
        /root/seaweedfs/weed/command/filer.go:203 +0x451
main.main()
        /root/seaweedfs/weed/weed.go:81 +0x38c

filer.toml config as follow
[elastic7]
enabled = true
servers = [
    "https://elasticsearch.xxxx.cn:39200"
]
username = "elastic"
password = "xxxx"
sniff_enabled = false
healthcheck_enabled = false
# increase the value is recommend, be sure the value in Elastic is greater or equal here
index.max_result_window = 10000

**Comment by 13666056333** [comment]
已解决，elastic生成的证书，需要配置dns相关内容，另外需要将证书加到linux的证书库路径下

**Comment by 13666056333** [comment]
已解决，elastic生成的证书，需要配置dns相关内容，另外需要将证书加到linux的证书库路径下
