### ISSUE TITLE
Nexus not working with seaweedfs and k8s ingress

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#4479]
blobstores s3 successfully added to nexus.

**Describe the bug**
But when you try to put through PUT exactly the file with the properties permission, we get the response code 400

It cannot be reproduced locally
```
make dev 
s3cmd --no-ssl  --host-bucket=127.0.0.1:8333 --host=127.0.0.1:8333  --add-header "x-amz-meta-BlobStore.temporary-blob:true" put /tmp/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties s3://test/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: '/tmp/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties' -> 's3://test/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties'  [1 of 1]
 316 of 316   100% in    0s    12.81 KB/s  done
```

log:
```
seaweedfs-s3-1      | I0517 13:42:17.004555 error_handler.go:96 status 200 : , headers: map[Accept-Encoding:[identity] Authorization:[AWS4-HMAC-SHA256 Credential=4E01751561F27CD2152F/20230517/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-blobstore.temporary-blob;x-amz-meta-s3cmd-attrs;x-amz-storage-class,Signature=186b0b9778233e73f55a87b1895ae8048100d0394ef43a2262dce5172a5b52c8] Content-Length:[316] Content-Type:[binary/octet-stream] X-Amz-Content-Sha256:[791f0612803520adaf33869579e48951ebbcb741a5a513c85a04d600d0278f26] X-Amz-Date:[20230517T134216Z] X-Amz-Meta-Blobstore.temporary-Blob:[true] X-Amz-Meta-S3cmd-Attrs:[atime:1684308365/ctime:1684327250/gid:0/gname:wheel/md5:a9949994865960a9e4efa26ff7149d9d/mode:33188/mtime:1684308365/uid:501/uname:lebedev] X-Amz-Storage-Class:[STANDARD]]
```

**System Setup**
```
seaweedfs: v3.48
nexus: v3.52.0
```

**Expected behavior**
Nexus working with seaweedfs

**Screenshots**
![Снимок экрана 2023-05-17 в 16 36 15](https://github.com/seaweedfs/seaweedfs/assets/9497591/969fd001-43cc-4c4d-99fb-5a5f944ac3ef)

**Additional context**
nexus log:
```
2023-05-17 11:15:03,483+0000 WARN  [qtp1772156792-631] *UNKNOWN org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: GET /repository/chartmuseum-devexp-s3/charts/zookeeper-3.2.3.tgz
com.amazonaws.services.s3.model.AmazonS3Exception: There were headers present in the request which were not signed (Service: Amazon S3; Status Code: 400; Error Code: AccessDenied; Request ID: 1684322103480962667; S3 Extended Request ID: null; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
```
filler log:
```
I0517 11:29:15.997452 error_handler.go:96 status 400 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><Resource>/content/vol-36/chap-13/eb3f230c-8d66-49de-b7c4-3d0e838ba01f.properties</Resource><RequestId>1684322955997376792</RequestId><Key>content/vol-36/chap-13/eb3f230c-8d66-49de-b7c4-3d0e838ba01f.properties</Key><BucketName>package-cache-nexus-proxy-cache</BucketName></Error>
```

tcpdump for 400 bad:

```
PUT /content/vol-36/chap-40/dcc7f0e9-6c08-40d4-af38-ab19d0781560.properties HTTP/1.1
Host: package-cache-nexus-proxy-cache.s3-proxy.query.consul
amz-sdk-invocation-id: 7994fd41-fdab-9ce5-f9be-4670b6ba5d3f
amz-sdk-request: attempt=1;max=4
amz-sdk-retry: 0/0/500
Authorization: AWS4-HMAC-SHA256 Credential=JNGRYLO4EEXYDZDOJZ781/20230517/DEFAULT/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-meta-blobstore.temporary-blob, Signature=ff2f216668dae3392b5c3040248105be770cc903f47c03cb16383061efa21a01
Content-Type: application/octet-stream
User-Agent: aws-sdk-java/1.12.265 Linux/5.18.5-1.el8.elrepo.x86_64 OpenJDK_64-Bit_Server_VM/25.372-b07 java/1.8.0_372 vendor/Red_Hat,_Inc. cfg/retry-mode/legacy
x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20230517T115838Z
x-amz-decoded-content-length: 239
x-amz-meta-BlobStore.temporary-blob: true
Content-Length: 412
Connection: Keep-Alive
Expect: 100-continue
```

tcpdump for 200 OK:
```
PUT /content/vol-25/chap-20/4bb3fba4-5717-4045-bdc7-a48cb99905c3.bytes HTTP/1.1
Host: package-cache-nexus-proxy-cache.s3-proxy.query.consul
amz-sdk-invocation-id: 9d4c3851-bfc6-a2f3-f182-efe583a1310e
amz-sdk-request: attempt=1;max=4
amz-sdk-retry: 0/0/500
Authorization: AWS4-HMAC-SHA256 Credential=JNGRYLO4EEXYDZDOJZ781/20230517/DEFAULT/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=d8476f4dcc879a8529b8f32c0a0534b7bb107a367c207a7b51520e7837a9bfa4
Content-Type: application/octet-stream
User-Agent: aws-sdk-java/1.12.265 Linux/5.18.5-1.el8.elrepo.x86_64 OpenJDK_64-Bit_Server_VM/25.372-b07 java/1.8.0_372 vendor/Red_Hat,_Inc. cfg/retry-mode/legacy
x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20230517T120339Z
x-amz-decoded-content-length: 11201
Content-Length: 11376
Connection: Keep-Alive
Expect: 100-continue
```

**Comment by kmlebedev** [comment]
The problem is the invalid header `x-amz-meta-BlobStore.temporary-blob` which contains a dot and this header can be cut from the nginx ingress side of the kubernetes controller. http://nginx.org/en/docs/http/ngx_http_core_module.html#ignore_invalid_headers

At the same time, this invalid head is involved in the signature, which accordingly leads to the inability to verify the signature on the s3 api side

**Comment by kmlebedev** [comment]
links https://ablog.jc-lab.net/301

**Comment by kmlebedev** [comment]
The problem is solved by setting annotations for the ingress object:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      ignore_invalid_headers off;
```

before:
```
DEBUG: Canonical Request:
PUT
/package-cache-nexus-proxy-cache/content/vol-19/chap-44/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties.ingress.rm

content-length:316
content-type:binary/octet-stream
host:s3-fast-api.query.consul-test
x-amz-content-sha256:791f0612803520adaf33869579e48951ebbcb741a5a513c85a04d600d0278f26
x-amz-date:20230518T082024Z
x-amz-meta-blobstore.temporary-blob:true
x-amz-meta-s3cmd-attrs:atime:1684308365/ctime:1684327250/gid:0/gname:wheel/md5:a9949994865960a9e4efa26ff7149d9d/mode:33188/mtime:1684308365/uid:501/uname:lebedev
x-amz-storage-class:STANDARD

content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-blobstore.temporary-blob;x-amz-meta-s3cmd-attrs;x-amz-storage-class
791f0612803520adaf33869579e48951ebbcb741a5a513c85a04d600d0278f26
----------------------
DEBUG: signature-v4 headers: {'content-length': '316', 'content-type': 'binary/octet-stream', 'x-amz-meta-blobstore.temporary-blob': 'true', 'x-amz-meta-s3cmd-attrs': 'atime:1684308365/ctime:1684327250/gid:0/gname:wheel/md5:a9949994865960a9e4efa26ff7149d9d/mode:33188/mtime:1684308365/uid:501/uname:lebedev', 'x-amz-storage-class': 'STANDARD', 'x-amz-date': '20230518T082024Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=JNGRYLO4EEXYDZDOJZ781/20230518/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-blobstore.temporary-blob;x-amz-meta-s3cmd-attrs;x-amz-storage-class,Signature=41857d4861dfb873d8da9b486fd43c91b06adacc5dab87ff92dc4d2f46375461', 'x-amz-content-sha256': '791f0612803520adaf33869579e48951ebbcb741a5a513c85a04d600d0278f26'}
DEBUG: get_hostname(package-cache-nexus-proxy-cache): s3-fast-api.query.consul-test
DEBUG: ConnMan.get(): re-using connection: https://s3-fast-api.query.consul-test#1
DEBUG: format_uri(): /package-cache-nexus-proxy-cache/content/vol-19/chap-44/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties.ingress.rm
 316 of 316   100% in    0s   147.94 KB/sDEBUG: ConnMan.put(): connection put back to pool (https://s3-fast-api.query.consul-test#2)
DEBUG: Response:
{'data': b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied'
         b'</Code><Message>There were headers present in the request which were'
         b' not signed</Message><Resource>/package-cache-nexus-proxy-cache/cont'
         b'ent/vol-19/chap-44/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties.i'
         b'ngress.rm</Resource><RequestId>1684398024580059624</RequestId><Key>c'
         b'ontent/vol-19/chap-44/12ac5e23-8815-4374-b888-6dc2e0b6268d.propertie'
         b's.ingress.rm</Key><BucketName>package-cache-nexus-proxy-cache</Bucke'
         b'tName></Error>',
 'headers': {'accept-ranges': 'bytes',
             'connection': 'keep-alive',
             'content-length': '486',
             'content-type': 'application/xml',
             'date': 'Thu, 18 May 2023 08:20:24 GMT',
             'strict-transport-security': 'max-age=15724800; includeSubDomains',
             'x-amz-request-id': '1684398024580117475'},
 'reason': 'Bad Request',
 'size': 316,
 'status': 400}
 316 of 316   100% in    0s     8.00 KB/s  done
DEBUG: S3Error: 400 (Bad Request)
DEBUG: HttpHeader: date: Thu, 18 May 2023 08:20:24 GMT
DEBUG: HttpHeader: content-type: application/xml
DEBUG: HttpHeader: content-length: 486
DEBUG: HttpHeader: connection: keep-alive
DEBUG: HttpHeader: accept-ranges: bytes
DEBUG: HttpHeader: x-amz-request-id: 1684398024580117475
DEBUG: HttpHeader: strict-transport-security: max-age=15724800; includeSubDomains
DEBUG: ErrorXML: Code: 'AccessDenied'
DEBUG: ErrorXML: Message: 'There were headers present in the request which were not signed'
DEBUG: ErrorXML: Resource: '/package-cache-nexus-proxy-cache/content/vol-19/chap-44/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties.ingress.rm'
DEBUG: ErrorXML: RequestId: '1684398024580059624'
DEBUG: ErrorXML: Key: 'content/vol-19/chap-44/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties.ingress.rm'
DEBUG: ErrorXML: BucketName: 'package-cache-nexus-proxy-cache'
ERROR: S3 error: 400 (AccessDenied): There were headers present in the request which were not signed
```


after set  ignore_invalid_headers off:
```
DEBUG: Canonical Request:
PUT
/package-cache-nexus-proxy-cache/content/vol-19/chap-44/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties.ingress.rm

content-length:316
content-type:binary/octet-stream
host:s3-fast-api.query.consul-test
x-amz-content-sha256:791f0612803520adaf33869579e48951ebbcb741a5a513c85a04d600d0278f26
x-amz-date:20230518T082224Z
x-amz-meta-blobstore.temporary-blob:true
x-amz-meta-s3cmd-attrs:atime:1684308365/ctime:1684327250/gid:0/gname:wheel/md5:a9949994865960a9e4efa26ff7149d9d/mode:33188/mtime:1684308365/uid:501/uname:lebedev
x-amz-storage-class:STANDARD

content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-blobstore.temporary-blob;x-amz-meta-s3cmd-attrs;x-amz-storage-class
791f0612803520adaf33869579e48951ebbcb741a5a513c85a04d600d0278f26
----------------------
DEBUG: signature-v4 headers: {'content-length': '316', 'content-type': 'binary/octet-stream', 'x-amz-meta-blobstore.temporary-blob': 'true', 'x-amz-meta-s3cmd-attrs': 'atime:1684308365/ctime:1684327250/gid:0/gname:wheel/md5:a9949994865960a9e4efa26ff7149d9d/mode:33188/mtime:1684308365/uid:501/uname:lebedev', 'x-amz-storage-class': 'STANDARD', 'x-amz-date': '20230518T082224Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=JNGRYLO4EEXYDZDOJZ781/20230518/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-blobstore.temporary-blob;x-amz-meta-s3cmd-attrs;x-amz-storage-class,Signature=e68dcf69afeb64a306d4ff93f575fbaa567e4f410e718a2a4abc527e235213d3', 'x-amz-content-sha256': '791f0612803520adaf33869579e48951ebbcb741a5a513c85a04d600d0278f26'}
DEBUG: get_hostname(package-cache-nexus-proxy-cache): s3-fast-api.query.consul-test
DEBUG: ConnMan.get(): re-using connection: https://s3-fast-api.query.consul-test#1
DEBUG: format_uri(): /package-cache-nexus-proxy-cache/content/vol-19/chap-44/12ac5e23-8815-4374-b888-6dc2e0b6268d.properties.ingress.rm
 316 of 316   100% in    0s    88.04 KB/sDEBUG: ConnMan.put(): connection put back to pool (https://s3-fast-api.query.consul-test#2)
DEBUG: Response:
{'data': b'',
 'headers': {'accept-ranges': 'bytes',
             'connection': 'keep-alive',
             'content-length': '0',
             'date': 'Thu, 18 May 2023 08:22:24 GMT',
             'etag': '"a9949994865960a9e4efa26ff7149d9d"',
             'strict-transport-security': 'max-age=15724800; includeSubDomains',
             'x-amz-request-id': '1684398144418683956'},
 'reason': 'OK',
 'size': 316,
 'status': 200}
 316 of 316   100% in    0s     4.57 KB/s  done
DEBUG: MD5 sums: computed=a9949994865960a9e4efa26ff7149d9d, received=a9949994865960a9e4efa26ff7149d9d
```
