### ISSUE TITLE
weed server -s3 segfault

### ISSUE THREAD

**Issue by hencoappel** [seaweedfs/seaweedfs#4627]
**Describe the bug**
Version: 3.53

Running `weed server -s3` s3 cert/key file arguments on Linux results in a segfault. This is due to the change https://github.com/seaweedfs/seaweedfs/pull/4482 not initialising s3.port.https to 0 in seaweedfs/weed/command/server.go.

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27422ac]
goroutine 116 [running]:
github.com/seaweedfs/seaweedfs/weed/command.(*S3Options).startS3Server(0x51624e0)
        /github/workspace/weed/command/s3.go:269 +0xeac
github.com/seaweedfs/seaweedfs/weed/command.runServer.func2()
        /github/workspace/weed/command/server.go:271 +0x51
created by github.com/seaweedfs/seaweedfs/weed/command.runServer
        /github/workspace/weed/command/server.go:268 +0xd67

**Expected behavior**
Should not segfault on start up.

**Comment by hencoappel** [comment]
Created a pull request for this: https://github.com/seaweedfs/seaweedfs/pull/4667

**Comment by hencoappel** [comment]
Pull request merged.
