### ISSUE TITLE
loss of mount point at high load (fuse mount)

### ISSUE THREAD

**Issue by setar** [seaweedfs/seaweedfs#4968]
# SeaWeedFS
all-in-one storage server on ubuntu LTS 20.04  , weed v3.57 from binary releases @github

## Services start options:
```
  ExecStart=/usr/local/sbin/weed master -mdir=/data/seaweedfs/master -ip=192.168.0.12 -defaultReplication=000
  ExecStart=/usr/local/sbin/weed volume -dir=/data/seaweedfs/volume -dataCenter=one -rack=rack1 -mserver=192.168.0.12:9333 -ip=192.168.0.12 -max=0
  ExecStart=/usr/local/sbin/weed filer -s3 -dataCenter=one -rack=rack1 -master=192.168.0.12:9333 -ip=192.168.0.12
  ExecStart=/usr/local/sbin/weed mount -filer=192.168.0.12:8888 -dir="/data/mnt"
```

## `> cluster.ps`
```
* filers 1
  * 192.168.0.12:8888 (30GB 3.57 0f8168c0c928bba3d2f48b0680d3bdce9c617559) 2023-10-30 22:06:42.881127352 +0000 UTC
    DataCenter: one
    signature: 779212908
* filer 192.168.0.12:8888 metadata sync time
* volume servers 1
  * data center: one
    * rack: rack1
      * 192.168.0.12:8080 (30GB 3.57 0f8168c0c928bba3d2f48b0680d3bdce9c617559)
```
 
## `> cluster.check`
```
Topology volumeSizeLimit:30000 MB hdd(volume:7/7 active:7 free:0 remote:0)
the cluster has 1 filers: [192.168.0.12:8888]
the cluster has 1 volume servers: [192.168.0.12:8080]
checking master localhost:9333 to volume server 192.168.0.12:8080 ... ok round trip 0.679ms clock delta 0.076ms
checking volume server 192.168.0.12:8080 to master localhost:9333 ... ok round trip 31.303ms clock delta 15.374ms
checking filer 192.168.0.12:8888 to master localhost:9333 ... ok round trip 16.578ms clock delta 7.773ms
checking filer 192.168.0.12:8888 to volume server 192.168.0.12:8080 ... ok round trip 0.632ms clock delta 0.064ms
checking filer 192.168.0.12:8888 to 192.168.0.12:8888 ... ok round trip 0.511ms clock delta 0.103ms
```

# Load
zimbra mail server creates a significant load on the file system, the utilization of HDD disk speeds according to iostat -x is close to 100%

# BUG (crash fuse mount server)

I tried different types of zimbra server connection: 
via NFS from client to storage server 
and weedfiler + weedmount on client, the result is the same

# the crutch script ;)
```
while true ; do 
  crash_fs="`journalctl -n 3 -u seaweedmount | cat | grep "status=255/EXCEPTION" |wc -l`" ; 
  if (( $(echo $crash_fs) == '1' )) ; then 
    echo "`date`, status=crash" ; 
    umount -f -l /opt/zimbra/store && systemctl restart seaweedmount ; 
  fi ; 
  sleep 10 ;  
done
```
# LOGS

```
Вт 31 окт 2023 09:21:24 MSK, status=crash
Вт 31 окт 2023 11:30:16 MSK, status=crash
```
```
окт 31 08:50:08 zimbra-store systemd[1]: Started SeaweedFS mount.
окт 31 08:50:10 zimbra-store seaweedfs-mount[40135]: mount point owner uid=0 gid=0 mode=drwxr-xr-x
окт 31 08:50:10 zimbra-store seaweedfs-mount[40135]: current uid=0 gid=0
окт 31 08:50:10 zimbra-store seaweedfs-mount[40135]: I1031 08:50:10.678303 leveldb_store.go:47 filer store dir: /tmp/eaeae2ae/meta
окт 31 08:50:10 zimbra-store seaweedfs-mount[40135]: I1031 08:50:10.679837 file_util.go:23 Folder /tmp/eaeae2ae/meta Permission: -rwxr-xr-x
окт 31 08:50:10 zimbra-store seaweedfs-mount[40135]: I1031 08:50:10.857621 mount_std.go:268 mounted 192.168.0.12:8888/ to /data/mnt
окт 31 08:50:10 zimbra-store seaweedfs-mount[40135]: I1031 08:50:10.858152 mount_std.go:269 This is SeaweedFS version 30GB 3.57 0f8168c0c928bba3d2f48b0680d3bdce9c617559 linux amd64
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: F1031 09:21:19.224273 inode_to_path.go:153 MarkChildrenCached not found inode /0/124/msg/0
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: goroutine 121533 [running]:
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/glog/glog.go:768 +0x85
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x517bce0, 0x3, 0xc0005360e0, {0x4058547?, 0xc00143faf0?}, 0x1?, 0x0)
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/glog/glog.go:719 +0x38a
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0xc004429cc0?, 0xc?, {0x3069b4c, 0x25}, {0xc00143faf0, 0x1, 0x1})
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/glog/glog.go:657 +0x10a
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/glog/glog.go:1154
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/mount.(*InodeToPath).MarkChildrenCached(0xc00081c2a0, {0xc004429cc0, 0xc})
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/mount/inode_to_path.go:153 +0x110
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/mount.NewSeaweedFileSystem.func1({0xc004429cc0?, 0x11?})
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/mount/weedfs.go:104 +0x2c
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.doEnsureVisited(0xc000459080, {0x37db418, 0xc0008b49a0}, {0xc004429cc0, 0xc})
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/mount/meta_cache/meta_cache_init.go:63 +0x1e9
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.EnsureVisited(0xc000459080, {0x37db418, 0xc0008b49a0}, {0xc004429cc0?, 0x2617b17?})
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/mount/meta_cache/meta_cache_init.go:25 +0x7b
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).maybeLoadEntry(0xc0008b49a0, {0xc004429cc0, 0x19})
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/mount/weedfs.go:174 +0x218
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).maybeReadEntry(0xc0008b49a0, 0xc0007d3a40?)
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/mount/weedfs.go:148 +0xa7
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).GetXAttr(0x47d8ca?, 0xc001dca240?, 0xc00143fe10?, {0xc01c95b9c8, 0x17}, {0xc00bbf3000, 0x1000, 0x28d9480?})
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /github/workspace/weed/mount/weedfs_xattr.go:40 +0x7f
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/hanwen/go-fuse/v2/fuse.doGetXAttr(0xc0008b4580, 0xc001dca240)
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.0/fuse/opcode.go:289 +0x1cc
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0008b4580, 0xc001dca240)
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.0/fuse/server.go:526 +0x267
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0008b4580, 0x65?)
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.0/fuse/server.go:499 +0x110
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]: created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest in goroutine 121530
окт 31 09:21:19 zimbra-store seaweedfs-mount[40135]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.0/fuse/server.go:366 +0x53f
окт 31 09:21:20 zimbra-store systemd[1]: seaweedmount.service: Main process exited, code=exited, status=255/EXCEPTION
окт 31 09:21:20 zimbra-store systemd[1]: seaweedmount.service: Failed with result 'exit-code'.
окт 31 09:21:24 zimbra-store systemd[1]: Started SeaweedFS mount.
окт 31 09:21:27 zimbra-store seaweedfs-mount[41711]: mount point owner uid=0 gid=0 mode=drwxr-xr-x
окт 31 09:21:27 zimbra-store seaweedfs-mount[41711]: current uid=0 gid=0
окт 31 09:21:27 zimbra-store seaweedfs-mount[41711]: I1031 09:21:27.408835 leveldb_store.go:47 filer store dir: /tmp/eaeae2ae/meta
окт 31 09:21:27 zimbra-store seaweedfs-mount[41711]: I1031 09:21:27.410256 file_util.go:23 Folder /tmp/eaeae2ae/meta Permission: -rwxr-xr-x
окт 31 09:21:27 zimbra-store seaweedfs-mount[41711]: I1031 09:21:27.612762 mount_std.go:268 mounted 192.168.0.12:8888/ to /data/mnt
окт 31 09:21:27 zimbra-store seaweedfs-mount[41711]: I1031 09:21:27.612796 mount_std.go:269 This is SeaweedFS version 30GB 3.57 0f8168c0c928bba3d2f48b0680d3bdce9c617559 linux amd64
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: F1031 11:30:13.050032 inode_to_path.go:153 MarkChildrenCached not found inode /0/40/msg/7
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: goroutine 247971 [running]:
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/glog/glog.go:768 +0x85
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x517bce0, 0x3, 0xc0005b80e0, {0x4058547?, 0xc001099af0?}, 0x1?, 0x0)
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/glog/glog.go:719 +0x38a
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0xc00790aae0?, 0xb?, {0x3069b4c, 0x25}, {0xc001099af0, 0x1, 0x1})
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/glog/glog.go:657 +0x10a
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/glog/glog.go:1154
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/mount.(*InodeToPath).MarkChildrenCached(0xc00088b650, {0xc00790aae0, 0xb})
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/mount/inode_to_path.go:153 +0x110
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/mount.NewSeaweedFileSystem.func1({0xc00790aae0?, 0x11?})
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/mount/weedfs.go:104 +0x2c
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.doEnsureVisited(0xc00046f5c0, {0x37db418, 0xc000760580}, {0xc00790aae0, 0xb})
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/mount/meta_cache/meta_cache_init.go:63 +0x1e9
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.EnsureVisited(0xc00046f5c0, {0x37db418, 0xc000760580}, {0xc00790aae0?, 0x2617b17?})
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/mount/meta_cache/meta_cache_init.go:25 +0x7b
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).maybeLoadEntry(0xc000760580, {0xc00790aae0, 0x1b})
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/mount/weedfs.go:174 +0x218
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).maybeReadEntry(0xc000760580, 0xc0007eef90?)
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/mount/weedfs.go:148 +0xa7
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).GetXAttr(0x47d8ca?, 0xc0030c6900?, 0xc001099e10?, {0xc01eef8678, 0x17}, {0xc002584000, 0x1000, 0x28d9480?})
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /github/workspace/weed/mount/weedfs_xattr.go:40 +0x7f
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/hanwen/go-fuse/v2/fuse.doGetXAttr(0xc00045a420, 0xc0030c6900)
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.0/fuse/opcode.go:289 +0x1cc
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc00045a420, 0xc0030c6900)
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.0/fuse/server.go:526 +0x267
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc00045a420, 0x80?)
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.0/fuse/server.go:499 +0x110
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]: created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest in goroutine 247759
окт 31 11:30:13 zimbra-store seaweedfs-mount[41711]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.0/fuse/server.go:366 +0x53f
окт 31 11:30:13 zimbra-store systemd[1]: seaweedmount.service: Main process exited, code=exited, status=255/EXCEPTION
окт 31 11:30:13 zimbra-store systemd[1]: seaweedmount.service: Failed with result 'exit-code'.
```

## P.S. dmesg in he same time is clean (HDD not have any hardware problems)

**Comment by chrislusf** [comment]
added a fix. please help to test it.

**Comment by setar** [comment]
This fix looks good, I think it will work. I'm doing a load check. Do you understand why this warning appears and do I need to worry about this situation? Thanks
