### ISSUE TITLE
Filer: k8s installation via helm version 3.60.1, filer pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by ykhedar** [seaweedfs/seaweedfs#5167]
**Describe the bug**
Filer pod fails to start. With the new helm chart version 3.60.1, the filer pod seems to be getting nil pointer dereference.
With default installation via helm - 
`helm upgrade --install seaweedfs seaweedfs/seaweedfs`

**Expected behavior**
Successful bootup.

**Filer logs**
```
I0105 20:16:38.163927 config.go:46 Reading : Config File "security" Not Found in "[/data /root/.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
I0105 20:16:38.168182 masterclient.go:127 .filer masterClient bootstraps with masters {[seaweedfs-master-0.seaweedfs-master.default:9333] <nil>}
I0105 20:16:38.168211 masterclient.go:173 .filer masterClient Connecting to master seaweedfs-master-0.seaweedfs-master.default:9333
I0105 20:16:38.168344 config.go:59 Reading filer.toml from /etc/seaweedfs/filer.toml
W0105 20:16:38.168354 filer_server.go:155 skipping default store dir in ./filerldb2
I0105 20:16:38.169110 masterclient.go:198 .filer masterClient Connected to seaweedfs-master-0.seaweedfs-master.default:9333
I0105 20:16:38.169200 config.go:46 Reading : Config File "notification" Not Found in "[/data /root/.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
I0105 20:16:38.169321 leveldb2_store.go:42 filer store leveldb2 dir: /data/filerldb2
I0105 20:16:38.169337 file_util.go:27 Folder /data/filerldb2 Permission: -rwxr-xr-x
I0105 20:16:38.169380 masterclient.go:294 updateVidMap(DefaultDataCenter) .filer: seaweedfs-volume-0.seaweedfs-volume.default:8080 volume add: 0, del: 0, add ec: 0 del ec: 0
I0105 20:16:38.299934 filer.go:169 existing filer.store.id = -1072196138
I0105 20:16:38.299947 configuration.go:28 configured filer store to leveldb2
I0105 20:16:38.300598 master_client.go:20 the cluster has 1 filer
I0105 20:16:38.300622 filer.go:123 10.78.0.58:8888 aggregate from peers [10.78.0.58:8888]
I0105 20:16:38.302996 filer.go:288 Start Seaweed Filer 30GB 3.60 d4e91b6ad at 10.78.0.58:8888
I0105 20:16:38.302991 meta_aggregator.go:92 loopSubscribeToOneFiler read 10.78.0.58:8888 start from 2024-01-05 20:15:38.300611744 +0000 UTC 1704485738300611744
I0105 20:16:38.303516 meta_aggregator.go:103 subscribing remote 10.78.0.58:8888 meta change: connecting to peer filer 10.78.0.58:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 10.78.0.58:18888: connect: connection refused"
I0105 20:16:40.037422 meta_aggregator.go:92 loopSubscribeToOneFiler read 10.78.0.58:8888 start from 2024-01-05 20:15:38.300611744 +0000 UTC 1704485738300611744
I0105 20:16:40.038589 meta_aggregator.go:189 subscribing remote 10.78.0.58:8888 meta change: 2024-01-05 20:15:38.300611744 +0000 UTC, clientId:797332816
I0105 20:16:40.039337 filer_grpc_server_sub_meta.go:296 + local listener filer:10.78.0.58:8888@10.78.0.58:38040 clientId -797332816 clientEpoch 1
I0105 20:16:40.039344 filer_grpc_server_sub_meta.go:117  + filer:10.78.0.58:8888@10.78.0.58:38040 local subscribe / from 2024-01-05 20:15:38.300611744 +0000 UTC clientId:-797332816
I0105 20:16:40.039358 filer_grpc_server_sub_meta.go:130 read on disk filer:10.78.0.58:8888@10.78.0.58:38040 local subscribe / from 2024-01-05 20:15:38.300611744 +0000 UTC
I0105 20:16:40.039387 filer_grpc_server_sub_meta.go:149 read in memory filer:10.78.0.58:8888@10.78.0.58:38040 local subscribe / from 2024-01-05 20:15:38.300611744 +0000 UTC
I0105 20:16:40.165032 s3.go:202 S3 read filer buckets dir: /buckets
I0105 20:16:40.165047 s3.go:209 connected to filer 10.78.0.58:8888 grpc address 10.78.0.58:18888
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cf9bf5]

goroutine 87 [running]:
github.com/seaweedfs/seaweedfs/weed/command.(*S3Options).startS3Server(0x3cc9860)
        /go/src/github.com/seaweedfs/seaweedfs/weed/command/s3.go:226 +0x495
github.com/seaweedfs/seaweedfs/weed/command.runFiler.func1(0x0?)
        /go/src/github.com/seaweedfs/seaweedfs/weed/command/filer.go:185 +0x26
created by github.com/seaweedfs/seaweedfs/weed/command.runFiler in goroutine 1
        /go/src/github.com/seaweedfs/seaweedfs/weed/command/filer.go:183 +0x2aa
```
I might be wrong but from my understanding it looks like related to - https://github.com/seaweedfs/seaweedfs/commit/06343f897645c4650f8f65e9a7ecd9b255820cfd

On a another note, if you could confirm -  this line in helmchart looks wrong to me - https://github.com/seaweedfs/seaweedfs/blob/master/k8s/charts/seaweedfs/templates/volume-statefulset.yaml#L256

**Comment by ykhedar** [comment]
Related to https://github.com/seaweedfs/seaweedfs/issues/5153
