### ISSUE TITLE
Runtime panic from 3.62

### ISSUE THREAD

**Issue by Cottand** [seaweedfs/seaweedfs#5244]
**Describe the bug**
The following panic on filer start:
```
I0125 21:58:50.993467 filer_grpc_server_sub_meta.go:36  backup_s3@172.26.64.1:52240 starts to subscribe / from 2024-01-25 21:10:29.022901885 +0000 UTC
I0125 21:58:51.076594 webdav.go:104 connected to filer 10.10.0.1:8888 grpc address 10.10.0.1:18888
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d06d2b]

goroutine 72 [running]:
github.com/seaweedfs/seaweedfs/weed/command.(*WebDavOption).startWebDav(0x3cc8ea0)
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/webdav.go:121 +0x4cb
github.com/seaweedfs/seaweedfs/weed/command.runFiler.func2(0x0?)
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer.go:200 +0x26
created by github.com/seaweedfs/seaweedfs/weed/command.runFiler in goroutine 1
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer.go:198 +0x35b
```

**System Setup**

```
weed with args:
          "-logtostderr",
          "filer",
          "-ip=${NOMAD_IP_http}",
          "-ip.bind=0.0.0.0",
          "-master=seaweedfs-master-http.nomad:${var.master_port_http}.${var.master_port_grpc}",
          "-port=${NOMAD_PORT_http}",
          "-port.grpc=${NOMAD_PORT_grpc}",
          "-metricsPort=${NOMAD_PORT_metrics}",
          "-webdav",
          "-webdav.collection=",
          "-webdav.replication=020",
          "-webdav.port=${NOMAD_PORT_webdav}",
          "-s3",
          "-s3.port=${NOMAD_PORT_s3}",
          "-s3.allowEmptyFolder=false",

```

**Expected behavior**
No runtime panics :)

**Additional context**

A suspect the bug was introduced in 3.61

**Comment by Cottand** [comment]
I also believe this to be unrelated to https://github.com/seaweedfs/seaweedfs/issues/5153 because
- the stack trace is different
- this still happens om 3.62
