### ISSUE TITLE
[mount] exit on  filer_pb_tail.go:91 process directory 

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#5289]
**Describe the bug**
logs

```
2024/02/06 10:12:49 writer: Write/Writev failed, err: 22=invalid argument. opcode: READDIRPLUS
F0206 10:16:41.653863 filer_pb_tail.go:91 process directory:"/domain/documents/6/1/1"  event_notification:{new_entry:{name:"611f1909871900f7a0311af09135>
goroutine 228 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
        /github/workspace/weed/glog/glog.go:768 +0x85
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x55d4780, 0x3, 0xc00092a770, {0x43121f9?, 0xc0009ff9a8?}, 0x2?, 0x0)
        /github/workspace/weed/glog/glog.go:719 +0x38a
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0xc000b34601?, 0x9ff8c8?, {0x321f9d3, 0xe}, {0xc0009ff9a8, 0x2, 0x2})
        /github/workspace/weed/glog/glog.go:657 +0x10a
github.com/seaweedfs/seaweedfs/weed/glog.Fatalf({0x321f9d3?, 0x3a59c40?}, {0xc0009ff9a8?, 0x0?, 0x0?})
        /github/workspace/weed/glog/glog.go:1154 +0x38
github.com/seaweedfs/seaweedfs/weed/pb.WithFilerClientFollowMetadata.makeSubscribeMetadataFunc.func1({0x3a860b8, 0xc0008d3fa0})
        /github/workspace/weed/pb/filer_pb_tail.go:91 +0x38e
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1.1(0xc000cca800)
        /github/workspace/weed/mount/wfs_filer_client.go:27 +0x68
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcClient(0x71?, 0x545991a6?, 0xc0009ffcf0, {0xc0000787b0, 0x12}, 0x0?, {0xc0009ffce0?, 0x1?, 0x1?})
        /github/workspace/weed/pb/grpc_client_server.go:155 +0x348
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1()
        /github/workspace/weed/mount/wfs_filer_client.go:25 +0x15e
github.com/seaweedfs/seaweedfs/weed/util.Retry({0x3212f59, 0xa}, 0xc0032ade00)
        /github/workspace/weed/util/retry.go:16 +0xa7
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient(0x0?, 0x0?, 0x0?)
        /github/workspace/weed/mount/wfs_filer_client.go:18 +0x65
github.com/seaweedfs/seaweedfs/weed/pb.WithFilerClientFollowMetadata({0x3a4dfb8, 0xc000a68580}, 0xc00077bd80, 0xc000011608)
        /github/workspace/weed/pb/filer_pb_tail.go:50 +0x87
github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.SubscribeMetaEvents.func2()
        /github/workspace/weed/mount/meta_cache/meta_cache_subscribe.go:74 +0x26
github.com/seaweedfs/seaweedfs/weed/util.RetryUntil({0x322b21f, 0x11}, 0xc0032adf60, 0x3406e08)
        /github/workspace/weed/util/retry.go:64 +0x4e
github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.SubscribeMetaEvents(0xc000ce20c0, 0x545991a6, {0x3a4dfb8, 0xc000a68580}, {0x7ffc0c2d8ec7, 0x1}, 0x17a05d598fb725>
        /github/workspace/weed/mount/meta_cache/meta_cache_subscribe.go:72 +0x176
created by github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).StartBackgroundTasks in goroutine 1
        /github/workspace/weed/mount/weedfs.go:123 +0x152
```

**System Setup**
```
weed version 8000GB 3.58 linux amd64
```

**Comment by chrislusf** [comment]
The logs seem to be missing the actual error at the end of `filer_pb_tail.go:91`

**Comment by chrislusf** [comment]
Is this reproducible or restarting helps?

**Comment by chrislusf** [comment]
not clear how to reproduce this.
