### ISSUE TITLE
Export failed on volume transferred to S3

### ISSUE THREAD

**Issue by tomkoy** [seaweedfs/seaweedfs#5377]
Export failed on volume transferred to S3
Seaweedfs 3.63

command:
./weed export -dir=vol1 -volumeId=2

output:
`
key     name    size    gzip    mime    modified        ttl     deleted start   stop
I0313 12:56:03.068648 volume_tier.go:28 volume 2 is tiered to s3.default as cb74c56f-9929-4efd-8313-08636b6d8da9 and read only
I0313 12:56:03.068957 volume_loading.go:49 loading volume 2 from remote files:{backend_type:"s3"  backend_id:"default"  key:"cb74c56f-9929-4efd-8313-08636b6d8da9"  file_size:25884056  modified_time:1710181192  extension:".dat"}  version:2  BytesOffset:4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x104144b]

goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).LoadRemoteFile(0xc00060a000)
        /github/workspace/weed/storage/volume_tier.go:68 +0xcb
github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).load(0xc00060a000, 0x0, 0x0, 0x0, 0x0)
        /github/workspace/weed/storage/volume_loading.go:50 +0x185
github.com/seaweedfs/seaweedfs/weed/storage.loadVolumeWithoutIndex({0x7ffe1f1411bf, 0x4}, {0x0, 0x0}, 0x2, 0x0)
        /github/workspace/weed/storage/volume_loading.go:23 +0xb7
github.com/seaweedfs/seaweedfs/weed/storage.ScanVolumeFile({0x7ffe1f1411bf?, 0x4?}, {0x0?, 0x38?}, 0x2, 0x0?, {0x2bcf970, 0xc00058c080})
        /github/workspace/weed/storage/volume_read.go:214 +0x5b
github.com/seaweedfs/seaweedfs/weed/command.runExport(0x3f20ab8?, {0xc0001be060?, 0x2?, 0x2?})
        /github/workspace/weed/command/export.go:216 +0xa95
main.main()
        /github/workspace/weed/weed.go:80 +0x2c2
`

**Comment by chrislusf** [comment]
Did this happen when the volume server was starting?

**Comment by tomkoy** [comment]
Nope, thing works normally, other volumen "native" works fine
