### ISSUE TITLE
filer.backup fails with panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by stibi** [seaweedfs/seaweedfs#5571]
**Describe the bug**
Error when running `weed filer.backup`:

```
I0508 21:45:35.281247 s3_sink.go:78 sink.s3.region: eu-central-1
I0508 21:45:35.281546 s3_sink.go:79 sink.s3.bucket: my-backup-bucket-on-aws-s3
I0508 21:45:35.281558 s3_sink.go:80 sink.s3.directory: /
I0508 21:45:35.281562 s3_sink.go:81 sink.s3.endpoint: https://s3.eu-central-1.amazonaws.com
I0508 21:45:35.281565 s3_sink.go:82 sink.s3.acl:
I0508 21:45:35.281569 s3_sink.go:83 sink.s3.is_incremental: false
I0508 21:45:35.281573 s3_sink.go:84 sink.s3.s3_disable_content_md5_validation: true
I0508 21:45:35.281577 s3_sink.go:85 sink.s3.s3_force_path_style: true
I0508 21:45:35.281586 s3_sink.go:86 sink.s3.keep_part_size: true
I0508 21:45:35.281590 s3_sink.go:92 sink.s3.uploader_max_upload_parts: 1000
I0508 21:45:35.281630 s3_sink.go:94 sink.s3.uploader_part_size_mb: 0
I0508 21:45:35.281636 s3_sink.go:95 sink.s3.uploader_concurrency: 8
I0508 21:45:35.281711 filer_replication.go:129 Configure sink to s3
I0508 21:45:35.284242 filer_backup.go:116 resuming from 2024-04-17 13:05:17.846599071 +0000 UTC
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/replication/sink/s3sink.(*S3Sink).CreateEntry(0xc00031b4d0, {0xc000a08100?, 0xc000378770?}, 0xc000a344d0, {0x7?, 0xc000a2a030?, 0x17?})
	/go/src/github.com/seaweedfs/seaweedfs/weed/replication/sink/s3sink/s3_sink.go:179 +0x1f1
github.com/seaweedfs/seaweedfs/weed/command.doFilerBackup.genProcessFunction.func3(0xc000884640)
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer_sync.go:433 +0x50b
github.com/seaweedfs/seaweedfs/weed/command.doFilerBackup.AddOffsetFunc.func4(0xc000884640)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb_tail.go:112 +0x47
github.com/seaweedfs/seaweedfs/weed/pb.FollowMetadata.makeSubscribeMetadataFunc.func1({0x2c28618, 0xc0003ba9b0})
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb_tail.go:86 +0x298
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcFilerClient.func1(0xc00091a008)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:262 +0x68
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcClient(0x59?, 0x0?, 0xc0007d3a40, {0xc0001ff0f0, 0xf}, 0x9?, {0xc0007d3a30?, 0x2?, 0x9?})
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:155 +0x343
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcFilerClient(0x1, 0x0, {0x242e059?, 0x45bb0a?}, {0x2bea5c0, 0xc0001adca0}, 0xc0007d3a90)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:260 +0xae
github.com/seaweedfs/seaweedfs/weed/pb.WithFilerClient(...)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:254
github.com/seaweedfs/seaweedfs/weed/pb.FollowMetadata({0x242e059?, 0x242098b?}, {0x2bea5c0?, 0xc0001adca0?}, 0xc0007d3dc0?, 0x2bd9468?)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb_tail.go:41 +0x69
github.com/seaweedfs/seaweedfs/weed/command.doFilerBackup({0x2bea5c0, 0xc0001adca0}, 0x3f852e0, 0x2b351b9f, 0x1)
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer_backup.go:164 +0xa58
github.com/seaweedfs/seaweedfs/weed/command.runFilerBackup(0x3f68758?, {0xc0001c2010?, 0x0?, 0x0?})
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer_backup.go:71 +0x99
main.main()
	/go/src/github.com/seaweedfs/seaweedfs/weed/weed.go:80 +0x2c2
```

**System Setup**
- `weed s3 -filer=localhost:8888 -ip.bind=0.0.0.0 -config=/vault/secrets/s3-identities.json`
- `weed filer -master=localhost:9333 -ip.bind=0.0.0.0`
- `weed master -ip.bind=0.0.0.0 -defaultReplication=00`
- OS version - Alpine Linux 3.19.1
- output of `weed version`: version 30GB 3.64 b74e8082b linux amd64

**Expected behavior**
Working backup of seaweed to S3.

Any idea if a bug or problem with configuration?

Thanks a lot.

**Comment by chrislusf** [comment]
duplicate with https://github.com/seaweedfs/seaweedfs/pull/5406

**Comment by stibi** [comment]
Thanks, I updated to latest seaweed and this is solved. Unfortunately, there is [another trouble](https://github.com/seaweedfs/seaweedfs/issues/5572).
