### ISSUE TITLE
CSI Failed with Nomad

### ISSUE THREAD

**Issue by fred-gb** [seaweedfs/seaweedfs#5664]
Bonjour, 👋🏻 
I discovered Seaweed last week, it's very interesting!

**Describe the bug**
I don't think it was bug, just I don't understand how it's works 😅 HELP ! 

**System Setup**
Developement environment :
Ubuntu 24.04
Nomad 1.8.0

**Steps**
I installed Seaweed in cluster mode, on hosts, I don't want to have Nomad Job for this storage.

<img width="758" alt="Capture d’écran 2024-06-10 à 15 38 01" src="https://github.com/seaweedfs/seaweedfs/assets/17061623/f365eec0-da6e-4dbd-a8ba-98bc25aad3e8">

the filer:
```
/usr/local/bin/weed filer -ip.bind=0.0.0.0 -ip=10.0.0.40 -port=8888 -master=10.0.0.40:9333,10.0.0.50:9333,10.0.0.60:9333  -s3  -dataCenter=dc1 -rack=rack1  -metricsPort=9300
```

It seems to work:
```
root@dev-cluster-node04:/opt# curl http://10.0.0.50:8080/5,085d475248
CECI EST UNE TEST
```

On Nomad, I create a job:

```
job "seaweedfs-csi" {
  datacenters = ["dc1"]

  type = "system"

  update {
    max_parallel  = 1
    stagger       = "60s"
  }

  constraint {
    operator = "distinct_hosts"
    value = true
  }
 

  group "nodes" {
  
   	network {
      mode = "host"
    }
    
    ephemeral_disk {
      migrate = false
      size    = 300
      sticky  = false
    }
      
    task "plugin" {
      driver = "docker"

      config {
        image = "chrislusf/seaweedfs-csi-driver:latest"
        force_pull = "true"

        args = [
          "--endpoint=unix://csi/csi.sock",
          "--filer=172.17.0.1:8888",
          "--nodeid=${node.unique.name}",
          "--cacheCapacityMB=256",
          "--cacheDir=${NOMAD_TASK_DIR}/cache_dir",
        ]

        privileged = true
      }

      csi_plugin {
        id        = "seaweedfs"
        type      = "monolith"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 512
        memory = 1024
        memory_max = 3072 # W need to have memory oversubscription enabled
      }
    }
  }
}

```

I changed: `"--filer=172.17.0.1:8888",` to communicate with host.

When Iaunched this job, it works:
![Capture d’écran 2024-06-10 à 15 51 41](https://github.com/seaweedfs/seaweedfs/assets/17061623/d2224475-9068-4e9a-915f-18d8a76ac403)

Following examples models: https://github.com/seaweedfs/seaweedfs-csi-driver/tree/master/deploy/nomad

I created volume like example:
```
root@dev-cluster-node01:/opt# nomad volume status example-seaweedfs-volume
ID                   = example-seaweedfs-volume
Name                 = example-seaweedfs-volume
Namespace            = default
External ID          = example-seaweedfs-volume
Plugin ID            = seaweedfs
Provider             = seaweedfs-csi-driver
Version              = 1.0.0
Capacity             = 10 GiB
Schedulable          = true
Controllers Healthy  = 3
Controllers Expected = 3
Nodes Healthy        = 3
Nodes Expected       = 3
Access Mode          = <none>
Attachment Mode      = <none>
Mount Options        = flags: [REDACTED]
Namespace            = default

Allocations
No allocations placed
```

As soon I started the example job, I have this error:
```
Setup Failure 	failed to setup alloc: pre-run hook "csi_hook" failed: mounting volumes: rpc error: code = Unavailable desc = error reading from server: EOF
```

And CSI plugin goes failed on node where allocation is with this logs:
```
I0610 14:00:31.792341 nodeserver.go:34 node stage volume example-seaweedfs-volume to /local/csi/staging/default/example-seaweedfs-volume/rw-file-system-multi-node-multi-writer
I0610 14:00:31.793985 mounter_seaweedfs.go:45 mounting [172.17.0.1:8888] /buckets/example-seaweedfs-volume to /local/csi/staging/default/example-seaweedfs-volume/rw-file-system-multi-node-multi-writer
I0610 14:00:31.795085 mounter.go:53 Mounting fuse with command: weed and args: [-logtostderr=true mount -dirAutoCreate=true -umask=000 -dir=/local/csi/staging/default/example-seaweedfs-volume/rw-file-system-multi-node-multi-writer -localSocket=/tmp/seaweedfs-mount-1892693304.sock -cacheDir=/local/cache_dir/example-seaweedfs-volume -filer.path=/buckets/example-seaweedfs-volume -cacheCapacityMB=256 -collection=example-seaweedfs-volume -filer=172.17.0.1:8888 -concurrentWriters=32]
I0610 14:00:31.927264 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c0_2_0.ldb, watermark 0, num of entries:0
I0610 14:00:31.934238 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c0_2_0.ldb... , watermark: 0
I0610 14:00:31.943374 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c0_2_1.ldb, watermark 0, num of entries:0
I0610 14:00:31.953164 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c0_2_1.ldb... , watermark: 0
I0610 14:00:31.967913 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_0.ldb, watermark 0, num of entries:0
I0610 14:00:31.977085 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_0.ldb... , watermark: 0
I0610 14:00:31.991051 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_1.ldb, watermark 0, num of entries:0
I0610 14:00:31.998402 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_1.ldb... , watermark: 0
I0610 14:00:32.042412 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_2.ldb, watermark 0, num of entries:0
I0610 14:00:32.058531 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_2.ldb... , watermark: 0
I0610 14:00:32.071718 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c2_2_0.ldb, watermark 0, num of entries:0
I0610 14:00:32.082368 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c2_2_0.ldb... , watermark: 0
I0610 14:00:32.092189 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c2_2_1.ldb, watermark 0, num of entries:0
I0610 14:00:32.100619 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c2_2_1.ldb... , watermark: 0
I0610 14:00:32.101139 leveldb_store.go:47 filer store dir: /local/cache_dir/example-seaweedfs-volume/dc68c46c/meta
I0610 14:00:32.101219 file_util.go:27 Folder /local/cache_dir/example-seaweedfs-volume/dc68c46c/meta Permission: -rwxr-xr-x
I0610 14:00:32.121553 mount_std.go:268 mounted 172.17.0.1:8888/buckets/example-seaweedfs-volume to /local/csi/staging/default/example-seaweedfs-volume/rw-file-system-multi-node-multi-writer
I0610 14:00:32.121573 mount_std.go:269 This is SeaweedFS version 30GB 3.62  linux arm64
panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

goroutine 140 [running]:
github.com/seaweedfs/seaweedfs-csi-driver/pkg/k8s.NewInCluster()
	/go/src/github.com/seaweedfs/seaweedfs-csi-driver/pkg/k8s/client.go:16 +0x7c
github.com/seaweedfs/seaweedfs-csi-driver/pkg/k8s.GetVolumeCapacity({0x40000549a8, 0x18})
	/go/src/github.com/seaweedfs/seaweedfs-csi-driver/pkg/k8s/client.go:28 +0x38
github.com/seaweedfs/seaweedfs-csi-driver/pkg/driver.(*NodeServer).NodeStageVolume(0x400029fcb0, {0x1067808?, 0x10?}, 0x4000172720)
	/go/src/github.com/seaweedfs/seaweedfs-csi-driver/pkg/driver/nodeserver.go:84 +0xae8
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler.func1({0x168c488, 0x40001bd9e0}, {0x13341c0?, 0x4000172720})
	/go/pkg/mod/github.com/container-storage-interface/spec@v1.8.0/lib/go/csi/csi.pb.go:7034 +0x74
github.com/seaweedfs/seaweedfs-csi-driver/pkg/driver.logGRPC({0x168c488, 0x40001bd9e0}, {0x13341c0?, 0x4000172720?}, 0x4000280d40, 0x40004635a8)
	/go/src/github.com/seaweedfs/seaweedfs-csi-driver/pkg/driver/utils.go:64 +0xd4
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler({0x130d680?, 0x400029fcb0}, {0x168c488, 0x40001bd9e0}, 0x40000f6bd0, 0x1503a10)
	/go/pkg/mod/github.com/container-storage-interface/spec@v1.8.0/lib/go/csi/csi.pb.go:7036 +0x12c
google.golang.org/grpc.(*Server).processUnaryRPC(0x400002c000, {0x16924b8, 0x40001c11e0}, 0x40004470e0, 0x400029ffb0, 0x22e5040, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:1358 +0xc04
google.golang.org/grpc.(*Server).handleStream(0x400002c000, {0x16924b8, 0x40001c11e0}, 0x40004470e0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:1735 +0x7cc
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:970 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 63
	/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:981 +0x160
```

When I exec bash in allocation CSI plugin, I can reach Seaweed filer and volume:
```
/ # curl 172.17.0.1:8080/5,085d475248
CECI EST UNE TEST
```

```
# curl -i 172.17.0.1:8888
HTTP/1.1 200 OK
Server: SeaweedFS Filer 30GB 3.67
Date: Mon, 10 Jun 2024 13:23:57 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked

<!DOCTYPE html>
<html>
<head>
    <title>SeaweedFS Filer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/seaweedfsstatic/bootstrap/3.3.1/css/bootstrap.min.css">
    <style>
[...]
```

And a last screenshot:
<img width="1246" alt="Capture d’écran 2024-06-10 à 16 12 40" src="https://github.com/seaweedfs/seaweedfs/assets/17061623/d93f94e5-96d2-4a2d-b095-e3dcad57d3ff">

I logs, I can see:
```
panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```
Hard to defined when I use Nomad 😅 

I don't understand. Sorry... 😞

HELP! 🛟

**Comment by chrislusf** [comment]
see FAQ #1 https://github.com/seaweedfs/seaweedfs/wiki/FAQ#how-many-volumes-do-i-need

"A CSI mount is automatically mapped to a bucket, which needs a few volumes."

**Comment by fred-gb** [comment]
Thanks,
But I'm sorry. I don't understand.

I changed settings to:
`volumeSizeLimitMB=100`
`max=9`

My cluster:
<img width="1188" alt="Capture d’écran 2024-06-11 à 10 00 03" src="https://github.com/seaweedfs/seaweedfs/assets/17061623/aef1ead2-1740-4e6d-b4a2-a8a5984189e7">

But not working wet. Sames logs errors.

I can upload file with filer's UI.

Thanks
