### ISSUE TITLE
transport endpoint is not connected or Unable to find files in the mounted directory./weed version version 30GB 3.47 18686b7375cb02e6a3cda9d2f80387009c21826f linux amd64

### ISSUE THREAD

**Issue by Super-six-java** [seaweedfs/seaweedfs#5839]
Hello respected developer
    when I used to mount a remote dataset and ran the YOLOv5 algorithm for training, I occasionally encountered the problem of not being able to find the dataset images. However, I was able to find the images in the mount directory or the transport endpoint was not connected. Then we checked the issues and reproduced the problem:
   When the algorithm is training, we delete all files in the/tmp directory of the container` rm -rf /tmp/* `. At this point, the algorithm crashes and we restart it. When the algorithm starts loading images, we use the following command 
``` shell
apt install fio 
# Filename is the directory where the dataset is mounted
fio --name=random-write-test --ioengine=libaio --rw=randwrite --bs=4k --size=1G --numjobs=4 --runtime=60 --group_reporting  --filename=/data/model/dataset/train/xxxx
```
Write files randomly to the mounting directory, and then
Unable to find files in the mounted directory
We speculate that during the algorithm training process, a file was written to the mount directory, causing the cache to fail
__error msg__

`/data/model/dataset/train/yolov5-normal-3300/ ` is my mount point
```
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/model/code/yolov5/utils/dataloaders.py", line 776, in __getitem__
    img, labels = self.load_mosaic(index)
  File "/data/model/code/yolov5/utils/dataloaders.py", line 926, in load_mosaic
    img, _, (h, w) = self.load_image(index)
  File "/data/model/code/yolov5/utils/dataloaders.py", line 857, in load_image
    if fn.exists():  # load npy
  File "/usr/lib/python3.8/pathlib.py", line 1407, in exists
    self.stat()
  File "/usr/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
OSError: [Errno 107] Transport endpoint is not connected: '/data/model/dataset/train/yolov5-normal-3300/images/pexels-ana-ferreira-1895976_75.npy'
```
```
 df -h
df: /data/model/dataset/train: Transport endpoint is not connected
df: /data/model/dataset/test: Transport endpoint is not connected
```

seaweedfs version ：run `/weed version `   echo :  `version 30GB 3.47 18686b7375cb02e6a3cda9d2f80387009c21826f linux 
amd64`
linux version :`Linux beda8eb8fba0 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by chrislusf** [comment]
the cache directory is under `/tmp/` by default. Try to configure `weed mount -cacheDir=xxx` to some other directory.

**Comment by Super-six-java** [comment]
> the cache directory is under `/tmp/` by default. Try to configure `weed mount -cacheDir=xxx` to some other directory.默认情况下，缓存目录位于 `/tmp/` 下。尝试将`杂草挂载 -cacheDir=xxx` 配置到其他目录。

Thank you for your answer, but as a matter of course, the cache is lost and should not affect the operation of the mount

**Comment by mag101** [comment]
-cacheDir=xxx doesn't fix issue.
in fstab " fuse	/mnt/ocom/app	fuse.weed  cacheDir=/var/cache/seaweedfs/mnt-ocom-app
ls  /var/cache/seaweedfs/mnt-ocom-app/5da05bd0
meta 
ls /tmp/5da05bd0
swap
last one not depend from "cacheDir" option and if remove rm -rf /tmp/5da05bd0
we have issue after 5 minutes:
ls -l /mnt/ocom/app
ls: cannot access '/mnt/ocom/app': Transport endpoint is not connected
very easy to reproduce.

**Comment by alzamonn** [comment]
some evidence where this is reproduced
`weed version
version 30GB 3.63  linux amd64
`
![image](https://github.com/user-attachments/assets/f40dbf53-e1ea-4588-a928-af1fcf210b9a)
