### ISSUE TITLE
mq.broker: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Material-Scientist** [seaweedfs/seaweedfs#5875]
**Describe the bug**
When trying to publish or consume messages via broker, the broker process crashes with:
```
I0809 18:57:20.514969 broker_topic_conf_read_write.go:35 load conf for topic my_namespace.my_topic from filer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x195d82a]

goroutine 174 [running]:
github.com/seaweedfs/seaweedfs/weed/mq/topic.(*LocalPartition).MaybeConnectToFollowers(0xc00037e5a0?, 0xc0008ac220?, {0x2c7e720?, 0xc00014ced8?})
        /github/workspace/weed/mq/topic/local_partition.go:137 +0x2a
github.com/seaweedfs/seaweedfs/weed/mq/broker.(*MessageQueueBroker).PublishMessage(0xc00037e5a0, {0x2caa558, 0xc000799ec0})
        /github/workspace/weed/mq/broker/broker_grpc_pub.go:66 +0x353
github.com/seaweedfs/seaweedfs/weed/pb/mq_pb._SeaweedMessaging_PublishMessage_Handler({0x243c520?, 0xc00037e5a0}, {0x2ca2728, 0xc00018a780})
        /github/workspace/weed/pb/mq_pb/mq_grpc.pb.go:579 +0xd8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000a56000, {0x2c9c478, 0xc0008a7b30}, {0x2cac380, 0xc00027e480}, 0xc0008c4900, 0xc000a0ed20, 0x407f760, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.64.1/server.go:1673 +0x1208
google.golang.org/grpc.(*Server).handleStream(0xc000a56000, {0x2cac380, 0xc00027e480}, 0xc0008c4900)
        /go/pkg/mod/google.golang.org/grpc@v1.64.1/server.go:1794 +0xe3a
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /go/pkg/mod/google.golang.org/grpc@v1.64.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 47
        /go/pkg/mod/google.golang.org/grpc@v1.64.1/server.go:1040 +0x125
```

Created stub files with:
```
python -m grpc_tools.protoc -I/root/proto --python_out=. --grpc_python_out=. /root/proto/mq.pr
oto
```

```
python -m grpc_tools.protoc -I/root/proto --python_out=. --grpc_python_out=. /root/proto/schem
a.proto
```

Launch broker:
```
weed mq.broker -master="10.0.0.4:9333" -ip="10.0.0.4"
```

Pub/sub from python:
```python
import grpc
import mq_pb2
import mq_pb2_grpc

# Connect to the SeaweedFS broker
channel = grpc.insecure_channel('10.0.0.4:17777')  # Replace with your broker's address
stub = mq_pb2_grpc.SeaweedMessagingStub(channel)

# Create a topic
def create_topic(namespace, topic_name, partition_count):
    request = mq_pb2.ConfigureTopicRequest(
        topic=mq_pb2.Topic(namespace=namespace, name=topic_name),
        partition_count=partition_count
    )
    response = stub.ConfigureTopic(request)
    print(f"Topic created: {response}")

# Publish messages to a topic
def publish_messages(namespace, topic_name, messages):
    def message_generator():
        yield mq_pb2.PublishMessageRequest(
            init=mq_pb2.PublishMessageRequest.InitMessage(
                topic=mq_pb2.Topic(namespace=namespace, name=topic_name),
                partition=mq_pb2.Partition(ring_size=1, range_start=0, range_stop=1)
            )
        )
        for msg in messages:
            yield mq_pb2.PublishMessageRequest(
                data=mq_pb2.DataMessage(
                    key=msg['key'].encode(),
                    value=msg['value'].encode()
                )
            )

    responses = stub.PublishMessage(message_generator())
    for response in responses:
        print(f"Message published: {response}")

# Consume messages from a topic
def consume_messages(namespace, topic_name):
    request = mq_pb2.SubscribeMessageRequest(
        init=mq_pb2.SubscribeMessageRequest.InitMessage(
            topic=mq_pb2.Topic(namespace=namespace, name=topic_name),
            partition_offset=mq_pb2.PartitionOffset(
                partition=mq_pb2.Partition(ring_size=1, range_start=0, range_stop=1),
                start_type=mq_pb2.PartitionOffsetStartType.EARLIEST
            )
        )
    )
    
    responses = stub.SubscribeMessage(request)
    for response in responses:
        if response.HasField('data'):
            print(f"Received message: Key={response.data.key.decode()}, Value={response.data.value.decode()}")
        elif response.HasField('ctrl'):
            print(f"Control message: {response.ctrl}")

# Usage example
namespace = "my_namespace"
topic_name = "my_topic"

# Create a topic
create_topic(namespace, topic_name, partition_count=1)

# Publish messages
messages = [
    {"key": "key1", "value": "value1"},
    {"key": "key2", "value": "value2"},
    {"key": "key3", "value": "value3"}
]
publish_messages(namespace, topic_name, messages)

# Consume messages
consume_messages(namespace, topic_name)
```

Successfully created topic:
```
Topic created: broker_partition_assignments {
  partition {
    ring_size: 2520
    range_stop: 2520
    unix_time_ns: 1723230003674188677
  }
  leader_broker: "10.0.0.4:17777"
}
```

`/etc/topics/my_namespace/my_topic/topic.conf`:
```
{
  "brokerPartitionAssignments": [
    {
      "partition": {
        "ringSize": 2520,
        "rangeStart": 0,
        "rangeStop": 2520,
        "unixTimeNs": "1723223889268598591"
      },
      "leaderBroker": "10.0.0.4:17777",
      "followerBrokers": []
    }
  ],
  "recordType": null
}
```

Error on pub/sub:
```
_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-08-09T19:00:03.689066439+00:00", grpc_status:14, grpc_message:"Socket closed"}"
>
```

**System Setup**
- OS version: Ubuntu 22.04
- weed version: "chrislusf/seaweedfs:3.71"
- python version: 3.11

**Expected behavior**
Being able to pub/sub messages via broker.

**Screenshots**
Successfully created topic:
![image](https://github.com/user-attachments/assets/9a284599-ebd4-4eeb-a4cb-b074ecca97fc)

**Additional context**
I'm aware message brokers are WIP, but here's an example of how to use them with python. Unfortunately, only topic creation works for now.

**Comment by chrislusf** [comment]
Amazing you can figure out so much already by yourself!

> partition=mq_pb2.Partition(ring_size=1, range_start=0, range_stop=1)

I am not that familiar with python and not sure how to run the code here. Try to change to `partition=mq_pb2.Partition(ring_size= 2520, range_start=0, range_stop= 2520)`

**Comment by Material-Scientist** [comment]
Changed to 2520, and get a slightly different error from broker process crashing:
```
I0810 20:26:19.744046 broker_topic_conf_read_write.go:35 load conf for topic my_namespace.my_topic from filer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x195d82a]

goroutine 306 [running]:
github.com/seaweedfs/seaweedfs/weed/mq/topic.(*LocalPartition).MaybeConnectToFollowers(0xc00076a900?, 0xc0003a4f30?, {0x2c7e720?, 0xc000a06e18?})
        /github/workspace/weed/mq/topic/local_partition.go:137 +0x2a
github.com/seaweedfs/seaweedfs/weed/mq/broker.(*MessageQueueBroker).PublishMessage(0xc00076a900, {0x2caa558, 0xc000a00520})
        /github/workspace/weed/mq/broker/broker_grpc_pub.go:66 +0x353
github.com/seaweedfs/seaweedfs/weed/pb/mq_pb._SeaweedMessaging_PublishMessage_Handler({0x243c520?, 0xc00076a900}, {0x2ca2728, 0xc000878000})
        /github/workspace/weed/pb/mq_pb/mq_grpc.pb.go:579 +0xd8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000052200, {0x2c9c478, 0xc0008d70e0}, {0x2cac380, 0xc00096c480}, 0xc000a04fc0, 0xc0005793b0, 0x407f760, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.64.1/server.go:1673 +0x1208
google.golang.org/grpc.(*Server).handleStream(0xc000052200, {0x2cac380, 0xc00096c480}, 0xc000a04fc0)
        /go/pkg/mod/google.golang.org/grpc@v1.64.1/server.go:1794 +0xe3a
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /go/pkg/mod/google.golang.org/grpc@v1.64.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 157
        /go/pkg/mod/google.golang.org/grpc@v1.64.1/server.go:1040 +0x125
```

Do you have an example of producing & subscribing to broker messages in `go`? The only thing I found was a [repo from 4 years ago](https://github.com/seaweedfs/messaging-client-go) that seems to be out of date by now.

**Comment by chrislusf** [comment]
https://github.com/seaweedfs/seaweedfs/tree/master/weed/mq/client/cmd

there are 2 versions: key-value messages and typed messages.

**Comment by Material-Scientist** [comment]
Sorry, I can't figure out how to use these. Could you please give an example on how to publish a message? Does it work via `weed ...` in the CLI?

**Comment by chrislusf** [comment]
@Material-Scientist The message queue feature is merged. You may want to check it out and let me know your feedback?

https://github.com/seaweedfs/seaweedfs/wiki/Seaweed-Message-Queue
