### ISSUE TITLE
SIGSEV in weed export while listing file

### ISSUE THREAD

**Issue by aagrxyz** [seaweedfs/seaweedfs#5971]
**Describe the bug**

Running weed export on any volume causes a SIGSEV

```
weed export -dir=/mnt/disk0 -volumeId=1 -fileNameFormat={{.Name}}
key	name	size	gzip	mime	modified	ttl	deleted	start	stop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb0806c]

goroutine 1 [running]:
os.(*File).Name(...)
	/usr/local/go/src/os/file.go:56
github.com/seaweedfs/seaweedfs/weed/storage/backend.NewDiskFile(0x0)
	/github/workspace/weed/storage/backend/disk_file.go:27 +0x4c
github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).load(0xc0001da3c0, 0x0, 0x0, 0x0, 0x0)
	/github/workspace/weed/storage/volume_loading.go:69 +0x325
github.com/seaweedfs/seaweedfs/weed/storage.loadVolumeWithoutIndex({0x7ffeb373d6be, 0xa}, {0x0, 0x0}, 0x1, 0x0)
	/github/workspace/weed/storage/volume_loading.go:23 +0xb7
github.com/seaweedfs/seaweedfs/weed/storage.ScanVolumeFile({0x7ffeb373d6be?, 0xa?}, {0x0?, 0x38?}, 0x1, 0x0?, {0x2c000b0, 0xc000a92000})
	/github/workspace/weed/storage/volume_read.go:214 +0x5b
github.com/seaweedfs/seaweedfs/weed/command.runExport(0x3f92418?, {0xc0000500c0?, 0x3?, 0x3?})
	/github/workspace/weed/command/export.go:216 +0xa95
main.main()
	/github/workspace/weed/weed.go:95 +0x3d9

```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version: 
```
$ uname -a
Linux  5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
- output of `weed version` - `version 30GB 3.69 ac6fd36c06f9cd6740cb2ff7e97c1ba92d55bf2c linux amd64`
- if using filer, show the content of `filer.toml`
```
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = true
#max_file_name_length = 255

####################################################
# The following are filer store options
####################################################

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = true
dir = "/mnt/ssd/seaweedfs/filer/filerldb2"                    # directory to store level db files
```

**Expected behavior**

As per https://github.com/seaweedfs/seaweedfs/issues/19 and the `weed export` command, I would expect to get the list of files

**Screenshots**

**Additional context**

**Comment by aagrxyz** [comment]
Nvm, I figured out it was a permission issue -> running weed export as root fixes the issue.

I still do not see names of the files. I am seeing just the chunks of the files. For example here is the output

```
weed export -dir=/mnt/disk0 -fileNameFormat={{.Name}} -volumeId=1
key	name	size	gzip	mime	modified	ttl	deleted	start	stop
I0904 00:46:14.397886 volume_loading.go:91 readSuperBlock volume 1 version 3
1,03cd5c4cb8		1156	false		2024-04-07T16:32:40		false	8	1208
1,012caa8ace38		61120	false		2024-04-07T17:08:12		false	1208	62376
1,015099ab9aa2		72582	false		2024-04-07T17:18:12		false	62376	135000
1,0284f8b97a1b		404403	false		2024-04-07T17:27:47		false	135000	539448
1,1aa1697b27d8		35645	false		2024-04-07T17:47:08		false	539448	575136
1,da5c9384462b		394726	false		2024-04-07T18:10:15		false	575136	969904
1,012b011a0507cb		2374305	false		2024-04-07T18:20:15		false	969904	3344256
1,014d638d4cb5a3		488020	false		2024-04-07T18:24:15		false	3344256	3832320
1,017c9f35620408		1934787	false		2024-04-07T18:29:15		false	3832320	5767152
1,0184790842d06b		1008652	false		2024-04-07T18:30:15		false	5767152	6775848
1,01e8bb6bb8cb4f		977114	false		2024-04-07T18:41:15		false	6775848	7753008
1,0227018f3b7f0e		802464	false		2024-04-07T18:47:15		false	7753008	8555520
1,9e18933753b985		1759560	false		2024-09-02T00:51:11		false	8555520	10315128
```

Is it possible to find out the files these chunks are part of?

**Comment by chrislusf** [comment]
depending on how the chunk was uploaded, the file name does not always exist.

**Comment by aagrxyz** [comment]
All of the files were uploaded as a part of the FUSE mount -> so is it possible to inspect the filer metadata/database to find the file a chunk belongs to?

**Comment by chrislusf** [comment]
I thought you lost the filer metadata

**Comment by aagrxyz** [comment]
No, I am trying to understand what data is present in some volumes. I do
have the filer metadata. I recently added collection names for different
directories using fs.configure and migrated all the data to the new paths.
There are still some volumes remaining which have some size and I can't
figure out what data is present in those volumes.
