### ISSUE TITLE
3.73 fuse mount read panic

### ISSUE THREAD

**Issue by half-life666** [seaweedfs/seaweedfs#6020]
**Describe the bug**
setup a fuse mount with no cache size, write a file and read will hit panic, recreate is easy:
1. Create a new fuse mount
2. Write a file to fuse mount
3. Drop the cache
4. Copy the file out

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xfe2a40]

goroutine 120 [running]:
github.com/seaweedfs/seaweedfs/weed/util/chunk_cache.(*TieredChunkCache).GetMaxFilePartSizeInCache(0x45835e?)
        /seaweedfs/weed/util/chunk_cache/chunk_cache.go:51
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).readChunkSliceAt(0xc000a4ff00, {0xc001bc2000, 0x40000, 0x40000}, 0xc0080a44e0, 0xc0005716b0, 0x0)
        /seaweedfs/weed/filer/reader_at.go:202 +0xff
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).doReadAt(0xc000a4ff00, {0xc001bc2000, 0x40000, 0x40000}, 0x0)
        /seaweedfs/weed/filer/reader_at.go:157 +0x305
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkReadAt).ReadAtWithTime(0xc001b80720?, {0xc001bc2000?, 0xf4240000?, 0x23e?}, 0x2118ce0?)
        /seaweedfs/weed/filer/reader_at.go:125 +0x11f
github.com/seaweedfs/seaweedfs/weed/filer.(*FileChunkSection).readDataAt(0xc001b80720, 0xc000571170?, 0x0?, {0xc001bc2000, 0x40000, 0x40000}, 0x0)
        /seaweedfs/weed/filer/filechunk_section.go:104 +0xe5
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkGroup).ReadDataAt(0xc000571140, 0xf4240000, {0xc001bc2000, 0x40000, 0x40000}, 0x0)
        /seaweedfs/weed/filer/filechunk_group.go:63 +0x268
github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).readFromChunks(0xc006cb4700, {0xc001bc2000, 0x40000, 0x40000}, 0x0)
        /seaweedfs/weed/mount/filehandle_read.go:58 +0x545
github.com/seaweedfs/seaweedfs/weed/mount.readDataByFileHandle({0xc001bc2000, 0x40000, 0x40000}, 0xc006cb4700, 0x0)
        /seaweedfs/weed/mount/weedfs_file_read.go:81 +0xf2
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).Read(0x0?, 0xc00dee4248?, 0xc00dee43e0, {0xc001bc2000, 0x40000, 0x40000})
        /seaweedfs/weed/mount/weedfs_file_read.go:49 +0x14e
github.com/hanwen/go-fuse/v2/fuse.doRead(0xc0005ae680, 0xc00dee4248)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/opcode.go:398 +0x7c
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0005ae680, 0xc00dee4248)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:527 +0x2f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0005ae680, 0x1)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:500 +0x118
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest in goroutine 1
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:367 +0x54c

```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
/usr/bin/weed -logtostderr=true master -mdir=/data -ip=xxx -volumePreallocate=false -volumeSizeLimitMB=4096 -defaultReplication=000
/usr/bin/weed -logtostderr=true volume -dir=/data -dir=/mnt/weed1 -mserver=localhost:9333 -max=0 -port=8080 -metricsPort=9325 -preStopSeconds=1
/usr/bin/weed -logtostderr=true volume -dir=/data -dir=/mnt/weed2 -mserver=localhost:9333 -max=0 -port=8081 -metricsPort=9326 -preStopSeconds=1
/usr/bin/weed -logdir=/var/log/udm filer -defaultReplicaPlacement=000 -master=localhost:9333 -metricsPort=9328 -maxMB=128
weed -v=4 mount -filer=localhost:8888 -dir=/opt/udm/fs1 -cacheCapacityMB=0 -concurrentWriters=8 -filer.path=/opt/udm/fs1 -collection=user1 -chunkSizeLimitMB=8
```

- OS version

- output of `weed version`
 version 30GB 3.72 linux amd64

- if using filer, show the content of `filer.toml`

**Expected behavior**

**Screenshots**

**Additional context**

```go
	if option.CacheSizeMBForRead > 0 {
		wfs.chunkCache = chunk_cache.NewTieredChunkCache(256, option.getUniqueCacheDirForRead(), option.CacheSizeMBForRead, 1024*1024)
	}
```

since CacheSizeMBForRead is 0, chunkCache is not initialized, the last change at https://github.com/seaweedfs/seaweedfs/pull/6009 breaks the read.

**Comment by half-life666** [comment]
attempted a fix in https://github.com/seaweedfs/seaweedfs/pull/6021
