### ISSUE TITLE
[Mount] Unable to start mount

### ISSUE THREAD

**Issue by Dando-Real-ITA** [seaweedfs/seaweedfs#6034]
**Describe the bug**
I just updated to commit 2b13d2c083a8cf2e1efc616e3301ce590c78cf11 and mount refuses to start anymore.
This is the error: 
```
I0917 11:11:23.922805 needle_map_leveldb.go:67 Loading /mnt/seaweedfs/.docker/cloud_edge/48101edc/c2_2_1.ldb... , watermark: 0
I0917 11:11:23.923168 leveldb_store.go:47 filer store dir: /mnt/seaweedfs/.docker/cloud_edge/48101edc/meta
I0917 11:11:23.923198 file_util.go:27 Folder /mnt/seaweedfs/.docker/cloud_edge/48101edc/meta Permission: -rwxr-xr-x
I0917 11:11:23.931053 wfs_filer_client.go:31 WithFilerClient 0 vpn.katapy.icu:18888: filer: no entry is found in filer store
I0917 11:11:23.942884 wfs_filer_client.go:31 WithFilerClient 1 lh1.vpn.katapy.icu:18888: filer: no entry is found in filer store
failed to start background tasks: filer: no entry is found in filer store
```
My guess is it is related to the new WORM patch which added:
https://github.com/seaweedfs/seaweedfs/blob/2b13d2c083a8cf2e1efc616e3301ce590c78cf11/weed/mount/weedfs.go#L144
```
fn, err := wfs.subscribeFilerConfEvents()
if err != nil {
	return err
}

go fn()
```

The **remote** filer has data ( tested connecting with shell ) but the **local** filer store used for cache, that is created new, is empty with version change on a new folder, has no data and I think this causes the mount to crash.

**System Setup**
Commit 2b13d2c083a8cf2e1efc616e3301ce590c78cf11 

**Expected behavior**
Weed should run normally as before

**Additional context**
I am going to locally test removing the return error that is causing in my opinion the mount to not work anymore

**Comment by Dando-Real-ITA** [comment]
Ok even worse after bypassing the error, now it crashes with trying to read rules:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21c5301]
goroutine 285 [running]:
github.com/seaweedfs/seaweedfs/weed/filer.(*FilerConf).MatchStorageRule(0x0, {0xc0008fa120, 0x23})
        /home/gaspare/Documents/code/go/seaweedfs/weed/filer/filer_conf.go:156 +0xc1
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).wormEnabledForEntry(0xc000b55340?, {0x
```
Seems that a file is expected to be inside filter which was not required before and should not be necessary.

**Comment by Dando-Real-ITA** [comment]
I solved in my local branch by not executing `wormEnabledForEntry` if `wfs.FilerConf` is `nil`. It is a workaround, proper way would be to load the conf from filer.toml remotely
