### ISSUE TITLE
使用filer时，会出现文件找不到，但是本地挂载目录中是有这个文件

### ISSUE THREAD

**Issue by god12311** [seaweedfs/seaweedfs#6047]
场景：
使用seaweedfs的filer功能进行文件系统共享挂载，会有四个节点同时挂载这个目录进行读写操作；元数据使用的是redis cluster

现象：
本地挂载目录中有文件，但是访问的时候找不到 no such file or directory

具体报错,这只是其中的一部分日志，这种报错量比较多：
E0918 16:52:41.951476 weedfs_dir_read.go:221 dir ReadDirAll /npm/test1/xxx/node_modules/.staging/core-js-5b3b93f1/features/url-search-params: list /npm/test1/xxx/node_modules/.stagin
g/core-js-5b3b93f1/features/url-search-params: persisting /npm/test1/xxx/node_modules/.staging/core-js-5b3b93f1/features/url-search-params/index.js : open /tmp/91ac9b75/meta/016485.sst: no such file or d
irectory

F0918 18:00:34.378136 filer_pb_tail.go:92 process directory:"/npm/test2/xxx/node_modules/es-abstract/2024" event_notification:{old_entry:{name:"NewPromiseCapability.js" attributes:{mtime:1726653
634 file_mode:420 crtime:1726653634 inode:8946670770529276835}} new_entry:{name:"NewPromiseCapability.js" chunks:{size:1228 modified_ts_ns:1726653634372713376 e_tag:"z7S+GTTpFpQ3MNecL/ZXKQ==" fid:{volume_id:2 file_key:234784
73 cookie:821192230} is_compressed:true} attributes:{file_size:1228 mtime:1726653634 file_mode:420 crtime:1726653634 mime:"text/plain; charset=utf-8" inode:8946670770529276835}} delete_chunks:true new_parent_path:"/npm/test2
/xxx/node_modules/es-abstract/2024" signatures:-1094824416 signatures:-1142722667} ts_ns:1726653634381283990: persisting /npm/test2/xxx/node_modules/es-abstract/202
4/NewPromiseCapability.js : open /tmp/91ac9b75/meta/016485.sst: no such file or directory
goroutine 121 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x1)
        /github/workspace/weed/glog/glog.go:768 +0x85
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x7333520, 0x3, 0xc04400f880, {0x58fc244?, 0xc144f5d980?}, 0x2?, 0x0)
        /github/workspace/weed/glog/glog.go:722 +0x3af
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0x7333520, 0x3, {0x4439361, 0xe}, {0xc144f5d980, 0x2, 0x2})
        /github/workspace/weed/glog/glog.go:657 +0x10a
github.com/seaweedfs/seaweedfs/weed/glog.Fatalf({0x4439361?, 0x4c190b0?}, {0xc144f5d980?, 0xc0008be780?, 0x0?})
        /github/workspace/weed/glog/glog.go:1154 +0x38
github.com/seaweedfs/seaweedfs/weed/pb.WithFilerClientFollowMetadata.makeSubscribeMetadataFunc.func1({0x4c59b60, 0xc0e7c81800})
        /github/workspace/weed/pb/filer_pb_tail.go:92 +0x42e
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1.1(0xc005d36008)
        /github/workspace/weed/mount/wfs_filer_client.go:27 +0x68
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcClient(0xdc?, 0x9205d0ac?, 0xc000a81cd0, {0xc10d7942b8, 0x13}, 0x0?, {0xc000a81cc0?, 0x1?, 0x1?})
        /github/workspace/weed/pb/grpc_client_server.go:155 +0x33a
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1()
        /github/workspace/weed/mount/wfs_filer_client.go:25 +0x14c
github.com/seaweedfs/seaweedfs/weed/util.Retry({0x4429aa2, 0xa}, 0xc00628dde8)
        /github/workspace/weed/util/retry.go:16 +0xa7
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient(0x7f254cec0008?, 0x90?, 0xc0009fae48?)
        /github/workspace/weed/mount/wfs_filer_client.go:18 +0x65
github.com/seaweedfs/seaweedfs/weed/pb.WithFilerClientFollowMetadata({0x4c067c8, 0xc000231760}, 0xc00171c000, 0xc000546420)
        /github/workspace/weed/pb/filer_pb_tail.go:51 +0x87
github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.SubscribeMetaEvents.func2()
        /github/workspace/weed/mount/meta_cache/meta_cache_subscribe.go:80 +0x26
github.com/seaweedfs/seaweedfs/weed/util.RetryUntil({0x44474d6, 0x11}, 0xc00628df60, 0x4674590)
        /github/workspace/weed/util/retry.go:64 +0x4e
github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.SubscribeMetaEvents(0xc000d98480, 0x9205d0ac, {0x4c067c8, 0xc000231760}, {0x4bb63f8, 0x1}, 0x17f1740fe81f8d7a)
        /github/workspace/weed/mount/meta_cache/meta_cache_subscribe.go:78 +0x1e5
created by github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).StartBackgroundTasks in goroutine 1
        /github/workspace/weed/mount/weedfs.go:143 +0x11d

挂载命令：
/usr/local/bin/weed  mount -filer=xxx:8888,xxx:8888  -dir=/data -cacheCapacityMB=10240

请问这个问题是什么原因造成的，会是元数据丢失吗？出现问题时只是部分文件有问题

**Comment by chrislusf** [comment]
configure the cache directory outside of the `/tmp` folder

**Comment by god12311** [comment]
是挂载的时候吗，比如像下面这样？
/usr/local/bin/weed mount -filer=xxx:8888,xxx:8888 -dir=/data -cacheCapacityMB=10240 -cacheDirWrite=/data/swdfs-cache

那这个的具体原因是什么？/tmp下临时文件被删除导致？还有如果要修复这些找不到的文件应该怎么操作呢？

**Comment by god12311** [comment]
是挂载的时候吗，比如像下面这样？
/usr/local/bin/weed mount -filer=xxx:8888,xxx:8888 -dir=/data -cacheCapacityMB=10240 -cacheDir=/data/swdfs-cache 

那这个的具体原因是什么？/tmp下临时文件被删除导致？还有如果要修复这些找不到的文件应该怎么操作呢？

**Comment by god12311** [comment]
> configure the cache directory outside of the `/tmp` folder

并且这个配置也不会导致文件找不到吧，只是提高文件访问速度；因为我没有配置 -cacheDirWrite
