### ISSUE TITLE
master raft panic

### ISSUE THREAD

**Issue by neo-v** [seaweedfs/seaweedfs#6070]
**Describe the bug**
Raft panic if a master takes snapshot simultaneously
The pendingSnapshot will be set to nil when a thread call save snapshot while another thread is manipulating it.

it may need a server lock.

**Screenshots**
![image](https://github.com/user-attachments/assets/7f7303d0-161f-4e70-9c5a-ee24090b8990)

**Additional context**
can I push a pr to raft  repo?
@chrislusf

**Comment by neo-v** [comment]
![image](https://github.com/user-attachments/assets/5cfb5ea2-7757-47df-aaf3-4ee83062134c)

**Comment by zouyixiong** [comment]
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1b7592b]
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]: goroutine 556003269 [running]:
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]: github.com/seaweedfs/raft.(*server).TakeSnapshot(0xc0004e9680)
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]:         /home/xyz/go/pkg/mod/github.com/seaweedfs/raft@v1.1.3/server.go:1268 +0x46b
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]: github.com/seaweedfs/raft.(*server).maybeTakeSnapshot.func1()
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]:         /home/xyz/go/pkg/mod/github.com/seaweedfs/raft@v1.1.3/server.go:1221 +0x55
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]: created by github.com/seaweedfs/raft.(*server).maybeTakeSnapshot in goroutine 131
Mar 24 21:41:42 gz-cs-2-127 seaweedfs-master[131220]:         /home/xyz/go/pkg/mod/github.com/seaweedfs/raft@v1.1.3/server.go:1219 +0x8e
Mar 24 21:41:42 gz-cs-2-127 systemd[1]: weed-master.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 24 21:41:42 gz-cs-2-127 systemd[1]: weed-master.service: Failed with result 'exit-code'.
Mar 24 21:41:42 gz-cs-2-127 systemd[1]: weed-master.service: Consumed 3w 3d 45min 3.237s CPU time.



weed version
version 30GB 3.85  linux amd64

run in the some issue in 3.85.
