### ISSUE TITLE
When rsync or copy most file to FUSE mount path, weed mount panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lvxuan263** [seaweedfs/seaweedfs#6110]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

**Describe the bug**
weed mount logs:
```log
mount point owner uid=0 gid=0 mode=drwxr-xr-x
current uid=0 gid=0
I1010 08:06:38.959473 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c0_2_0.ldb, watermark 0, num of entries:0
I1010 08:06:39.054707 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c0_2_0.ldb... , watermark: 0
I1010 08:06:39.160140 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c0_2_1.ldb, watermark 0, num of entries:0
I1010 08:06:39.196654 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c0_2_1.ldb... , watermark: 0
I1010 08:06:39.229696 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c1_3_0.ldb, watermark 0, num of entries:0
I1010 08:06:39.258201 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c1_3_0.ldb... , watermark: 0
I1010 08:06:39.289252 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c1_3_1.ldb, watermark 0, num of entries:0
I1010 08:06:39.319486 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c1_3_1.ldb... , watermark: 0
I1010 08:06:39.352508 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c1_3_2.ldb, watermark 0, num of entries:0
I1010 08:06:39.389969 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c1_3_2.ldb... , watermark: 0
I1010 08:06:39.429399 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c2_2_0.ldb, watermark 0, num of entries:0
I1010 08:06:39.478548 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c2_2_0.ldb... , watermark: 0
I1010 08:06:39.537395 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c2_2_1.ldb, watermark 0, num of entries:0
I1010 08:06:39.575861 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c2_2_1.ldb... , watermark: 0
I1010 08:06:39.576084 leveldb_store.go:47 filer store dir: /tmp/7a37eab9/meta
I1010 08:06:39.576112 file_util.go:27 Folder /tmp/7a37eab9/meta Permission: -rwxr-xr-x
I1010 08:06:39.602877 wfs_filer_client.go:31 WithFilerClient 0 10.56.122.2:19335: filer: no entry is found in filer store
I1010 08:06:39.602895 filer_conf.go:39 fuse filer conf /etc/seaweedfs/filer.conf not found
I1010 08:06:39.602916 mount_std.go:280 mounted 10.56.122.2:9335/ to /mnt/data
I1010 08:06:39.602929 mount_std.go:281 This is SeaweedFS version 30GB 3.76 82ed61c65 linux amd64
I1010 08:09:03.527993 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c0_2_0.ldb, watermark 0, num of entries:0
I1010 08:09:03.567980 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c0_2_0.ldb... , watermark: 0
I1010 08:09:03.973302 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c0_2_1.ldb, watermark 0, num of entries:0
I1010 08:09:04.006265 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c0_2_1.ldb... , watermark: 0
I1010 08:09:04.389964 needle_map_leveldb.go:122 generateLevelDbFile /tmp/7a37eab9/c0_2_0.ldb, watermark 0, num of entries:0
I1010 08:09:04.424709 needle_map_leveldb.go:66 Loading /tmp/7a37eab9/c0_2_0.ldb... , watermark: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1dc5f41]

goroutine 203 [running]:
github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.SubscribeMetaEvents.func2.mergeProceesors.1(0xc0006391d0)
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/meta_cache/meta_cache_subscribe.go:30 +0x41
github.com/seaweedfs/seaweedfs/weed/pb.WithFilerClientFollowMetadata.makeSubscribeMetadataFunc.func1({0x2d3dac0, 0xc00061c760})
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb_tail.go:87 +0x293
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1.1(0xc0006b1c08)
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/wfs_filer_client.go:27 +0x68
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcClient(0x23?, 0x234ab7ec?, 0xc000525be0, {0xc000054288, 0x11}, 0x0?, {0xc0002f0bd0?, 0x1?, 0x1?})
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:155 +0x343
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1()
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/wfs_filer_client.go:25 +0x155
github.com/seaweedfs/seaweedfs/weed/util.Retry({0x250ecc9, 0xa}, 0xc000525cf8)
	/go/src/github.com/seaweedfs/seaweedfs/weed/util/retry.go:16 +0xa7
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient(0x0?, 0x20?, 0xc000839568?)
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/wfs_filer_client.go:18 +0x65
github.com/seaweedfs/seaweedfs/weed/pb.WithFilerClientFollowMetadata({0x2d16288, 0xc0008b5080}, 0xc0008e2000, 0xc00053b920)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb_tail.go:51 +0x87
github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.SubscribeMetaEvents.func2()
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/meta_cache/meta_cache_subscribe.go:115 +0xcb
github.com/seaweedfs/seaweedfs/weed/util.RetryUntil({0x251f1cf, 0x11}, 0xc000525ef0, 0x2660698)
	/go/src/github.com/seaweedfs/seaweedfs/weed/util/retry.go:64 +0x4e
github.com/seaweedfs/seaweedfs/weed/mount/meta_cache.SubscribeMetaEvents(0xc0008e42a0, 0x234ab7ec, {0x2d16288, 0xc0008b5080}, {0x2ceca60, 0x1}, 0x17fd08e233af5972, {0xc00011a318, 0x1, 0x1})
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/meta_cache/meta_cache_subscribe.go:113 +0x39a
created by github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).StartBackgroundTasks in goroutine 1
	/go/src/github.com/seaweedfs/seaweedfs/weed/mount/weedfs.go:150 +0x146
```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
Using default parameter of master/volume/filer/mount service.
weed mount -filer="10.56.xx.xx:9335" -dir=/mnt/data -volumeServerAccess=publicUrl -dirAutoCreate=true'

- OS version: ubuntu 20.04
- output of `weed version`: chrislusf/seaweedfs:3.76
-  the content of `filer.toml`
```
[leveldb2]
enabled = true
dir = "/data/seaweedfs/filer"
```

**Comment by chrislusf** [comment]
please use this commit https://github.com/seaweedfs/seaweedfs/commit/07df5c53deca5d92382cd1c0fa967bde4f855811

**Comment by lvxuan263** [comment]
thanks~ i will try.
