### ISSUE TITLE
weed mount error transport endpoint is not connected

### ISSUE THREAD

**Issue by vvilli** [seaweedfs/seaweedfs#6129]
### Discussed in https://github.com/seaweedfs/seaweedfs/discussions/5546

<div type='discussions-op-text'>

<sup>Originally posted by **CKHH** April 29, 2024</sup>
Hi,

We are using `weed mount` to 6 filer servers. Sometimes we get error: `Transport endpoint is not connected` and had to restart the `weed mount`. What could cause the error? Thanks.

From the logs:
```
Apr 25 08:41:05 sftp02u weed[1318154]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 25 08:41:05 sftp02u weed[1318154]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1b12338]
Apr 25 08:41:05 sftp02u weed[1318154]: goroutine 2095550 [running]:
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/filer.FromPbEntry({0xc0029dfab0, 0x41}, 0x0)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/filer/entry.go:132 +0x38
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).downloadRemoteEntry.func1({0x38b0390, 0xc00df28ce0})
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/mount/filehandle_read.go:93 +0x1c5
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1.1(0xc00959d800)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/mount/wfs_filer_client.go:27 +0x6f
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcClient(0xb1?, 0x7fff?, 0xc001d73910, {0xc0074709a8, 0x13}, 0x20?, {0xc0026cb900?, 0x3?, 0x2?})
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:129 +0x4ed
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1()
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/mount/wfs_filer_client.go:25 +0x165
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/util.Retry({0x30e16d2, 0xa}, 0xc001d73a20)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/util/retry.go:16 +0xb1
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).WithFilerClient(0xc0029dfab0?, 0x60?, 0x7fc51b8ed5b8?)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/mount/wfs_filer_client.go:18 +0x66
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).downloadRemoteEntry(0xc005cfa140, 0x0)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/mount/filehandle_read.go:78 +0xaf
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).readFromChunks(0xc005cfa140, {0xc0095b5000, 0x1000, 0x1000}, 0x0)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/mount/filehandle_read.go:38 +0x1e5
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/mount.readDataByFileHandle({0xc0095b5000, 0x1000, 0x1000}, 0xc005cfa140, 0x0)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/mount/weedfs_file_read.go:80 +0x105
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).Read(0x47bd85?, 0xc0003d4900?, 0xc0003d4a98, {0xc0095b5000, 0x1000, 0x1000})
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/src/github.com/seaweedfs/seaweedfs/weed/mount/weedfs_file_read.go:48 +0x125
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/hanwen/go-fuse/v2/fuse.doRead(0xc0009c6580, 0xc0003d4900)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.3.0/fuse/opcode.go:392 +0x83
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0009c6580, 0xc0003d4900)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.3.0/fuse/server.go:518 +0x1f3
Apr 25 08:41:05 sftp02u weed[1318154]: github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0009c6580, 0x0?)
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.3.0/fuse/server.go:491 +0x108
Apr 25 08:41:05 sftp02u weed[1318154]: created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
Apr 25 08:41:05 sftp02u weed[1318154]:         /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.3.0/fuse/server.go:358 +0x545
Apr 25 08:41:06 sftp02u systemd[1]: seaweedfs-fi-report-mount.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 25 08:41:06 sftp02u systemd[1]: seaweedfs-fi-report-mount.service: Failed with result 'exit-code'.
```
</div>

**Comment by epotyomkin** [comment]
Same issue


```
Oct 15 11:04:37 srv-prod-n2 weed: E1015 11:04:37.961714 page_chunk_swapfile.go:55 create swap file: open /tmp/0d33f874/swap/2721469488: no such file or directory
Oct 15 11:04:37 srv-prod-n2 weed: panic: runtime error: invalid memory address or nil pointer dereference
Oct 15 11:04:37 srv-prod-n2 weed: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cf57e2]
Oct 15 11:04:37 srv-prod-n2 weed: goroutine 14941 [running]:
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount/page_writer.(*SwapFileChunk).WriteDataAt(0x0, {0xc00c869200, 0x9000, 0xe9080}, 0x4000000, 0x17fe91acb7d82
d29)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/page_writer/page_chunk_swapfile.go:100 +0x62
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount/page_writer.(*UploadPipeline).SaveDataAt(0xc001b98310, {0xc00c869200, 0x9000, 0xe9080}, 0x4000000, 0x1, 0
x17fe91acb7d82d29)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/page_writer/upload_pipeline.go:115 +0x1f4
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount.(*ChunkedDirtyPages).AddPage(0xc0061d1200, 0x4000000, {0xc00c869200, 0x9000, 0xe9080}, 0x1, 0x17fe91acb7d
82d29)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/dirty_pages_chunked.go:45 +0x153
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount.(*PageWriter).addToOneChunk(...)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/page_writer.go:46
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount.(*PageWriter).AddPage(0xc00260aa00, 0x3fe9000, {0xc00c852200, 0x20000, 0x100080}, 0x1, 0x17fe91acb7d82d29
)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/page_writer.go:39 +0x21d
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).Write(0x473c26?, 0xc002c4dc00?, 0xc00c8521b0, {0xc00c852200, 0x20000, 0x100080})
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/weedfs_file_write.go:65 +0x25e
Oct 15 11:04:37 srv-prod-n2 weed: github.com/hanwen/go-fuse/v2/fuse.doWrite(0x1a00000038?, 0xc002011688)
Oct 15 11:04:37 srv-prod-n2 weed: /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/opcode.go:224 +0x3b
Oct 15 11:04:37 srv-prod-n2 weed: github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0005e0680, 0xc002011688)
Oct 15 11:04:37 srv-prod-n2 weed: /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:527 +0x2f3
Oct 15 11:04:37 srv-prod-n2 weed: github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0005e0680, 0x1)
Oct 15 11:04:37 srv-prod-n2 weed: /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:500 +0x118
Oct 15 11:04:37 srv-prod-n2 weed: created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest in goroutine 180
Oct 15 11:04:37 srv-prod-n2 weed: /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:367 +0x54c
Oct 15 11:04:38 srv-prod-n2 systemd: sfs-mount-robot.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 15 11:04:38 srv-prod-n2 nlp_gw_int/edfc3eee6679: ERROR gw.gateway 15.10 11:04:38.045 [None] Unexpected error <class 'OSError'>. Exception arguments [Errno 107] Transport endpoin
t is not connected
```

**Comment by chrislusf** [comment]
Please follow issue template.

**Comment by epotyomkin** [comment]
open new issue #6143
