### ISSUE TITLE
Crash with error "Transport endpoint is not connected"

### ISSUE THREAD

**Issue by epotyomkin** [seaweedfs/seaweedfs#6143]
**Describe the bug**
The FS folder is mounted inside the docker container, sometimes it crashes with error "Transport endpoint is not connected" and we have to restart it to restore the service.

```
Oct 15 11:04:37 srv-prod-n2 weed: E1015 11:04:37.961714 page_chunk_swapfile.go:55 create swap file: open /tmp/0d33f874/swap/2721469488: no such file or directory
Oct 15 11:04:37 srv-prod-n2 weed: panic: runtime error: invalid memory address or nil pointer dereference
Oct 15 11:04:37 srv-prod-n2 weed: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cf57e2]
Oct 15 11:04:37 srv-prod-n2 weed: goroutine 14941 [running]:
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount/page_writer.(*SwapFileChunk).WriteDataAt(0x0, {0xc00c869200, 0x9000, 0xe9080}, 0x4000000, 0x17fe91acb7d82
d29)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/page_writer/page_chunk_swapfile.go:100 +0x62
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount/page_writer.(*UploadPipeline).SaveDataAt(0xc001b98310, {0xc00c869200, 0x9000, 0xe9080}, 0x4000000, 0x1, 0
x17fe91acb7d82d29)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/page_writer/upload_pipeline.go:115 +0x1f4
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount.(*ChunkedDirtyPages).AddPage(0xc0061d1200, 0x4000000, {0xc00c869200, 0x9000, 0xe9080}, 0x1, 0x17fe91acb7d
82d29)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/dirty_pages_chunked.go:45 +0x153
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount.(*PageWriter).addToOneChunk(...)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/page_writer.go:46
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount.(*PageWriter).AddPage(0xc00260aa00, 0x3fe9000, {0xc00c852200, 0x20000, 0x100080}, 0x1, 0x17fe91acb7d82d29
)
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/page_writer.go:39 +0x21d
Oct 15 11:04:37 srv-prod-n2 weed: github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).Write(0x473c26?, 0xc002c4dc00?, 0xc00c8521b0, {0xc00c852200, 0x20000, 0x100080})
Oct 15 11:04:37 srv-prod-n2 weed: /github/workspace/weed/mount/weedfs_file_write.go:65 +0x25e
Oct 15 11:04:37 srv-prod-n2 weed: github.com/hanwen/go-fuse/v2/fuse.doWrite(0x1a00000038?, 0xc002011688)
Oct 15 11:04:37 srv-prod-n2 weed: /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/opcode.go:224 +0x3b
Oct 15 11:04:37 srv-prod-n2 weed: github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0005e0680, 0xc002011688)
Oct 15 11:04:37 srv-prod-n2 weed: /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:527 +0x2f3
Oct 15 11:04:37 srv-prod-n2 weed: github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0005e0680, 0x1)
Oct 15 11:04:37 srv-prod-n2 weed: /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:500 +0x118
Oct 15 11:04:37 srv-prod-n2 weed: created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest in goroutine 180
Oct 15 11:04:37 srv-prod-n2 weed: /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fuse/server.go:367 +0x54c
Oct 15 11:04:38 srv-prod-n2 systemd: sfs-mount-robot.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 15 11:04:38 srv-prod-n2 nlp_gw_int/edfc3eee6679: ERROR gw.gateway 15.10 11:04:38.045 [None] Unexpected error <class 'OSError'>. Exception arguments [Errno 107] Transport endpoin
t is not connected
```

Server side log

```
Oct 15 11:04:38 [localhost] weed: I1015 11:04:38.023873 filer_grpc_server_sub_meta.go:271 => client mount@2.2.2.2:40754: rpc error: code = Unavailable desc = transport is closing
Oct 15 11:04:38 [localhost] weed: E1015 11:04:38.023932 log_read.go:122 LoopProcessLogData: aggMeta:mount@2.2.2.2:40754 process log entry 1 ts_ns:1728921213646674800  partition_key_hash:-24119093  data:"\n\x15/data/dicts/400316231\x12T\x12#\n\x0557280\"\x1a\x10\xfd\xfc\xb4\xb8\x06\x18\xa4\x030\xfd\xfc\xb4\xb8\x06\x88\x01߄\x8eҗ\xbdů^\x18\x01\"\x15/data/dicts/4003162312\x14\xfe\xa3Ȋ\xfd\xff\xff\xff\xff\x01\x98\xb1<U+0771>\xfa\xff\xff\xff\xff\x01\x18<U+36C00>\xf0\x95\x97\xff\x17"  key:"/data/dicts/400316231": rpc error: code = Unavailable desc = transport is closing
Oct 15 11:04:38 [localhost] weed: E1015 11:04:38.024125 filer_grpc_server_sub_meta.go:79 processed to 2024-10-14 15:53:33.6466748 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
Oct 15 11:04:38 [localhost] weed: I1015 11:04:38.024162 filer_grpc_server_sub_meta.go:315 -  listener mount@192.168.92.6:40754 clientId 1117187479 clientEpoch 2
Oct 15 11:04:43 [localhost] weed: I1015 11:04:43.331005 filer_grpc_server_sub_meta.go:299 +  listener mount@192.168.92.6:53916 clientId 1764855246 clientEpoch 2
Oct 15 11:04:43 [localhost] weed: I1015 11:04:43.331036 filer_grpc_server_sub_meta.go:37  mount@2.2.2.2:53916 starts to subscribe / from 2024-10-15 08:04:43.330008271 +0000 UTC
```

**System Setup**

[Service]
```
EnvironmentFile=/etc/environment
ExecStart=/usr/local/bin/weed mount -nonempty -filer=1.1.1.1:8888,1.1.1.2:8888,1.1.1.3:8888 -dir=/mnt/temp_dir -cacheDir=/opt/seaweedfs-cache -localSocket=/var/run/weed-mount.sock
Restart=always
RestartSec=5s
```

**On the server side:**

weed version
version 30GB 3.68 a9cd9b0542ef9e2c795baf063d3f7db395ff209b linux amd64

```
#cat /etc/*release | tail -1
CentOS Linux release 7.9.2009 (Core)
```

We do not use filer.toml 
We run the filer /usr/local/bin/weed filer -defaultStoreDir /opt/seaweedfs/filer

**On the client side:**

```
# cat /etc/*release | head -1
CentOS Linux release 7.8.2003 (Core)
```

weed version
version 30GB 3.68 a9cd9b0542ef9e2c795baf063d3f7db395ff209b linux amd64

**Expected behavior**
SeaWeedFS and filer works without error or reconnects when an error occurs.

**Comment by valan** [comment]
I had this same issue, looks to be fixed in 3.77

**Comment by LeeXN** [comment]
I have submitted PR #7957 to fix this panic.

### Analysis
The panic occurs because the `/tmp` directory (used for swap files by default) was cleaned up by the OS (e.g., `systemd-tmpfiles`) while the process was running. The `NewSwapFileChunk` function fails to create the temp file when the parent directory is missing, but the error is not handled effectively. This results in a `nil` file handle being used subsequently, leading to a nil pointer dereference panic in `WriteDataAt`.

### The Fix
The PR adds logic to recreate the swap directory if it is found to be missing, ensuring the process can recover gracefully instead of crashing.

### Workaround / Best Practice
To strictly prevent this issue without code changes, it is recommended to configure a persistent cache directory instead of using the volatile `/tmp`.

**Example:**
Use the `-cacheDir` flag in your start command (or systemd unit):
```bash
weed mount -dir=/mnt/your_mount -cacheDir=/var/cache/weedfs ...
