### ISSUE TITLE
weed mount panic after days IO

### ISSUE THREAD

**Issue by half-life666** [seaweedfs/seaweedfs#6168]
**Describe the bug**
weed mount crash after >7 days running IO:

```
I1026 02:08:48.684965 dirty_pages_chunked.go:82 /opt/udm/fs1/longrun/20241026_1004_244/38.file.dat saveToStorage 2813,28dff81ab1d602 [419430400,427819008)
I1026 02:08:48.688910 dirty_pages_chunked.go:82 /opt/udm/fs1/longrun/20241026_1004_244/38.file.dat saveToStorage 2809,28dff5b8e0ae95 [411041792,419430400)
I1026 02:08:48.696594 dirty_pages_chunked.go:82 /opt/udm/fs1/longrun/20241026_1004_244/38.file.dat saveToStorage 2816,28dff3dc4bc9c5 [452984832,461373440)
I1026 02:08:48.906389 dirty_pages_chunked.go:82 /opt/udm/fs1/longrun/20241026_1004_244/38.file.dat saveToStorage 2837,28dff2d9b8a7c8 [234881024,243269632)
I1026 02:08:48.915874 dirty_pages_chunked.go:82 /opt/udm/fs1/longrun/20241026_1004_244/38.file.dat saveToStorage 2823,28dff7e28e6eae [478150656,486539264)
I1026 02:08:48.970290 dirty_pages_chunked.go:82 /opt/udm/fs1/longrun/20241026_1004_244/38.file.dat saveToStorage 2817,28dff6fb86cc86 [511705088,520093696)
I1026 02:08:48.994513 dirty_pages_chunked.go:82 /opt/udm/fs1/longrun/20241026_1004_244/38.file.dat saveToStorage 2795,28dffa966fc65e [469762048,478150656)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xad7308]

goroutine 4608039 [running]:
github.com/seaweedfs/seaweedfs/weed/filer.(*FileChunkSection).setupForRead(0x3ae5ce0?, 0x4009d84000?, 0x10?)
        /seaweedfs/weed/filer/filechunk_section.go:66 +0x2c8
github.com/seaweedfs/seaweedfs/weed/filer.(*FileChunkSection).readDataAt(0x4008748900, 0x4004d14480?, 0x1?, {0x4009dc4000, 0xc0000, 0xc0000}, 0x4000000)
        /seaweedfs/weed/filer/filechunk_section.go:100 +0x44
github.com/seaweedfs/seaweedfs/weed/filer.(*ChunkGroup).ReadDataAt(0x4004d14420, 0x1f400000, {0x4009d84000, 0x100000, 0x100000}, 0x3fc0000)
        /seaweedfs/weed/filer/filechunk_group.go:67 +0x230
github.com/seaweedfs/seaweedfs/weed/mount.(*FileHandle).readFromChunks(0x400b682180, {0x4009d84000, 0x100000, 0x100000}, 0x3fc0000)
        /seaweedfs/weed/mount/filehandle_read.go:61 +0x41c
github.com/seaweedfs/seaweedfs/weed/mount.readDataByFileHandle({0x4009d84000, 0x100000, 0x100000}, 0x400b682180, 0x3fc0000)
        /seaweedfs/weed/mount/weedfs_file_read.go:81 +0xb0
github.com/seaweedfs/seaweedfs/weed/mount.(*WFS).Read(0x4001327d58?, 0x400606a008?, 0x400606a1a0, {0x4009d84000, 0x100000, 0x100000})
        /seaweedfs/weed/mount/weedfs_file_read.go:49 +0xec
github.com/hanwen/go-fuse/v2/fuse.doRead(0x40006b2b60, 0x400606a008)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.6.1/fuse/opcode.go:399 +0x80
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0x40006b2b60, 0x400606a008)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.6.1/fuse/server.go:560 +0x26c
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0x40006b2b60, 0x1)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.6.1/fuse/server.go:533 +0xec
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest in goroutine 4608038
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.6.1/fuse/server.go:365 +0x51c

```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
version 30GB 3.77  linux amd64

- if using filer, show the content of `filer.toml`

**Expected behavior**
no panic

**Screenshots**

**Additional context**
Looking at below code:
```go

func (section *FileChunkSection) setupForRead(group *ChunkGroup, fileSize int64) {
	if section.isPrepared {
		section.reader.fileSize = fileSize
		return
	}

	section.lock.Lock()
	defer section.lock.Unlock()

	if section.isPrepared {
		section.reader.fileSize = fileSize
		return
	}
```

I think the problem is clear, the first `if section.isPrepared` is not in lock protection, meaning this `setupForRead` is not thread safe. If 2 threads have contention for this function, it's possible that one thread is closeing sectoin.reader, another is trying to access the `section.reader.fileSize`.

**Comment by half-life666** [comment]
pr https://github.com/seaweedfs/seaweedfs/pull/6169
