### ISSUE TITLE
 upload file failed, http: server gave HTTP response to HTTPS client?

### ISSUE THREAD

**Issue by hupeipei888** [seaweedfs/seaweedfs#6394]
upload to seaweedfs(wihout TLS) in aws-sdk-s3 error

java log
```
十二月 25, 2024 2:49:30 下午 com.amazonaws.util.VersionInfoUtils printDeprecationAnnouncement
警告: The AWS SDK for Java 1.x entered maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/
You can print where on the file system the AWS SDK for Java 1.x core runtime is located by setting the AWS_JAVA_V1_PRINT_LOCATION environment variable or aws.java.v1.printLocation system property to 'true'.
This message can be disabled by setting the AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT environment variable or aws.java.v1.disableDeprecationAnnouncement system property to 'true'.
The AWS SDK for Java 1.x is being used here:
at java.lang.Thread.getStackTrace(Thread.java:1564)
at com.amazonaws.util.VersionInfoUtils.printDeprecationAnnouncement(VersionInfoUtils.java:81)
at com.amazonaws.util.VersionInfoUtils.<clinit>(VersionInfoUtils.java:59)
at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:95)
at com.bes.demo.seaweedfs.upload.UploadDemo.main(UploadDemo.java:32)
Bucket already exists
Object upload started
com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error, please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 1735109374166314729; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1912)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1450)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1419)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1183)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:838)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:805)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:735)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:581)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5605)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5552)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:428)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6686)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1916)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1876)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:169)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:149)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:115)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

seaweedfs log 
```
I1225 14:55:15.370181 filer_notify.go:104 metadata log write failed /topics/.system/log/2024-12-25/06-49.0a52ceda: upload data http://192.168.0.77:8080/4,e51197e2c4: upload  132 bytes to http://192.168.0.77:8080/4,e51197e2c4: Post "https://192.168.0.77:8080/4,e51197e2c4": http: server gave HTTP response to HTTPS client
W1225 14:55:16.108502 upload_content.go:190 uploading 0 to http://192.168.0.77:8080/1,e69e913a25: upload  132 bytes to http://192.168.0.77:8080/1,e69e913a25: Post "https://192.168.0.77:8080/1,e69e913a25": http: server gave HTTP response to HTTPS client
W1225 14:55:16.584233 upload_content.go:190 uploading 1 to http://192.168.0.77:8080/1,e69e913a25: upload  132 bytes to http://192.168.0.77:8080/1,e69e913a25: Post "https://192.168.0.77:8080/1,e69e913a25": http: server gave HTTP response to HTTPS client
W1225 14:55:17.296720 upload_content.go:190 uploading 2 to http://192.168.0.77:8080/1,e69e913a25: upload  132 bytes to http://192.168.0.77:8080/1,e69e913a25: Post "https://192.168.0.77:8080/1,e69e913a25": http: server gave HTTP response to HTTPS client
I1225 14:55:17.296766 filer_notify.go:104 metadata log write failed /topics/.system/log/2024-12-25/06-49.0a52ceda: upload data http://192.168.0.77:8080/1,e69e913a25: upload  132 bytes to http://192.168.0.77:8080/1,e69e913a25: Post "https://192.168.0.77:8080/1,e69e913a25": http: server gave HTTP response to HTTPS client
W1225 14:55:18.035564 upload_content.go:190 uploading 0 to http://192.168.0.77:8080/6,e7ab2504d1: upload  132 bytes to http://192.168.0.77:8080/6,e7ab2504d1: Post "https://192.168.0.77:8080/6,e7ab2504d1": http: server gave HTTP response to HTTPS client
W1225 14:55:18.510585 upload_content.go:190 uploading 1 to http://192.168.0.77:8080/6,e7ab2504d1: upload  132 bytes to http://192.168.0.77:8080/6,e7ab2504d1: Post "https://192.168.0.77:8080/6,e7ab2504d1": http: server gave HTTP response to HTTPS client
W1225 14:55:19.222778 upload_content.go:190 uploading 2 to http://192.168.0.77:8080/6,e7ab2504d1: upload  132 bytes to http://192.168.0.77:8080/6,e7ab2504d1: Post "https://192.168.0.77:8080/6,e7ab2504d1": http: server gave HTTP response to HTTPS client
I1225 14:55:19.222829 filer_notify.go:104 metadata log write failed /topics/.system/log/2024-12-25/06-49.0a52ceda: upload data http://192.168.0.77:8080/6,e7ab2504d1: upload  132 bytes to http://192.168.0.77:8080/6,e7ab2504d1: Post "https://192.168.0.77:8080/6,e7ab2504d1": http: server gave HTTP response to HTTPS client

```

**Describe the bug**
```
<dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-s3</artifactId>
        <version>1.12.780</version>
    </dependency>
```

```
String bucketName = "bucket1";
        File file = new File("D:\\data\\dump\\test.csv");
        String keyName = "test/" + file.getName();

        try {
            AWSCredentials credentials = new BasicAWSCredentials("bes", "B#2008_2108#es");
            ClientConfiguration clientConfiguration = new ClientConfiguration();
            clientConfiguration.setSignerOverride("AWSS3V4SignerType");

            AmazonS3 s3Client = AmazonS3ClientBuilder
                    .standard()
                    .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(
                            "http://192.168.0.77:8333", Regions.US_WEST_1.name()))
                    .withPathStyleAccessEnabled(true)
                    .withClientConfiguration(clientConfiguration)
                    .withCredentials(new AWSStaticCredentialsProvider(credentials))
                    .build();

            TransferManager tm = TransferManagerBuilder.standard()
                    .withS3Client(s3Client)
                    .build();


            if (!s3Client.doesBucketExistV2(bucketName)) {
                // Because the CreateBucketRequest object doesn't specify a region, the
                // bucket is created in the region specified in the client.
                s3Client.createBucket(new CreateBucketRequest(bucketName));

                // Verify that the bucket was created by retrieving it and checking its location.
                String bucketLocation = s3Client.getBucketLocation(new GetBucketLocationRequest(bucketName));
                System.out.println("Bucket location: " + bucketLocation);
            } else {
                System.out.println("Bucket already exists");
            }

            // TransferManager processes all transfers asynchronously,
            // so this call returns immediately.
            Upload upload = tm.upload(bucketName, keyName, file);
            System.out.println("Object upload started");

            // Optionally, wait for the upload to finish before continuing.
            upload.waitForCompletion();
            System.out.println("Object upload complete");
        } catch (AmazonServiceException e) {
            // The call was transmitted successfully, but Amazon S3 couldn't process
            // it, so it returned an error response.
            e.printStackTrace();
        } catch (SdkClientException e) {
            // Amazon S3 couldn't be contacted for a response, or the client
            // couldn't parse the response from Amazon S3.
            e.printStackTrace();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
```

**System Setup**
seaweedfs 3.80
```
nohup weed server -master.port=9333 -volume.port=8080 -volume.max=100 -dir="/data/seaweedfs/data" -ip="192.168.0.77" -filer -s3 > /data/seaweedfs/logs/server.log 2>&1 &
```
java 1.8
aws-java-sdk-s3 
```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
    <version>1.12.780</version>
</dependency>
```

**Expected behavior**
upload file successfully 

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
@hupeipei888 what was the problem?

**Comment by hupeipei888** [comment]
sorry, for some security policy mistakes.
